--- Deploy 29/12/2022
--- XNTC - Khí máu và điện giải EG7
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thở máy',N'Ventilator support',N'BGACE1',N'BGACE',N'A03_165_061222_V',N'1',N'1',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'BGACE2',N'BGACE1',N'A03_165_061222_V',N'2',N'2',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'BGACE3',N'BGACE1',N'A03_165_061222_V',N'2',N'3',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mode thở',N'Ventilator Mode',N'BGACE4',N'BGACE',N'A03_165_061222_V',N'1',N'4',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mode thở',N'Ventilator Mode',N'BGACE5',N'BGACE4',N'A03_165_061222_V',N'2',N'5',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Huyết áp',N'Blood Pressure',N'BGACE6',N'BGACE',N'A03_165_061222_V',N'1',N'6',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Huyết áp tối đa',N'Huyết áp tối đa',N'BGACE7',N'BGACE6',N'A03_165_061222_V',N'2',N'7',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Huyết áp tối thiểu',N'Huyết áp tối thiểu',N'BGACE8',N'BGACE6',N'A03_165_061222_V',N'2',N'8',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Vt',N'Vt',N'BGACE9',N'BGACE',N'A03_165_061222_V',N'1',N'9',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Vt',N'Vt',N'BGACE10',N'BGACE9',N'A03_165_061222_V',N'2',N'10',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'f',N'f',N'BGACE11',N'BGACE9',N'A03_165_061222_V',N'2',N'11',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nhịp thở',N'Nhịp thở',N'BGACE12',N'BGACE',N'A03_165_061222_V',N'1',N'12',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nhịp thở',N'Nhịp thở',N'BGACE13',N'BGACE12',N'A03_165_061222_V',N'2',N'13',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'FIO2',N'FIO2',N'BGACE14',N'BGACE',N'A03_165_061222_V',N'1',N'14',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'FIO2',N'FIO2',N'BGACE15',N'BGACE14',N'A03_165_061222_V',N'2',N'15',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nhiệt độ',N'Temperature',N'BGACE16',N'BGACE',N'A03_165_061222_V',N'1',N'16',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nhiệt độ',N'Temperature',N'BGACE17',N'BGACE16',N'A03_165_061222_V',N'2',N'17',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Allen Test',N'Allen Test',N'BGACE18',N'BGACE',N'A03_165_061222_V',N'1',N'18',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Allen Test',N'Allen Test',N'BGACE19',N'BGACE18',N'A03_165_061222_V',N'2',N'19',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Vị trí lấy mẫu',N'Collection site',N'BGACE20',N'BGACE',N'A03_165_061222_V',N'1',N'20',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Vị trí lấy mẫu',N'Collection site',N'BGACE21',N'BGACE20',N'A03_165_061222_V',N'2',N'21',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'pH',N'pH',N'BGACE22',N'BGACE',N'A03_165_061222_V',N'1',N'22',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE23',N'BGACE22',N'A03_165_061222_V',N'2',N'23',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em',N'Trẻ em',N'BGACE24',N'BGACE22',N'A03_165_061222_V',N'2',N'24',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'pCO2',N'pCO2',N'BGACE25',N'BGACE',N'A03_165_061222_V',N'1',N'25',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE26',N'BGACE25',N'A03_165_061222_V',N'2',N'26',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em',N'Trẻ em',N'BGACE27',N'BGACE25',N'A03_165_061222_V',N'2',N'27',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'pO2',N'pO2',N'BGACE28',N'BGACE',N'A03_165_061222_V',N'1',N'28',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE29',N'BGACE28',N'A03_165_061222_V',N'2',N'29',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em',N'Trẻ em',N'BGACE30',N'BGACE28',N'A03_165_061222_V',N'2',N'30',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ sơ sinh',N'Trẻ sơ sinh',N'BGACE31',N'BGACE28',N'A03_165_061222_V',N'2',N'31',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'BE',N'BE',N'BGACE32',N'BGACE',N'A03_165_061222_V',N'1',N'32',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE33',N'BGACE32',N'A03_165_061222_V',N'2',N'33',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'HCO3',N'HCO3',N'BGACE34',N'BGACE',N'A03_165_061222_V',N'1',N'34',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE35',N'BGACE34',N'A03_165_061222_V',N'2',N'35',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'TCO2',N'TCO2',N'BGACE36',N'BGACE',N'A03_165_061222_V',N'1',N'36',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE37',N'BGACE36',N'A03_165_061222_V',N'2',N'37',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'SO2',N'SO2',N'BGACE38',N'BGACE',N'A03_165_061222_V',N'1',N'38',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE39',N'BGACE38',N'A03_165_061222_V',N'2',N'39',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Na',N'Na',N'BGACE40',N'BGACE',N'A03_165_061222_V',N'1',N'40',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE41',N'BGACE40',N'A03_165_061222_V',N'2',N'41',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em và trẻ sơ sinh',N'Trẻ em và trẻ sơ sinh',N'BGACE42',N'BGACE40',N'A03_165_061222_V',N'2',N'42',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'K',N'K',N'BGACE43',N'BGACE',N'A03_165_061222_V',N'1',N'43',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE44',N'BGACE43',N'A03_165_061222_V',N'2',N'44',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em',N'Trẻ em',N'BGACE45',N'BGACE43',N'A03_165_061222_V',N'2',N'45',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ sơ sinh',N'Trẻ sơ sinh',N'BGACE46',N'BGACE43',N'A03_165_061222_V',N'2',N'46',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cl',N'Cl',N'BGACE47',N'BGACE',N'A03_165_061222_V',N'1',N'47',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE48',N'BGACE47',N'A03_165_061222_V',N'2',N'48',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em và trẻ sơ sinh',N'Trẻ em và trẻ sơ sinh',N'BGACE49',N'BGACE47',N'A03_165_061222_V',N'2',N'49',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'iCa',N'iCa',N'BGACE50',N'BGACE',N'A03_165_061222_V',N'1',N'50',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE51',N'BGACE50',N'A03_165_061222_V',N'2',N'51',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em',N'Trẻ em',N'BGACE52',N'BGACE50',N'A03_165_061222_V',N'2',N'52',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'HCT',N'HCT',N'BGACE53',N'BGACE',N'A03_165_061222_V',N'1',N'53',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE54',N'BGACE53',N'A03_165_061222_V',N'2',N'54',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ em',N'Trẻ em',N'BGACE55',N'BGACE53',N'A03_165_061222_V',N'2',N'55',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trẻ sơ sinh',N'Trẻ sơ sinh',N'BGACE56',N'BGACE53',N'A03_165_061222_V',N'2',N'56',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hgb',N'Hgb',N'BGACE57',N'BGACE',N'A03_165_061222_V',N'1',N'57',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người trưởng thành',N'Người trưởng thành',N'BGACE58',N'BGACE57',N'A03_165_061222_V',N'2',N'58',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả',N'Result',N'BGACE59',N'BGACE',N'A03_165_061222_V',N'1',N'59',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả',N'Result',N'BGACE60',N'BGACE59',N'A03_165_061222_V',N'2',N'60',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hình ảnh',N'Image',N'BGACE61',N'BGACE59',N'A03_165_061222_V',N'2',N'61',N'Text',N'',N'',N'',N'', '1');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người làm xét nghiệm',N'Technician',N'BGACECONFIRM_TEC_USERCREATED',N'BGACECONFIRM',N'BGACECONFIRM',N'1',N'1',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sĩ chỉ định',N'Referring Physician',N'BGACECONFIRM_REF',N'BGACECONFIRM',N'BGACECONFIRM',N'1',N'2',N'Label',N'',N'',N'',N'', '1');



Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chăm sóc thông tiểu, dẫn lưu',N'Urinary catheter/ drain care',N'PFEFUCDCCHKV2',N'PFEFUCDC',N'PFEF',N'2',N'2',N'Text',N'',N'0',N'',N'PFEFEN0CP0', '1');
update MasterDatas set [Order] = 3 where Code = 'PFEFUCDCNUU'
update MasterDatas set [Order] = 4 where Code = 'PFEFUCDCUUU'
update MasterDatas set [Order] = 5 where Code = 'PFEFUCDCPPP'
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACOORDIUPLOADCD1',N'IPDIAACOORDIUPLOAD',N'IPDIAACOORDI',N'2',N'1081',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACOORDIUPLOADCD2',N'IPDIAACOORDIUPLOAD',N'IPDIAACOORDI',N'2',N'1082',N'Text',N'',N'0',N'',N'', '');


Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điều dưỡng thực hiện',N'Assessment Nurse',N'FORADULTCONFIRM_USERCREATED',N'FORADULTCONFIRM_USERCREATED',N'FORADULTCONFIRM_USERCREATED',N'1',N'1',N'ConfirmForm',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điều dưỡng thực hiện',N'Assessment Nurse',N'FORFRAILELDERLYCONFIRM_USERCREATED',N'FORFRAILELDERLYCONFIRM_USERCREATED',N'FORFRAILELDERLYCONFIRM_USERCREATED',N'1',N'1',N'ConfirmForm',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điều dưỡng thực hiện',N'Assessment Nurse',N'FORCHEMOTHERAPYCONFIRM_USERCREATED',N'FORCHEMOTHERAPYCONFIRM_USERCREATED',N'FORCHEMOTHERAPYCONFIRM_USERCREATED',N'1',N'1',N'ConfirmForm',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo bác sĩ điều trị',N'Inform attending physician',N'IPDIAAUITV8IAPNEW',N'IPDIAAUITV8',N'IPDIAAU',N'2',N'541',N'Checkbox',N'',N'',N'',N'', '1');
Update MasterDatas set EnName = N'Admitted from', ViName = N'Vào khoa từ' where code = N'IPDIAAUADFRANS';
Update MasterDatas set EnName = N'Information received from', ViName = N'Người khai thông tin' where code = N'IPDIAAUINRFANS';
Update MasterDatas set EnName = N'Pain frequency', ViName = N'Tần suất đau' where code = N'IPDIAAUPAFRANS';
Update MasterDatas set EnName = N'Status', ViName = N'Trạng thái' where code = N'IPDIAAUMESTANS';
Update MasterDatas set EnName = N'Status', ViName = N'Trạng thái' where code = N'IPDIAAUMESTOTH2TEXT';
Update MasterDatas set EnName = N'Implantable or Electronic Devices', ViName = N'Thiết bị cấy ghép' where code = N'IPDIAAUIOEDANS';
Update MasterDatas set EnName = N'Feeding route', ViName = N'Đường ăn, uống' where code = N'IPDIAAUFEROANS';
Update MasterDatas set EnName = N'Bowel habits', ViName = N'Thói quen đại tiện' where code = N'IPDIAAUBOHAANS';
Update MasterDatas set EnName = N'Urinary assessment', ViName = N'Tiết niệu' where code = N'IPDIAAUURASANS';
Update MasterDatas set EnName = N'Living with', ViName = N'Đang ở cùng ai' where code = N'IPDIAAULIWIANS';
Update MasterDatas set EnName = N'Employment', ViName = N'Việc làm' where code = N'IPDIAAUEMPLANS';
Update MasterDatas set EnName = N'Sole provider', ViName = N'Là lao động chính trong gia đình' where code = N'IPDIAAUSOPRANS';
Update MasterDatas set EnName = N'Alcohol use (*)', ViName = N'Sử dụng chất cồn (*)' where code = N'IPDIAAUALUSANS';
Update MasterDatas set EnName = N'Tobacco or street drug use (*)', ViName = N'Thuốc lá hoặc thuốc gây nghiện (*)' where code = N'IPDIAAUTOSDDET';
Update MasterDatas set EnName = N'Legal Issue (*)', ViName = N'Hiện có rắc rối pháp lý (*)' where code = N'IPDIAAULEISDET';
Update MasterDatas set EnName = N'Self-injury (*)', ViName = N'Có dấu hiệu tự làm thương tổn bản thân (*)' where code = N'IPDIAAUSEINDET';
Update MasterDatas set EnName = N'Suicidal tendency (*)', ViName = N'Có biểu hiện muốn tự tử (*)' where code = N'IPDIAAUSUTEDET';
Update MasterDatas set EnName = N'Abuse suspected (**)', ViName = N'Có dấu hiệu nghi ngờ bị lạm dụng (**)' where code = N'IPDIAAUABSUDET';
Update MasterDatas set EnName = N'T', ViName = N'Thân nhiệt' where code = N'IPDIAAUTEMP';


Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'XNTC - Khí máu và điện giải EG7+',N'POCT - Blood gas analysis (Cartridge EG7+)',N'A03_165_061222_V',N'KQXN',N'NHOMBIEUMAU',N'2',N'25',N'Label',N'',N'',N'',N'', '');

--kiểm thảo tử vong ver 2 type KHSBA nhóm HSBA
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trích biên bản kiểm thảo tử vong V2',N'Trích biên bản kiểm thảo tử vong V2',N'MortalityReportV2',N'KHAC',N'NHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');