
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thời gian đông máu - ACT',N'Kaolin ACT',N'KAOLINACT1',N'KAOLINACT',N'A03_041_080322_V',N'1',N'1',N'Label',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khoảng tham chiếu',N'Reference Interval',N'KAOLINACT2',N'KAOLINACT',N'A03_041_080322_V',N'1',N'2',N'Label',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'82 - 152',N'82 - 152',N'KAOLINACT3',N'KAOLINACT2',N'A03_041_080322_V',N'2',N'3',N'Text',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giá trị thấp',N'Low value',N'KAOLINACT4',N'KAOLINACT',N'A03_041_080322_V',N'1',N'4',N'Label',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'N/A',N'NA',N'KAOLINACT5',N'KAOLINACT4',N'A03_041_080322_V',N'2',N'4',N'Text',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giá trị cao',N'High value',N'KAOLINACT6',N'KAOLINACT',N'A03_041_080322_V',N'1',N'5',N'Label',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 240',N'≥ 240',N'KAOLINACT7',N'KAOLINACT6',N'A03_041_080322_V',N'2',N'5',N'Text',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả',N'Result',N'KAOLINACT8',N'KAOLINACT',N'A03_041_080322_V',N'1',N'6',N'Label',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả',N'Result',N'KAOLINACT9',N'KAOLINACT8',N'A03_041_080322_V',N'2',N'6',N'Text',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đơn vị',N'Unit',N'KAOLINACT10',N'KAOLINACT',N'A03_041_080322_V',N'1',N'7',N'Label',N'',N'0',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'giây',N'sec',N'KAOLINACT11',N'KAOLINACT10',N'A03_041_080322_V',N'2',N'8',N'Text',N'',N'0',N'',N'', '1');

insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Tạo mới] ALL XNTC - Đông máu ACT' , N'APICRIPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Chỉnh sửa] ALL XNTC - Đông máu ACT' , N'APIUDIPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xác nhận] ALL XNTC - Đông máu ACT ' , N'APICFIPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xem] ALL XNTC - Đông máu ACT' , N'APIGDTIPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Tạo mới] ALL XNTC - Đông máu ACT' , N'APICROPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Chỉnh sửa] ALL XNTC - Đông máu ACT' , N'APIUDOPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xác nhận] ALL XNTC - Đông máu ACT ' , N'APICFOPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xem] ALL XNTC - Đông máu ACT' , N'APIGDTOPDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Tạo mới] ALL XNTC - Đông máu ACT' , N'APICREDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'ED'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Chỉnh sửa] ALL XNTC - Đông máu ACT' , N'APIUDEDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'ED'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xác nhận] ALL XNTC - Đông máu ACT ' , N'APICFEDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'ED'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xem] ALL XNTC - Đông máu ACT' , N'APIGDTEDA03_041_080322_V', (select id from VisitTypeGroups where Code = 'ED'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Tạo mới] ALL XNTC - Đông máu ACT' , N'APICREOCA03_041_080322_V', (select id from VisitTypeGroups where Code = 'EOC'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Chỉnh sửa] ALL XNTC - Đông máu ACT' , N'APIUDEOCA03_041_080322_V', (select id from VisitTypeGroups where Code = 'EOC'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xác nhận] ALL XNTC - Đông máu ACT' , N'APICFEOCA03_041_080322_V', (select id from VisitTypeGroups where Code = 'EOC'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[Xem] ALL XNTC - Đông máu ACT' , N'APIGDTEOCA03_041_080322_V', (select id from VisitTypeGroups where Code = 'EOC'));

INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'XNTC - Đông máu ACT (Cartridge Kaolin ACT)', 'A03_041_080322_V', 'IPD')
INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'XNTC - Đông máu ACT (Cartridge Kaolin ACT)', 'A03_041_080322_V', 'OPD')
INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'XNTC - Đông máu ACT (Cartridge Kaolin ACT)', 'A03_041_080322_V', 'ED')
INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'XNTC - Đông máu ACT (Cartridge Kaolin ACT)', 'A03_041_080322_V', 'EOC')
