insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD] Xem Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)' , N'IPDVIEW13NHI', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD] Chỉnh sửa Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)' , N'IPDEDIT13NHI', (select id from VisitTypeGroups where Code = 'IPD'));

insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][ĐD CHỈNH SỬA] Thang điểm HUMPTY DUMPTY đánh giá nguy cơ ngã ở trẻ em' , N'IPDDDCS', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][XEM] Thang điểm HUMPTY DUMPTY đánh giá nguy cơ ngã ở trẻ em' , N'IPDXEM', (select id from VisitTypeGroups where Code = 'IPD'));

insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][TẠO] Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ sơ sinh ' , N'IPDNOC1', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][XEM CHI TIẾT] Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ sơ sinh ' , N'IPDNOC2', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][CẬP NHẬT] Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ sơ sinh ' , N'IPDNOC3', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][XEM DANH SÁCH] Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ sơ sinh ' , N'IPDNOC4', (select id from VisitTypeGroups where Code = 'IPD'));

insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][ĐD TẠO MỚI] Bảng điểm GLAMORGAN sàng lọc loét do tỳ ép ở trẻ nhi và sơ sinh' , N'IPDGLAMORGANPOST', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][ĐD CHỈNH SỬA] Bảng điểm GLAMORGAN sàng lọc loét do tỳ ép ở trẻ nhi và sơ sinh' , N'IPDGLAMORGANPUT', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][XEM] Bảng điểm GLAMORGAN sàng lọc loét do tỳ ép ở trẻ nhi và sơ sinh' , N'IPDGLAMORGANGET', (select id from VisitTypeGroups where Code = 'IPD'));