# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- sprint-20

pool:
  name: 'Eform_UAT'

variables:
  solution: 'EFormCustomBuilder.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: 'none'
  displayName: 'Checkout code from repo'
- script: |
    echo ##[command]
    cd C:\\agents\\_work\\3\\s
    echo ##[command]
    git pull origin sprint-20
  displayName: 'Get newest code from sprint-20'
- task: MSBuild@1
  inputs:
    solution: 'EFormCustomBuilder.sln'
    msbuildLocationMethod: 'location'
    msbuildLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin'
    platform: 'Any CPU'
    configuration: Release
    clean: false
#- script: |
#    echo ##[copy file]
#    xcopy C:\\agents\\_work\\3\\s\\Application\\EForm\\bin C:\EMR\DEV\bin /E /Y