-- THEM GROUP NHOM HSBA
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD Theo dõi điều dưỡng',N'OPD Theo dõi điều dưỡng',N'OPDTDDD',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Theo dõi điều dưỡng',N'ED Theo dõi điều dưỡng',N'EDTDDD',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Theo dõi điều dưỡng',N'EOC Theo dõi điều dưỡng',N'EOCTDDD',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Biểu mẫu không thuộc HSBA',N'EOC Biểu mẫu không thuộc HSBA',N'EOCBMKTHSBA',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');

-- ACT Đông máu
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD ACT Khí Đông máu ',N'IPD ACT Khí Đông máu ',N'CatridgeKaolinACT',N'IPDKQXN',N'IPDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD ACT Khí Đông máu ',N'OPD ACT Khí Đông máu ',N'CatridgeKaolinACT',N'OPDKQXN',N'OPDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED ACT Khí Đông máu ',N'ED ACT Khí Đông máu ',N'CatridgeKaolinACT',N'EDKQXN',N'EDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC ACT Khí Đông máu ',N'EOC ACT Khí Đông máu ',N'CatridgeKaolinACT',N'EOCKQXN',N'EOCNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');

--setup quản lý thai nghén 
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Quản lý thai nghén',N'Pregnancy follow up record',N'A01_067_050919_VE',N'OPDSANPHUKHOA',N'A01_067_050919_VE',N'2',N'',N'',N'OPD',N'',N'',N'', '');

--quản lý thai nghén nhóm HSBA
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Quản lý thai nghén',N'Pregnancy follow up record',N'PregnancyFollowUpRecord',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'15',N'Label',N'',N'',N'',N'', '');

-- Chẩn đoán hình ảnh
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'Xem Lịch sử chẩn đoán hình ảnh' , N'VIEWRADIOLOGY', NULL);
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'Xem chi tiết lịch sử chẩn đoán hình ảnh' , N'VIEWDETAILTRADIOLOGY', NULL);
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'In báo cáo chẩn đoán hình ảnh' , N'PRINTRADIOLOGY', NULL);

--- người bệnh chuẩn bị trước phẫu thuật
INSERT INTO Forms(Id, CreatedAt, UpdatedAt, [Name], Code, VisitTypeGroupCode,IsDeleted, [Time])
VALUES(NEWID(),GETDATE(),GETDATE(),N'Yêu cầu người bệnh chuẩn bị trước khi phẫu thuật thủ thuật','A02_052_050919_V','IPD',0, 1)

insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Xem] Yêu cầu người bệnh chuẩn bị trước khi phẫu thuật thủ thuật' , N'APIGDTIPDA02_052_050919_V', NULL);
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Sửa] Yêu cầu người bệnh chuẩn bị trước khi phẫu thuật thủ thuật' , N'APIUDIPDA02_052_050919_V', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Tạo] Yêu cầu người bệnh chuẩn bị trước khi phẫu thuật thủ thuật' , N'APICRIPDA02_052_050919_V', (select id from VisitTypeGroups where Code = 'IPD'));

-- nhóm hsba
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Yêu cầu bệnh nhân chuẩn bị trước khi phẫu thuật',N'Yêu cầu bệnh nhân chuẩn bị trước khi phẫu thuật',N'IPD_A02_052_050919_V',N'IPDPTTT',N'IPDNHOMBIEUMAU',N'2',N'7',N'',N'',N'',N'',N'', '');
-------------------------------

-- xin lấy bánh rau 
--action
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Sửa] Bản cam kết xin lấy bánh rau không theo quy định quản lý của Bệnh viện' , N'APIUDIPDA01_159_050919_VE', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Tạo] Bản cam kết xin lấy bánh rau không theo quy định quản lý của Bệnh viện' , N'APICRIPDA01_159_050919_VE', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Xác nhận] Bản cam kết xin lấy bánh rau không theo quy định quản lý của Bệnh viện' , N'APICFIPDA01_159_050919_VE', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][ Xem Chi tiết] Bản cam kết xin lấy bánh rau không theo quy định quản lý của Bệnh viện' , N'APIGDTIPDA01_159_050919_VE', NULL);

-- unlocked
INSERT INTO Forms(Id, CreatedAt, UpdatedAt, [Name], Code, VisitTypeGroupCode,IsDeleted)
VALUES(NEWID(),GETDATE(),GETDATE(),N'Bản cam kết xin lấy bánh rau không theo quy định quản lý của Bệnh viện','A01_159_050919_VE','IPD',0)

-- nhóm hsba
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bản cam kết xin lấy bánh rau không theo quy định quản lý của Bệnh viện',N'Bản cam kết xin lấy bánh rau không theo quy định quản lý của Bệnh viện',N'IPD_A01_159_050919_VE',N'IPDHCCK',N'IPDNHOMBIEUMAU',N'2',N'6',N'',N'',N'',N'',N'', '');
------------------------


-- phiếu chăm sóc ver2
INSERT INTO AppConfigs(Id, [Key], [Label], [Value], IsDeleted, CreatedAt)
VALUES(NEWID(), 'UPDATE_CARENOTE_VESION2', N'Thời gian cập nhật thêm sơ sinh vào hồ sơ của sản phụ phiếu chăm sóc', FORMAT(GETDATE(), 'yyyy/MM/dd HH:mm tt zzz'), 0, GETDATE())


--phiếu điều trị ver2
INSERT INTO AppConfigs(Id, [Key], [Label], [Value], IsDeleted, CreatedAt)
VALUES(NEWID(), 'UPDATE_PHYSICIAN_VESION2', N'Thời gian cập nhật thêm sơ sinh vào hồ sơ của sản phụ phiếu điều trị', FORMAT(GETDATE(), 'yyyy/MM/dd HH:mm tt zzz'), 0, GETDATE())


update IPDInitialAssessmentForNewborns set [Version] = 1
--Ẩn đánh giá ban đầu trẻ vừa sinh
INSERT INTO AppConfigs(Id, [Key], [Label], [Value], IsDeleted, CreatedAt)
VALUES(NEWID(), 'HIDE_A02_016_050919_VE', N'Ẩn toàn bộ Phiếu đánh giá ban đầu trẻ vừa sinh với hồ sơ tiếp sau thòi gian này', FORMAT(GETDATE(), 'yyyy/MM/dd HH:mm tt zzz'), 0, GETDATE())

-- đánh giá trẻ sau 2 h sinh
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá tình trạng trẻ trong 2 giờ sau sinh',N'Đánh giá tình trạng trẻ trong 2 giờ sau sinh',N'ForUterineLife2Hours_Obstetrics',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'20',N'Label',N'',N'',N'',N'', '');
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][XEM] Đánh giá tình trạng trẻ trong 2 giờ sau sinh' , N'IPDVIEW2HOURSV2', NULL);
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Tạo mới] Đánh giá tình trạng trẻ trong 2 giờ sau sinh' , N'IPDCREATE2HOURSV2', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Chỉnh sửa] Đánh giá tình trạng trẻ trong 2 giờ sau sinh' , N'IPDUPDATE2HOURSV2', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Xác nhận] Đánh giá tình trạng trẻ trong 2 giờ sau sinh' , N'IPDCONFIRM2HOURSV2', (select id from VisitTypeGroups where Code = 'IPD'));

INSERT INTO Forms(Id, CreatedAt, UpdatedAt, [Name], Code, VisitTypeGroupCode,IsDeleted)
VALUES(NEWID(),GETDATE(),GETDATE(),N'Đánh giá tình trạng trẻ trong 2 giờ sau sinh','A02_016_061022_VE','IPD',0)



-- HSBA đánh giá trẻ vừa sinh sản phụ + sơ sinh
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu cho trẻ vừa sinh',N'Đánh giá ban đầu cho trẻ vừa sinh',N'ForNeonatalMaternity',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'21',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu cho trẻ vừa sinh',N'Đánh giá ban đầu cho trẻ vừa sinh',N'ForNeonatalMaternity_Obstetrics',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'21',N'Label',N'',N'',N'',N'', '');

insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][XEM] Đánh giá ban đầu cho trẻ vừa sinh Version 2' , N'IPDVIEWMATERNITYV2', NULL);
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Tạo mới] Đánh giá ban đầu cho trẻ vừa sinh Version 2' , N'IPDCREATEMATERNITYV2', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Chỉnh sửa] Đánh giá ban đầu cho trẻ vừa sinh Version 2' , N'IPDUPDATEMATERNITYV2', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Xác nhận] Đánh giá ban đầu cho trẻ vừa sinh Version 2' , N'IPDCONFIRMMATERNITYV2', (select id from VisitTypeGroups where Code = 'IPD'));

--Hô hấp tiễn phẫu
--Unlocked
INSERT INTO Forms(Id, CreatedAt, UpdatedAt, [Name], Code, VisitTypeGroupCode,IsDeleted, Time)
VALUES(NEWID(),GETDATE(),GETDATE(),N'Phiếu yêu cầu khám chuyên khoa hô hấp tiền phẫu','FORMOPDPYKKCKHHTP','OPD',0, 1)

--acction
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD][Tạo mới] Bác Sĩ  Phiếu yêu cầu khám chuyên khoa hô hấp tiền phẫu' , N'APICROPDFORMOPDPYKKCKHHTP', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD][Chỉnh sửa] Bác Sĩ  Phiếu yêu cầu khám chuyên khoa hô hấp tiền phẫu' , N'APIUDOPDFORMOPDPYKKCKHHTP', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD][Xem chi tiết] Bác Sĩ  Phiếu yêu cầu khám chuyên khoa hô hấp tiền phẫu' , N'APIGDTOPDFORMOPDPYKKCKHHTP', NULL);
-- nhóm HSBA
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu yêu cầu khám chuyên khoa hô hấp tiền phẫu',N'Phiếu yêu cầu khám chuyên khoa hô hấp tiền phẫu',N'OPDPYCKCKHHTP',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'1',N'Label',N'',N'',N'',N'', '');
 --masterdata
 Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày yêu cầu',N'Request date',N'KHHTP01',N'KHHTP',N'KHHTP',N'1',N'1',N'Label',N'AUTOFILL',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sĩ gây mê',N'Anesthesiologist name',N'KHHTP02',N'KHHTP',N'KHHTP',N'1',N'2',N'Label',N'AUTOFILL',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'1. Thông tin bệnh nhân',N'1. Patient information',N'KHHTP03',N'KHHTP',N'KHHTP',N'1',N'3',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán',N'Diagnosis',N'KHHTP04',N'KHHTP',N'KHHTP',N'1',N'4',N'Label',N'AUTOFILL',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dự kiến phương pháp vô cảm',N'Dự kiến phương pháp vô cảm',N'KHHTP05',N'KHHTP',N'KHHTP',N'1',N'5',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dự kiến phương pháp vô cảm',N'Dự kiến phương pháp vô cảm',N'KHHTP06',N'KHHTP05',N'KHHTP',N'2',N'6',N'Text',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dấu hiệu sinh tồn',N'Vital sign',N'KHHTP07',N'KHHTP',N'KHHTP',N'1',N'7',N'Label',N'AUTOFILL',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'2. Tiền sử bệnh',N'2. Past medical history',N'KHHTP08',N'KHHTP',N'KHHTP',N'1',N'8',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hen phế quản',N'Hen phế quản',N'KHHTP09',N'KHHTP08',N'KHHTP',N'2',N'9',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hen phế quản',N'Hen phế quản',N'KHHTP10',N'KHHTP08',N'KHHTP',N'2',N'10',N'Text',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'COPD',N'COPD',N'KHHTP11',N'KHHTP08',N'KHHTP',N'2',N'11',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'COPD',N'COPD',N'KHHTP12',N'KHHTP08',N'KHHTP',N'2',N'12',N'Text',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phẫu thuật phổi',N'Phẫu thuật phổi',N'KHHTP13',N'KHHTP08',N'KHHTP',N'2',N'13',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phẫu thuật phổi',N'Phẫu thuật phổi',N'KHHTP14',N'KHHTP08',N'KHHTP',N'2',N'14',N'Text',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hội chứng ngừng thở khi ngủ',N'Hội chứng ngừng thở khi ngủ',N'KHHTP15',N'KHHTP08',N'KHHTP',N'2',N'15',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hội chứng ngừng thở khi ngủ',N'Hội chứng ngừng thở khi ngủ',N'KHHTP16',N'KHHTP08',N'KHHTP',N'2',N'16',N'Text',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chấn thương đường thở',N'Chấn thương đường thở',N'KHHTP17',N'KHHTP08',N'KHHTP',N'2',N'17',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chấn thương đường thở',N'Chấn thương đường thở',N'KHHTP18',N'KHHTP08',N'KHHTP',N'2',N'18',N'Text',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'KHHTP19',N'KHHTP08',N'KHHTP',N'2',N'19',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'KHHTP20',N'KHHTP08',N'KHHTP',N'2',N'20',N'Text',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'3. Các triệu chứng',N'3. Symptoms',N'KHHTP21',N'KHHTP',N'KHHTP',N'1',N'21',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đau ngực',N'Chest pain',N'KHHTP22',N'KHHTP',N'KHHTP',N'1',N'22',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'KHHTP23',N'KHHTP22',N'KHHTP',N'2',N'23',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'KHHTP24',N'KHHTP22',N'KHHTP',N'2',N'24',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khó thở',N'Dyspnea',N'KHHTP25',N'KHHTP',N'KHHTP',N'1',N'25',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'KHHTP32',N'KHHTP25',N'KHHTP',N'2',N'32',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'KHHTP33',N'KHHTP25',N'KHHTP',N'2',N'33',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ho kéo dài',N'Ho kéo dài',N'KHHTP34',N'KHHTP',N'KHHTP',N'1',N'34',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'KHHTP35',N'KHHTP34',N'KHHTP',N'2',N'35',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'KHHTP36',N'KHHTP34',N'KHHTP',N'2',N'36',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cơn hen cấp',N'Cơn hen cấp',N'KHHTP37',N'KHHTP',N'KHHTP',N'1',N'37',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'KHHTP38',N'KHHTP37',N'KHHTP',N'2',N'38',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'KHHTP39',N'KHHTP37',N'KHHTP',N'2',N'39',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không áp dụng',N'N/A',N'KHHTP40',N'KHHTP37',N'KHHTP',N'2',N'40',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'4. Các phương pháp điều trị đã áp dụng',N'4. Treatment',N'KHHTP41',N'KHHTP',N'KHHTP',N'1',N'41',N'Label',N'AUTOFILL',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'5. Thông tin về ca mổ',N'5. Surgery',N'KHHTP42',N'KHHTP',N'KHHTP',N'1',N'42',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phương pháp phẫu thuật',N'Type of surgery',N'KHHTP43',N'KHHTP',N'KHHTP',N'1',N'43',N'Label',N'AUTOFILL',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày phẫu thuật dự kiến',N'Date of surgery',N'KHHTP44',N'KHHTP',N'KHHTP',N'1',N'44',N'Label',N'AUTOFILL',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có thể trì hoãn hay không?',N'Can be post-ponded',N'KHHTP45',N'KHHTP',N'KHHTP',N'1',N'45',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'KHHTP46',N'KHHTP45',N'KHHTP',N'2',N'46',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'KHHTP47',N'KHHTP45',N'KHHTP',N'2',N'47',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nguy cơ phẫu thuật',N'Surgical risk',N'KHHTP48',N'KHHTP',N'KHHTP',N'1',N'48',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cao',N'High',N'KHHTP49',N'KHHTP48',N'KHHTP',N'2',N'49',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trung bình',N'Intermediate',N'KHHTP50',N'KHHTP48',N'KHHTP',N'2',N'50',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thấp',N'Low',N'KHHTP51',N'KHHTP48',N'KHHTP',N'2',N'51',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nguy cơ đường thở khó',N'Nguy cơ đường thở khó',N'KHHTP52',N'KHHTP',N'KHHTP',N'1',N'52',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cao',N'High',N'KHHTP53',N'KHHTP52',N'KHHTP',N'2',N'53',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trung bình',N'Intermediate',N'KHHTP54',N'KHHTP52',N'KHHTP',N'2',N'54',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thấp',N'Low',N'KHHTP55',N'KHHTP52',N'KHHTP',N'2',N'55',N'Radio',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'6. Lý do can thiệp',N'6. Reason for the intervention',N'KHHTP56',N'KHHTP',N'KHHTP',N'1',N'56',N'Label',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ung thư',N'Oncology',N'KHHTP57',N'KHHTP56',N'KHHTP',N'2',N'57',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xuất huyết',N'Hemorrhage',N'KHHTP58',N'KHHTP56',N'KHHTP',N'2',N'58',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đe dọa tính mạng',N'Life threatening',N'KHHTP59',N'KHHTP56',N'KHHTP',N'2',N'59',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Gãy xương',N'Tracture',N'KHHTP60',N'KHHTP56',N'KHHTP',N'2',N'60',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chức năng',N'Functional',N'KHHTP61',N'KHHTP56',N'KHHTP',N'2',N'61',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'KHHTP62',N'KHHTP56',N'KHHTP',N'2',N'62',N'Checkbox',N'',N'',N'',N'KHHTP', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'KHHTP63',N'KHHTP56',N'KHHTP',N'2',N'63',N'Text',N'',N'',N'',N'KHHTP', '');

--------------------------------------

-- tim mach tiễn phẫu
-- Acction
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD][Tạo mới] Phiếu yêu cầu khám chuyên khoa tim mạch tiền phẫu' , N'APICROPDA01_204_030320_VE', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD][Chỉnh sửa] Phiếu yêu cầu khám chuyên khoa tim mạch tiền phẫu' , N'APIUDOPDA01_204_030320_VE', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD][Xem] Phiếu yêu cầu khám chuyên khoa tim mạch tiền phẫu' , N'APIGDTOPDA01_204_030320_VE', NULL);

--Unlock
INSERT INTO Forms(Id, CreatedAt, UpdatedAt, [Name], Code, VisitTypeGroupCode,IsDeleted, Time)
VALUES(NEWID(),GETDATE(),GETDATE(),N'Phiếu yêu cầu khám chuyên khoa tim mạch tiền phẫu','A01_204_030320_VE','OPD',0, 1)

-- nhóm HSBA
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu yêu cầu khám chuyên khoa tim mạch tiền phẫu',N'Phiếu yêu cầu khám chuyên khoa tim mạch tiền phẫu',N'OPD_A01_204_030320_VE',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'20',N'Label',N'',N'',N'',N'', '');
--masterdata

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày yêu cầu:',N'Request date:',N'OPDKCKTMTP01',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'1',N'Label',N'AUTOFILL',N'1',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sĩ gây mê:',N'Anesthesiologist name:',N'OPDKCKTMTP02',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'2',N'Label',N'AUTOFILL',N'1',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'I. Thông tin bệnh nhân:',N'I. Patient information:',N'OPDKCKTMTP03',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán:',N'Diagnosis:',N'OPDKCKTMTP04',N'OPDKCKTMTP03',N'OPDKCKTMTP',N'1',N'4',N'Label',N'AUTOFILL',N'1',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dự kiến phương pháp vô cảm:',N'Dự kiến phương pháp vô cảm:',N'OPDKCKTMTP05',N'OPDKCKTMTP03',N'OPDKCKTMTP',N'1',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dự kiến phương pháp vô cảm:',N'Dự kiến phương pháp vô cảm:',N'OPDKCKTMTP06',N'OPDKCKTMTP05',N'OPDKCKTMTP',N'2',N'6',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dấu hiệu sinh tồn:',N'Vital sign:',N'OPDKCKTMTP07',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'7',N'Label',N'AUTOFILL',N'1',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'II. Tiền sử bệnh:',N'II. Past medical history:',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh mạch vành',N'Coronaropathy',N'OPDKCKTMTP09',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'9',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh mạch vành',N'Bệnh mạch vành',N'OPDKCKTMTP10',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'10',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Stent mạch vành',N'Coronary Stent',N'OPDKCKTMTP11',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'11',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Stent mạch vành',N'Coronary Stent',N'OPDKCKTMTP12',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'12',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh van tim',N'Valvulopathy',N'OPDKCKTMTP13',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'13',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh van tim',N'Valvulopathy',N'OPDKCKTMTP14',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'14',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh mạch máu',N'Vascular',N'OPDKCKTMTP15',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'15',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh mạch máu',N'Vascular',N'OPDKCKTMTP16',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'16',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Rối loạn nhịp tim',N'Arthymia',N'OPDKCKTMTP17',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'17',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Rối loạn nhịp tim',N'Arthymia',N'OPDKCKTMTP18',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'18',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Huyết áp cao',N'HBP',N'OPDKCKTMTP19',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'19',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Huyết áp cao',N'HBP',N'OPDKCKTMTP20',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'20',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tăng huyết áp phổi',N'HPulmBP',N'OPDKCKTMTP21',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'21',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tăng huyết áp phổi',N'HPulmBP',N'OPDKCKTMTP22',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'22',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiểu đường',N'Diabetes',N'OPDKCKTMTP23',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'23',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiểu đường',N'Diabetes',N'OPDKCKTMTP24',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'24',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'OPDKCKTMTP25',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'25',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'OPDKCKTMTP26',N'OPDKCKTMTP08',N'OPDKCKTMTP',N'2',N'26',N'Text',N'NOT NULL',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'III. Các triệu chứng:',N'III. Symptoms:',N'OPDKCKTMTP27',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'27',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đau ngực:',N'Chest pain:',N'OPDKCKTMTP28',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'28',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'OPDKCKTMTP29',N'OPDKCKTMTP28',N'OPDKCKTMTP',N'2',N'29',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'OPDKCKTMTP30',N'OPDKCKTMTP28',N'OPDKCKTMTP',N'2',N'30',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nghi ngờ',N'Suspected',N'OPDKCKTMTP31',N'OPDKCKTMTP28',N'OPDKCKTMTP',N'2',N'31',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khó thở:',N'Dyspnea:',N'OPDKCKTMTP32',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'32',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'OPDKCKTMTP33',N'OPDKCKTMTP32',N'OPDKCKTMTP',N'2',N'33',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'OPDKCKTMTP34',N'OPDKCKTMTP32',N'OPDKCKTMTP',N'2',N'34',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phân loại suy tim theo NYHA:',N'State:',N'OPDKCKTMTP35',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'35',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không áp dụng',N'N/A',N'OPDKCKTMTP36',N'OPDKCKTMTP35',N'OPDKCKTMTP',N'2',N'36',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'1',N'1',N'OPDKCKTMTP37',N'OPDKCKTMTP35',N'OPDKCKTMTP',N'2',N'37',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'2',N'2',N'OPDKCKTMTP38',N'OPDKCKTMTP35',N'OPDKCKTMTP',N'2',N'38',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'3',N'3',N'OPDKCKTMTP39',N'OPDKCKTMTP35',N'OPDKCKTMTP',N'2',N'39',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'4',N'4',N'OPDKCKTMTP40',N'OPDKCKTMTP35',N'OPDKCKTMTP',N'2',N'40',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá khả năng hoạt động MET:',N'MET Effort capacity:',N'OPDKCKTMTP41',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'41',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≤ 4',N'≤ 4',N'OPDKCKTMTP42',N'OPDKCKTMTP41',N'OPDKCKTMTP',N'2',N'42',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'> 4',N'> 4',N'OPDKCKTMTP43',N'OPDKCKTMTP41',N'OPDKCKTMTP',N'2',N'43',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IV. Các phương pháp điều trị đã áp dụng:',N'IV. Treatment:',N'OPDKCKTMTP44',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'44',N'Label',N'AUTOFILL',N'1',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'V. Thông tin về ca mổ:',N'V. Surgery:',N'OPDKCKTMTP45',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'45',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phương pháp phẫu thuật:',N'Type of surgery:',N'OPDKCKTMTP46',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'46',N'Label',N'AUTOFILL',N'1',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày phẫu thuật dự kiến:',N'Date of surgery:',N'OPDKCKTMTP47',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'47',N'Label',N'AUTOFILL',N'1',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có thể trì hoãn hay không?:',N'Can be post-ponded:',N'OPDKCKTMTP48',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'48',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'OPDKCKTMTP49',N'OPDKCKTMTP48',N'OPDKCKTMTP',N'2',N'49',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'OPDKCKTMTP50',N'OPDKCKTMTP48',N'OPDKCKTMTP',N'2',N'50',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nguy cơ phẫu thuật:',N'Surgical risk:',N'OPDKCKTMTP51',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'51',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cao',N'High',N'OPDKCKTMTP52',N'OPDKCKTMTP51',N'OPDKCKTMTP',N'2',N'52',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trung bình',N'Intermediate',N'OPDKCKTMTP53',N'OPDKCKTMTP51',N'OPDKCKTMTP',N'2',N'53',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thấp',N'Low',N'OPDKCKTMTP54',N'OPDKCKTMTP51',N'OPDKCKTMTP',N'2',N'54',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nguy cơ chảy máu:',N'Bleeding risk:',N'OPDKCKTMTP55',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'55',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cao',N'High',N'OPDKCKTMTP56',N'OPDKCKTMTP55',N'OPDKCKTMTP',N'2',N'56',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trung bình',N'Intermediate',N'OPDKCKTMTP57',N'OPDKCKTMTP55',N'OPDKCKTMTP',N'2',N'57',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thấp',N'Low',N'OPDKCKTMTP58',N'OPDKCKTMTP55',N'OPDKCKTMTP',N'2',N'58',N'Radio',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'VI. Lý do can thiệp:',N'VI. Reason for the intervention:',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'59',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ung thư',N'Oncology',N'OPDKCKTMTP60',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'2',N'60',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xuất huyết',N'Hemorrhage',N'OPDKCKTMTP61',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'2',N'61',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đe dọa tính mạng',N'Life threatening',N'OPDKCKTMTP62',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'2',N'62',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Gãy xương',N'Fracture',N'OPDKCKTMTP63',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'2',N'63',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chức năng',N'Functional',N'OPDKCKTMTP64',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'2',N'64',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'OPDKCKTMTP65',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'2',N'65',N'Checkbox',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Other',N'OPDKCKTMTP66',N'OPDKCKTMTP59',N'OPDKCKTMTP',N'2',N'66',N'Text',N'NOT NULL',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'VII. Đánh giá điểm nguy cơ (BSGM điền phần này):',N'VII. Risk scores (to fill by anesthesiologist):',N'OPDKCKTMTP67',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'67',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điểm theo thang Lee:',N'Score de Lee:',N'OPDKCKTMTP68',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'68',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điểm theo thang Lee:',N'Score de Lee:',N'OPDKCKTMTP69',N'OPDKCKTMTP68',N'OPDKCKTMTP',N'2',N'69',N'Text',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điểm Goldman:',N'Goldman score:',N'OPDKCKTMTP70',N'OPDKCKTMTP',N'OPDKCKTMTP',N'1',N'70',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điểm Goldman:',N'Goldman score:',N'OPDKCKTMTP71',N'OPDKCKTMTP70',N'OPDKCKTMTP',N'2',N'71',N'Text',N'',N'',N'',N'', '');

