--ly do vao vien

Update MasterDatas
SET Note = '',DefaultValue = ''
where Form = 'TRANSLATEVI' or Form = 'TRANSLATEEN'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEREASON' ,Note = 'IPDTRANSLATEREASONANS,IPDTRANSLATECHIEFCOMANS'
Where Code = 'TRANSLATEREASONANS'
-- ly do nhao vien 
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECHIEFCOM' ,Note = 'IPDTRANSLATECHIEFCOMANS,IPDTRANSLATEREASONANS'
Where Code = 'TRANSLATECHIEFCOMANS'

--Lý do vào viện  = Lý do nhập viện 
--Qúa trình bệnh lý và diễn biến lâm sàng = 

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECLINEVOLU' ,Note = 'IPDTRANSLATECLINEVOLUANS'
Where Code = 'TRANSLATECLINEVOLUANS'

--Kết quả cận lâm sàng = Kết quả xét nghiệm, cận lâm sàng 

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESUBRESULT' ,Note = 'IPDTRANSLATESUBRESULTANS,IPDTRANSLATELABANDSUBRESULTANS'
Where Code = 'TRANSLATESUBRESULTANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATELABANDSUBRESULT' ,Note = 'IPDTRANSLATELABANDSUBRESULTANS,IPDTRANSLATESUBRESULTANS'
Where Code = 'TRANSLATELABANDSUBRESULTANS'

--Phương pháp điều trị = Điều trị

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREATMENTANDPROCEDURE' ,Note = 'IPDTRANSLATETREATMENTANDPROCEDUREANS,IPDTRANSLATETREATMENTANS'
Where Code = 'TRANSLATETREATMENTANDPROCEDUREANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREATMENT' ,Note = 'IPDTRANSLATETREATMENTANS,IPDTRANSLATETREATMENTANDPROCEDUREANS'
Where Code = 'TRANSLATETREATMENTANS'

--Tình trang người bệnh hiện tại 
--= Tình trạng khi ra viện 
--= Tình trạng người bệnh lúc chuyển viện
--= Tình trạng người bệnh lúc chuyển tuyến
--= Tình trạng thương tích lúc ra viện

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATCURRENTPATIENT' ,Note = 'IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS'
Where Code = 'TRANSLATCURRENTPATIENTANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECONDITIONDISCHARGE' ,Note = 'IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS'
Where Code = 'TRANSLATECONDITIONDISCHARGEANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESTATUSPATIENTTRANSFER' ,Note = 'IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS'
Where Code = 'TRANSLATESTATUSPATIENTTRANSFERANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESATATUSREFERAL' ,Note = 'IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS'
Where Code = 'TRANSLATESATATUSREFERALANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESTATUSINJURYDISCHARGE' ,Note = 'IPDTRANSLATESTATUSINJURYDISCHARGEANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESTATUSPATIENTTRANSFERANS'
Where Code = 'TRANSLATESTATUSINJURYDISCHARGEANS'


--Kế hoạch điều trị và chăm sóc tiếp theo 
--= Kế hoạch điều trị tiếp theo
--= Ghi chú
--= Hướng điều trị

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECAREPLAN' ,Note = 'IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATENOTEANS,IPDTRANSLATETREANTMENTPLANANS'
Where Code = 'TRANSLATECAREPLANANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEFOLLOWUPCAREPLAN' ,Note = 'IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATENOTEANS,IPDTRANSLATETREANTMENTPLANANS'
Where Code = 'TRANSLATEFOLLOWUPCAREPLANANS'


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATENOTE' ,Note = 'IPDTRANSLATENOTEANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATETREANTMENTPLANANS'
Where Code = 'TRANSLATENOTEANS'


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREANTMENTPLAN' ,Note = 'IPDTRANSLATETREANTMENTPLANANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATENOTEANS'
Where Code = 'TRANSLATETREANTMENTPLANANS'

--Chuẩn đoán

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEPDIAGNOSIS' ,Note = 'IPDTRANSLATEPDIAGNOSISANS'
Where Code = 'TRANSLATEPDIAGNOSISANS'

--Giới tính= Nam/Nữ

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGEN' ,Note = 'IPDTRANSLATEGENANS,IPDTRANSLATEGENVIANS'
Where Code = 'TRANSLATEGENANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGENVI' ,Note = 'IPDTRANSLATEGENVIANS,IPDTRANSLATEGENANS'
Where Code = 'TRANSLATEGENVIANS'
--Địa chỉ

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEADD' ,Note = 'IPDTRANSLATEADDANS,IPDTRANSLATEADDFOOTERANS'
Where Code = 'TRANSLATEADDANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEADDFOOTER' ,Note = 'IPDTRANSLATEADDFOOTERANS,IPDTRANSLATEADDANS'
Where Code = 'TRANSLATEADDFOOTERANS'

--Các thuốc chính đã dùng

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEDRUGUSED' ,Note = 'IPDTRANSLATEDRUGUSEDANS'
Where Code = 'TRANSLATEDRUGUSEDANS'

--Nghề nghiệp

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEJOB' ,Note = 'IPDTRANSLATEJOBANS'
Where Code = 'TRANSLATEJOBANS'

----- EOC
--Giới tính = Nam/Nữ
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGEN' ,Note = 'IPDTRANSLATEGENANS,IPDTRANSLATEGENVIANS,EOCTRANSLATEGENANS,EOCTRANSLATEGENVIANS'
Where Code = 'TRANSLATEGENANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGENVI' ,Note = 'IPDTRANSLATEGENVIANS,IPDTRANSLATEGENANS,EOCTRANSLATEGENVIANS,EOCTRANSLATEGENANS'
Where Code = 'TRANSLATEGENVIANS'

--Lý do khám bênh = Lý do nhập viện*

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEREASONFORVISIT' ,Note = 'EOCTRANSLATEREASONFORVISITANS,EOCTRANSLATECHIEFCOMANS'
Where Code = 'TRANSLATEREASONFORVISITANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECHIEFCOM' ,Note = 'IPDTRANSLATECHIEFCOMANS,IPDTRANSLATEREASONANS,EOCTRANSLATECHIEFCOMANS,EOCTRANSLATEREASONFORVISITANS'
Where Code = 'TRANSLATECHIEFCOMANS'

--Bệnh sử

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEHISTORY' ,Note = 'EOCTRANSLATEHISTORYANS,EOCTRANSLATEHISTORYOFPRESENTANS'
Where Code = 'TRANSLATEHISTORYANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEHISTORYOFPRESENT' ,Note = 'EOCTRANSLATEHISTORYOFPRESENTANS,EOCTRANSLATEHISTORYANS'
Where Code = 'TRANSLATEHISTORYOFPRESENTANS'


--Khám lâm sàng

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEKLS' ,Note = 'EOCTRANSLATEKLSANS'
Where Code = 'TRANSLATEKLSANS'

--Các xét nghiệm, thăm dò chính 
--= Kết quả cận lâm sàng  
--= Kết quả xét nghiệm, cận lâm sàng*
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEPRINCIPALTEST' ,Note = 'EOCTRANSLATEPRINCIPALTESTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATELABANDSUBRESULTANS'
Where Code = 'TRANSLATEPRINCIPALTESTANS'


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESUBRESULT' ,Note = 'IPDTRANSLATESUBRESULTANS,IPDTRANSLATELABANDSUBRESULTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATEPRINCIPALTESTANS,EOCTRANSLATELABANDSUBRESULTANS'
Where Code = 'TRANSLATESUBRESULTANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATELABANDSUBRESULT' ,Note = 'IPDTRANSLATELABANDSUBRESULTANS,IPDTRANSLATESUBRESULTANS,EOCTRANSLATELABANDSUBRESULTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATESUBRESULTANS'
Where Code = 'TRANSLATELABANDSUBRESULTANS'

--- Hướng điều trị = Phương pháp điều trị*


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREANTMENTPLAN' ,Note = 'IPDTRANSLATETREANTMENTPLANANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATENOTEANS,EOCTRANSLATETREANTMENTPLANANS,EOCTRANSLATETREATMENTANDPROCEDUREANS'
Where Code = 'TRANSLATETREANTMENTPLANANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREATMENTANDPROCEDURE' ,Note = 'IPDTRANSLATETREATMENTANDPROCEDUREANS,IPDTRANSLATETREATMENTANS,EOCTRANSLATETREATMENTANDPROCEDUREANS,EOCTRANSLATETREANTMENTPLANANS'
Where Code = 'TRANSLATETREATMENTANDPROCEDUREANS'


--Dặn dò = Kế hoạch điều trị và chăm sóc tiếp theo*

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATERECOMMENDATIONANDFOLLOWUP' ,Note = 'EOCTRANSLATERECOMMENDATIONANDFOLLOWUPANS,EOCTRANSLATECAREPLANANS'
Where Code = 'TRANSLATERECOMMENDATIONANDFOLLOWUPANS'

--Chuẩn đoán
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEPDIAGNOSIS' ,Note = 'IPDTRANSLATEPDIAGNOSISANS,EOCTRANSLATEPDIAGNOSISANS'
Where Code = 'TRANSLATEPDIAGNOSISANS'

--Tình trạng người bệnh lúc chuyển viện = Tình trạng người bệnh lúc chuyển tuyến
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESTATUSPATIENTTRANSFER' ,Note = 'IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS,EOCTRANSLATESTATUSPATIENTTRANSFERANS,EOCTRANSLATESATATUSREFERALANS'
Where Code = 'TRANSLATESTATUSPATIENTTRANSFERANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESATATUSREFERAL' ,Note = 'IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS,EOCTRANSLATESATATUSREFERALANS,EOCTRANSLATESTATUSPATIENTTRANSFERANS'
Where Code = 'TRANSLATESATATUSREFERALANS'



---- OPD 


--Giới tính= Nam/Nữ

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGEN' ,Note = 'IPDTRANSLATEGENANS,IPDTRANSLATEGENVIANS,OPDTRANSLATEGENANS,OPDTRANSLATEGENVIANS'
Where Code = 'TRANSLATEGENANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGENVI' ,Note = 'IPDTRANSLATEGENVIANS,IPDTRANSLATEGENANS,OPDTRANSLATEGENVIANS,OPDTRANSLATEGENANS'
Where Code = 'TRANSLATEGENVIANS'
--Địa chỉ

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEADD' ,Note = 'IPDTRANSLATEADDANS,IPDTRANSLATEADDFOOTERANS,OPDTRANSLATEADDANS,OPDTRANSLATEADDFOOTERANS'
Where Code = 'TRANSLATEADDANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEADDFOOTER' ,Note = 'IPDTRANSLATEADDFOOTERANS,IPDTRANSLATEADDANS,OPDTRANSLATEADDFOOTERANS,OPDTRANSLATEADDANS'
Where Code = 'TRANSLATEADDFOOTERANS'
---

--Lý do khám bênh = Lý do nhập viện

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEREASONFORVISIT' ,Note = 'EOCTRANSLATEREASONFORVISITANS,EOCTRANSLATECHIEFCOMANS,OPDTRANSLATEREASONFORVISITANS,OPDTRANSLATECHIEFCOMANS'
Where Code = 'TRANSLATEREASONFORVISITANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEREASONFORVISIT' ,Note = 'IPDTRANSLATECHIEFCOMANS,IPDTRANSLATEREASONANS,EOCTRANSLATECHIEFCOMANS,EOCTRANSLATEREASONFORVISITANS,OPDTRANSLATECHIEFCOMANS,OPDTRANSLATEREASONFORVISITANS'
Where Code = 'TRANSLATECHIEFCOMANS'
--Bẹnh sử
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEHISTORY' ,Note = 'EOCTRANSLATEHISTORYANS,EOCTRANSLATEHISTORYOFPRESENTANS,OPDTRANSLATEHISTORYANS,OPDTRANSLATEHISTORYOFPRESENTANS'
Where Code = 'TRANSLATEHISTORYANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEHISTORYOFPRESENT' ,Note = 'EOCTRANSLATEHISTORYOFPRESENTANS,EOCTRANSLATEHISTORYANS,OPDTRANSLATEHISTORYOFPRESENTANS,OPDTRANSLATEHISTORYANS'
Where Code = 'TRANSLATEHISTORYOFPRESENTANS'

--Khám lâm sàng
--= Dấu hiệu lâm sàng
--=thăm khám 

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEKLS' ,Note = 'EOCTRANSLATEKLSANS,OPDTRANSLATEKLSANS,OPDTRANSLATEDHLSANS,OPDTRANSLATEASSESSMENTANS'
Where Code = 'TRANSLATEKLSANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEDHLS' ,Note = 'OPDTRANSLATEDHLSANS,OPDTRANSLATEKLSANS,OPDTRANSLATEASSESSMENTANS'
Where Code = 'TRANSLATEDHLSANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEASSESSMENT' ,Note = 'OPDTRANSLATEASSESSMENTANS,OPDTRANSLATEKLSANS,OPDTRANSLATEDHLSANS'
Where Code = 'TRANSLATEASSESSMENTANS'

---
--Các xét nghiệm, thăm dò chính = Kết quả xét nghiệm, cận lâm sàng
--= kết quả cận lâm sàng

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEPRINCIPALTEST' ,Note = 'EOCTRANSLATEPRINCIPALTESTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATELABANDSUBRESULTANS,OPDTRANSLATEPRINCIPALTESTANS,OPDTRANSLATELABANDSUBRESULTANS,OPDTRANSLATESUBRESULTANS'
Where Code = 'TRANSLATEPRINCIPALTESTANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATELABANDSUBRESULT' ,Note = 'IPDTRANSLATELABANDSUBRESULTANS,IPDTRANSLATESUBRESULTANS,EOCTRANSLATELABANDSUBRESULTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATESUBRESULTANS,OPDTRANSLATELABANDSUBRESULTANS,OPDTRANSLATEPRINCIPALTESTANS,OPDTRANSLATESUBRESULTANS'
Where Code = 'TRANSLATELABANDSUBRESULTANS'


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESUBRESULT' ,Note = 'IPDTRANSLATESUBRESULTANS,IPDTRANSLATELABANDSUBRESULTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATEPRINCIPALTESTANS,EOCTRANSLATELABANDSUBRESULTANS,OPDTRANSLATESUBRESULTANS,OPDTRANSLATEPRINCIPALTESTANS,OPDTRANSLATELABANDSUBRESULTANS'
Where Code = 'TRANSLATESUBRESULTANS'


--Hướng điều trị = Phương pháp điều trị
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREANTMENTPLAN' ,Note = 'IPDTRANSLATETREANTMENTPLANANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATENOTEANS,EOCTRANSLATETREANTMENTPLANANS,EOCTRANSLATETREATMENTANDPROCEDUREANS,OPDTRANSLATETREANTMENTPLANANS,OPDTRANSLATETREATMENTANDPROCEDUREANS'
Where Code = 'TRANSLATETREANTMENTPLANANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREATMENTANDPROCEDURE' ,Note = 'IPDTRANSLATETREATMENTANDPROCEDUREANS,IPDTRANSLATETREATMENTANS,EOCTRANSLATETREATMENTANDPROCEDUREANS,EOCTRANSLATETREANTMENTPLANANS,OPDTRANSLATETREATMENTANDPROCEDUREANS,OPDTRANSLATETREANTMENTPLANANS,OPDTRANSLATESATATUSREFERALANS'
Where Code = 'TRANSLATETREATMENTANDPROCEDUREANS'


--Tình trạng người bệnh lúc chuyển viện = Tình trạng người bệnh lúc chuyển tuyến
Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESTATUSPATIENTTRANSFER' ,Note = 'IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS,EOCTRANSLATESTATUSPATIENTTRANSFERANS,EOCTRANSLATESATATUSREFERALANS,OPDTRANSLATESTATUSPATIENTTRANSFERANS,OPDTRANSLATESATATUSREFERALANS'
Where Code = 'TRANSLATESTATUSPATIENTTRANSFERANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESATATUSREFERAL' ,Note = 'IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS,EOCTRANSLATESATATUSREFERALANS,EOCTRANSLATESTATUSPATIENTTRANSFERANS,OPDTRANSLATESATATUSREFERALANS,OPDTRANSLATESTATUSPATIENTTRANSFERANS'
Where Code = 'TRANSLATESATATUSREFERALANS'

--ED --------

--Giới tính= Nam/Nữ

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGEN' ,Note = 'IPDTRANSLATEGENANS,IPDTRANSLATEGENVIANS,OPDTRANSLATEGENANS,OPDTRANSLATEGENVIANS,EDTRANSLATEGENANS,EDTRANSLATEGENVIANS'
Where Code = 'TRANSLATEGENANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEGENVI' ,Note = 'IPDTRANSLATEGENVIANS,IPDTRANSLATEGENANS,OPDTRANSLATEGENVIANS,OPDTRANSLATEGENANS,EDTRANSLATEGENVIANS,EDTRANSLATEGENANS'
Where Code = 'TRANSLATEGENVIANS'
--Địa chỉ

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEADD' ,Note = 'IPDTRANSLATEADDANS,IPDTRANSLATEADDFOOTERANS,OPDTRANSLATEADDANS,OPDTRANSLATEADDFOOTERANS,EDTRANSLATEADDANS,EDTRANSLATEADDFOOTERANS'
Where Code = 'TRANSLATEADDANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEADDFOOTER' ,Note = 'IPDTRANSLATEADDFOOTERANS,IPDTRANSLATEADDANS,OPDTRANSLATEADDFOOTERANS,OPDTRANSLATEADDANS,EDTRANSLATEADDFOOTERANS,EDTRANSLATEADDANS'
Where Code = 'TRANSLATEADDFOOTERANS'
---
--Lý do vào viện

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEREASON' ,Note = 'IPDTRANSLATEREASONANS,IPDTRANSLATECHIEFCOMANS,EDTRANSLATEREASONANS'
Where Code = 'TRANSLATEREASONANS'
---

--Qúa trình bệnh lý và diễn biến lâm sàng

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECLINEVOLU' ,Note = 'IPDTRANSLATECLINEVOLUANS,EDTRANSLATECLINEVOLUANS'
Where Code = 'TRANSLATECLINEVOLUANS'

--Kết quả cận lâm sàng = Kết quả xét nghiệm, cận lâm sàng*

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESUBRESULT' ,Note = 'IPDTRANSLATESUBRESULTANS,IPDTRANSLATELABANDSUBRESULTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATEPRINCIPALTESTANS,EOCTRANSLATELABANDSUBRESULTANS,OPDTRANSLATESUBRESULTANS,OPDTRANSLATEPRINCIPALTESTANS,OPDTRANSLATELABANDSUBRESULTANS,EDTRANSLATESUBRESULTANS,EDTRANSLATELABANDSUBRESULTANS'
Where Code = 'TRANSLATESUBRESULTANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATELABANDSUBRESULT' ,Note = 'IPDTRANSLATELABANDSUBRESULTANS,IPDTRANSLATESUBRESULTANS,EOCTRANSLATELABANDSUBRESULTANS,EOCTRANSLATESUBRESULTANS,EOCTRANSLATESUBRESULTANS,OPDTRANSLATELABANDSUBRESULTANS,OPDTRANSLATEPRINCIPALTESTANS,OPDTRANSLATESUBRESULTANS,EDTRANSLATELABANDSUBRESULTANS,EDTRANSLATESUBRESULTANS'
Where Code = 'TRANSLATELABANDSUBRESULTANS'

--Phương pháp điều trị = Điều trị

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREATMENTANDPROCEDURE' ,Note = 'IPDTRANSLATETREATMENTANDPROCEDUREANS,IPDTRANSLATETREATMENTANS,EOCTRANSLATETREATMENTANDPROCEDUREANS,EOCTRANSLATETREANTMENTPLANANS,OPDTRANSLATETREATMENTANDPROCEDUREANS,OPDTRANSLATETREANTMENTPLANANS,EDTRANSLATETREATMENTANDPROCEDUREANS,EDTRANSLATETREATMENTANS'
Where Code = 'TRANSLATETREATMENTANDPROCEDUREANS'


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREATMENT' ,Note = 'IPDTRANSLATETREATMENTANS,IPDTRANSLATETREATMENTANDPROCEDUREANS,EDTRANSLATETREATMENTANS,EDTRANSLATETREATMENTANDPROCEDUREANS'
Where Code = 'TRANSLATETREATMENTANS'


--Các thuốc chính đã dùng


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEDRUGUSED' ,Note = 'IPDTRANSLATEDRUGUSEDANS,EDTRANSLATEDRUGUSEDANS'
Where Code = 'TRANSLATEDRUGUSEDANS'

--- Tình trang bệnh nhân hiện tại = Tình trạng bệnh nhân lúc chuyển viện*
--Tình trạng người bệnh lúc chuyển tuyến
--Tình trạng thương tích lúc ra viện
--Tình trạng người bệnh lúc chuyển viện*


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECURSTATUS' ,Note = 'EDTRANSLATECURSTATUSANS,EDTRANSLATESTATUSPATIENTTRANSFER1ANS,EDTRANSLATESATATUSREFERALANS,EDTRANSLATESTATUSPATIENTTRANSFERANS'
Where Code = 'TRANSLATECURSTATUSANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESTATUSPATIENTTRANSFER1' ,Note = 'EDTRANSLATESTATUSPATIENTTRANSFER1ANS,EDTRANSLATECURSTATUSANS,EDTRANSLATESATATUSREFERALANS,EDTRANSLATESTATUSPATIENTTRANSFERANS'
Where Code = 'TRANSLATESTATUSPATIENTTRANSFER1ANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESATATUSREFERAL' ,Note = 'IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS,EOCTRANSLATESATATUSREFERALANS,EOCTRANSLATESTATUSPATIENTTRANSFERANS,OPDTRANSLATESATATUSREFERALANS,OPDTRANSLATESTATUSPATIENTTRANSFERANS,EDTRANSLATESATATUSREFERALANS,EDTRANSLATECURSTATUSANS,EDTRANSLATESTATUSPATIENTTRANSFER1ANS,EDTRANSLATESTATUSPATIENTTRANSFERANS'
Where Code = 'TRANSLATESATATUSREFERALANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESTATUSPATIENTTRANSFER' ,Note = 'IPDTRANSLATESTATUSPATIENTTRANSFERANS,IPDTRANSLATCURRENTPATIENTANS,IPDTRANSLATECONDITIONDISCHARGEANS,IPDTRANSLATESATATUSREFERALANS,IPDTRANSLATESTATUSINJURYDISCHARGEANS,EOCTRANSLATESTATUSPATIENTTRANSFERANS,EOCTRANSLATESATATUSREFERALANS,OPDTRANSLATESTATUSPATIENTTRANSFERANS,OPDTRANSLATESATATUSREFERALANS,EDTRANSLATESTATUSPATIENTTRANSFERANS,EDTRANSLATECURSTATUSANS,EDTRANSLATESTATUSPATIENTTRANSFER1ANS,TRANSLATESATATUSREFERALANS'
Where Code = 'TRANSLATESTATUSPATIENTTRANSFERANS'


--Kế hoạch điều trị và chăm sóc tiếp theo 
--= Hướng điều trị*
--=  Kế hoạch điều trị tiếp theo

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATECAREPLAN' ,Note = 'IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATENOTEANS,IPDTRANSLATETREANTMENTPLANANS,EOCTRANSLATECAREPLANANS,EOCTRANSLATERECOMMENDATIONANDFOLLOWUPANS,EDTRANSLATECAREPLANANS,EDTRANSLATETREANTMENTPLANANS,EDTRANSLATEFOLLOWUPCAREPLANANS'
Where Code = 'TRANSLATECAREPLANANS'


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETREANTMENTPLAN' ,Note = 'IPDTRANSLATETREANTMENTPLANANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATENOTEANS,EOCTRANSLATETREANTMENTPLANANS,EOCTRANSLATETREATMENTANDPROCEDUREANS,OPDTRANSLATETREANTMENTPLANANS,OPDTRANSLATETREATMENTANDPROCEDUREANS,EDTRANSLATETREANTMENTPLANANS,EDTRANSLATECAREPLANANS,EDTRANSLATEFOLLOWUPCAREPLANANS'
Where Code = 'TRANSLATETREANTMENTPLANANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEFOLLOWUPCAREPLAN' ,Note = 'IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATENOTEANS,IPDTRANSLATETREANTMENTPLANANS,EDTRANSLATEFOLLOWUPCAREPLANANS,EDTRANSLATECAREPLANANS,EDTRANSLATEFOLLOWUPCAREPLANANS'
Where Code = 'TRANSLATEFOLLOWUPCAREPLANANS'

--Lời dặn của thầy thuốc = Ghi chú*

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEDOCTORRECOMENDATION' ,Note = 'EDTRANSLATEDOCTORRECOMENDATIONANS,EDTRANSLATENOTEANS'
Where Code = 'TRANSLATEDOCTORRECOMENDATIONANS'


Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATENOTE' ,Note = 'IPDTRANSLATENOTEANS,IPDTRANSLATECAREPLANANS,IPDTRANSLATEFOLLOWUPCAREPLANANS,IPDTRANSLATETREANTMENTPLANANS,EDTRANSLATENOTEANS,EDTRANSLATEDOCTORRECOMENDATIONANS'
Where Code = 'TRANSLATENOTEANS'

--Nghề nghiệp

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEJOB' ,Note = 'IPDTRANSLATEJOBANS,EDTRANSLATEJOBANS'
Where Code = 'TRANSLATEJOBANS'

 --Dấu hiệu lâm sàng = Tình trạng thương tích lúc vào viện 
 --= Triệu chứng cấp cứu điển hình

 Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEDHLS' ,Note = 'OPDTRANSLATEDHLSANS,OPDTRANSLATEKLSANS,OPDTRANSLATEASSESSMENTANS,EDTRANSLATEDHLSANS,EDTRANSLATESTATUSADMITTEDANS,EDTRANSLATETCCCDHANS'
Where Code = 'TRANSLATEDHLSANS'

 Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATESTATUSADMITTED' ,Note = 'EDTRANSLATESTATUSADMITTEDANS,EDTRANSLATEDHLSANS,EDTRANSLATETCCCDHANS'
Where Code = 'TRANSLATESTATUSADMITTEDANS'

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATETCCCDH' ,Note = 'EDTRANSLATETCCCDHANS,EDTRANSLATEDHLSANS,EDTRANSLATESTATUSADMITTEDANS'
Where Code = 'TRANSLATETCCCDHANS'

--Chuẩn đoán

Update MasterDatas
SET Data = null ,DefaultValue = 'TRANSLATEPDIAGNOSIS' ,Note = 'IPDTRANSLATEPDIAGNOSISANS,EOCTRANSLATEPDIAGNOSISANS,EDTRANSLATEPDIAGNOSISANS'
Where Code = 'TRANSLATEPDIAGNOSISANS'


