select * from EDs

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,ED_MEDICAL REPORT_VI,EOC_TRANSFER LETTER_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKLS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,ED_MEDICAL REPORT_EN,EOC_TRANSFER LETTER_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKLS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,ED_MEDICAL REPORT_VI,EOC_TRANSFER LETTER_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKLSANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,ED_MEDICAL REPORT_EN,EOC_TRANSFER LETTER_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKLSANS'

update MasterDatas 
Set Code = 'TRANSLATEASSESSMENTANSANS'
where Code = 'TRANSLATEASSESSMENTANS'

update MasterDatas 
Set ViName = 'Clinical signs', EnName = 'Clinical signs'
where Code = 'TRANSLATEDHLS'  and Form = 'TRANSLATEEN'