

--
Update MasterDatas
set ViName = 'Clinical evolution',EnName = 'Clinical evolution'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATECLINEVOLU'

-----



Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTT'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTT'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTTANS'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTTANS'


Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKHH'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKHH'

Update MasterDatas
set Clinic =  'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKHHANS'

Update MasterDatas
set Clinic =    'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKHHANS'

----------

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCK'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCK'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCKANS'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCKANS'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCBPK'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCBPK'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCBPKANS'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCBPKANS'


------------------
Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMHH'

Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMHH'

Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMHHANS'

Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMHHANS'
------------------

Update MasterDatas
set DefaultValue = 'TRANS17'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTTANS'
Update MasterDatas
set DefaultValue = 'TRANS17'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTTANS' 

Update MasterDatas
set DefaultValue = 'TRANS18'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMANS'
Update MasterDatas
set DefaultValue = 'TRANS18'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMANS' 

Update MasterDatas
set DefaultValue = 'TRANS19'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKHHANS'
Update MasterDatas
set DefaultValue = 'TRANS19'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKHHANS' 

Update MasterDatas
set DefaultValue = 'TRANS20'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCKANS'
Update MasterDatas
set DefaultValue = 'TRANS20'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCKANS' 
-------
Update MasterDatas
set DefaultValue = 'TRANS21'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCBPKANS'
Update MasterDatas
set DefaultValue = 'TRANS21'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCBPKANS' 
-----------
Update MasterDatas
set DefaultValue = 'TRANS22'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMHHANS'
Update MasterDatas
set DefaultValue = 'TRANS22'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMHHANS' 
--

Update MasterDatas
set Clinic = 'IPD_INJURY CERTIFICATE_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATESTATUSADMITTED'

Update MasterDatas
set Clinic = 'IPD_INJURY CERTIFICATE_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATESTATUSADMITTED'

Update MasterDatas
set Clinic =  'IPD_INJURY CERTIFICATE_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATESTATUSADMITTEDANS'

Update MasterDatas
set Clinic =    'IPD_INJURY CERTIFICATE_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATESTATUSADMITTEDANS'


---------


Update MasterDatas
set Clinic = ''
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEASSESSMENT'

Update MasterDatas
set Clinic = ''
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEASSESSMENT'

Update MasterDatas
set Clinic =  ''
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEASSESSMENTANS'

Update MasterDatas
set Clinic =    ''
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEASSESSMENTANS'




Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGMDMCNCKVTT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGMDMCNCKVTT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGMDMCNCKVTTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGMDMCNCKVTTANS'
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNDCTMBP'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNDCTMBP'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNDCTMBPANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNDCTMBPANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNTDTTNND'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNTDTTNND'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNTDTTNNDANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNTDTTNNDANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNTHCVDPPVNBTCNND'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNTHCVDPPVNBTCNND'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNTHCVDPPVNBTCNNDANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNTHCVDPPVNBTCNNDANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNPVMDDC'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNPVMDDC'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNPVMDDCANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNPVMDDCANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNCNHHDTSNT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNCNHHDTSNT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNCNHHDTSNTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNCNHHDTSNTANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGSCDVDDDLN'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGSCDVDDDLN'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGSCDVDDDLNANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGSCDVDDDLNANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNGS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNGS'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNGSANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNGSANS'



Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGMDTDNTSVD'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGMDTDNTSVD'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGMDTDNTSVDANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGMDTDNTSVDANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNGTTTPA'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNGTTTPA'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNGTTTPAANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNGTTTPAANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGTTRLN'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGTTRLN'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGTTRLNANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGTTRLNANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNNTKG'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNNTKG'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNNTKGANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNNTKGANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNDVTHTB'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNDVTHTB'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNDVTHTBANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNDVTHTBANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNDCDLONBP'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNDCDLONBP'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGKNDCDLONBPANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGKNDCDLONBPANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKDD'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKDD'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKDDANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKDDANS'



Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGTC'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGTC'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGTCANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGTCANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGPTVDTT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGPTVDTT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGPTVDTTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGPTVDTTANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGPTTTTT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGPTTTTT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGPTTTTTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGPTTTTTANS'



Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTTTHGC'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTTTHGC'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTTTHGCANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTTTHGCANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGCGNMNTDTT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGCGNMNTDTT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGCGNMNTDTTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGCGNMNTDTTANS'



Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGDNMTMRGN'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGDNMTMRGN'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDGDNMTMRGNANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDGDNMTMRGNANS'



Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKLNKXST'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKLNKXST'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKLNKXSTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKLNKXSTANS'





Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATENN'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATENN'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATENNANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATENNANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATENT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATENT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATENTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATENTANS'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETTXH'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETTXH'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETTXHANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETTXHANS'



Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEHV'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEHV'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEHVANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEHVANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETCCY'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETCCY'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETCCYANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETCCYANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETCX'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETCX'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETCXANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETCXANS'


Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETCG'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETCG'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETCGANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETCGANS'




Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKNTPV'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKNTPV'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKNTPVANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKNTPVANS'



---
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETTLCT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETTLCT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETTLCTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETTLCTANS'

---
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEBHC'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEBHC'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEBHCANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEBHCANS'



Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETD'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETD'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETDANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETDANS'


--------------------------
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETG'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETG'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETGANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETGANS'


---
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETN'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETN'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETNANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETNANS'

--------
---
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETTANS'


---

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETLC'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETLC'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATETLCANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATETLCANS'


---
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEVDT'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEVDT'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEVDTANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEVDTANS'




---
Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEVDTHO'

Update MasterDatas
set Clinic = 'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEVDTHO'

Update MasterDatas
set Clinic =  'OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEVDTHOANS'

Update MasterDatas
set Clinic =    'OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEVDTHOANS'

---------
Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTT'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTT'

Update MasterDatas
set Clinic =  'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTTANS'

Update MasterDatas
set Clinic =   'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTTANS'

------------

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCK'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCK'

Update MasterDatas
set Clinic =  'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCKANS'

Update MasterDatas
set Clinic =  'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCKANS'


----

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCBPK'

Update MasterDatas
set Clinic = 'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCBPK'

Update MasterDatas
set Clinic =  'ED_REFERRAL LETTER_VI,ED_MEDICAL REPORT_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_TRANSFER LETTER_VI,ED_EMERGENCY CONFIRMATION_VI,ED_INJURY CERTIFICATE_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_MEDICAL REPORT_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKCBPKANS'

Update MasterDatas
set Clinic =  'ED_REFERRAL LETTER_EN,ED_MEDICAL REPORT_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_TRANSFER LETTER_EN,ED_EMERGENCY CONFIRMATION_EN,ED_INJURY CERTIFICATE_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_MEDICAL REPORT_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKCBPKANS'


---

Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMHH'

Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMHH'

Update MasterDatas
set Clinic =  'EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMHHANS'

Update MasterDatas
set Clinic =  'EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMHHANS'


------


------

Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMHH'

Update MasterDatas
set Clinic = 'EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMHH'

Update MasterDatas
set Clinic =  'EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI,EOC_TRANSFER LETTER_VI,OPD_REFERRAL LETTER_VI,OPD_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKTMHHANS'

Update MasterDatas
set Clinic =  'EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN,EOC_TRANSFER LETTER_EN,OPD_REFERRAL LETTER_EN,OPD_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKTMHHANS'


Update  MasterDatas 
Set EnName = 'Attention and concentration', ViName = 'Attention and concentration'
where Code = 'TRANSLATETCCY' and Form = 'TRANSLATEEN'

UPDATE  MasterDatas 
SET Code = 'TRANSLATEDGKNDVTHTB'
where Code = 'TRANSLATEDGKNDVTHTBANS' and DataType = 'Label' and Form = 'TRANSLATEEN'



UPDATE  MasterDatas 
SET Code = 'TRANSLATEDGPTTTTT'
where Code = 'TRANSLATEDGKNDVTHTBANS' and DataType = 'Label' and Form = 'TRANSLATEEN'
-------------

Update MasterDatas
set Clinic = 'IPD_TRANSFER LETTER_VI,ED_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDHLS'

Update MasterDatas
set Clinic = 'IPD_TRANSFER LETTER_EN,ED_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDHLS'

Update MasterDatas
set Clinic =  'IPD_TRANSFER LETTER_VI,ED_TRANSFER LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEDHLSANS'

Update MasterDatas
set Clinic =  'IPD_TRANSFER LETTER_EN,ED_TRANSFER LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEDHLSANS'

----------

Update MasterDatas
set Clinic = 'IPD_DISCHARGE MEDICAL REPORT_VI,IPD_MEDICAL REPORT_VI,IPD_REFERRAL LETTER_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_MEDICAL REPORT_VI,ED_REFERRAL LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATECLINEVOLU'

Update MasterDatas
set Clinic = 'IPD_DISCHARGE MEDICAL REPORT_EN,IPD_MEDICAL REPORT_EN,IPD_REFERRAL LETTER_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_MEDICAL REPORT_EN,ED_REFERRAL LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATECLINEVOLU'

Update MasterDatas
set Clinic =  'IPD_DISCHARGE MEDICAL REPORT_VI,IPD_MEDICAL REPORT_VI,IPD_REFERRAL LETTER_VI,ED_DISCHARGE MEDICAL REPORT_VI,ED_MEDICAL REPORT_VI,ED_REFERRAL LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATECLINEVOLUANS'

Update MasterDatas
set Clinic =  'IPD_DISCHARGE MEDICAL REPORT_EN,IPD_MEDICAL REPORT_EN,IPD_REFERRAL LETTER_EN,ED_DISCHARGE MEDICAL REPORT_EN,ED_MEDICAL REPORT_EN,ED_REFERRAL LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATECLINEVOLUANS'

delete MasterDatas where Code = 'TRANSLATEDGPTVDTT' and (Form = 'TRANSLATEVI' or Form = 'TRANSLATEEN' )
delete MasterDatas where Code = 'TRANSLATEDGPTVDTTANS' and (Form = 'TRANSLATEVI' or Form = 'TRANSLATEEN' )
delete MasterDatas where Code = 'TRANSLATEDGPTTTTT' and (Form = 'TRANSLATEVI' or Form = 'TRANSLATEEN' )
delete MasterDatas where Code = 'TRANSLATEDGPTTTTTANS' and (Form = 'TRANSLATEVI' or Form = 'TRANSLATEEN')

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá phát triển vận động theo tuổi',N'Đánh giá phát triển vận động theo tuổi',N'TRANSLATEDGPTVDTT',N'TRANSLATEVI',N'TRANSLATEVI',N'1',N'9',N'Label',N'',N'0',N'',N'OPD_MEDICAL REPORT_VI', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dịch tại đây',N'Dịch tại đây',N'TRANSLATEDGPTVDTTANS',N'TRANSLATEDGPTVDTT',N'TRANSLATEVI',N'2',N'10',N'Text',N'',N'0',N'',N'OPD_MEDICAL REPORT_VI', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Assessment of motor development by age',N'Assessment of motor development by age',N'TRANSLATEDGPTVDTT',N'TRANSLATEEN',N'TRANSLATEEN',N'1',N'9',N'Label',N'',N'0',N'',N'OPD_MEDICAL REPORT_EN', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Translate here',N'Translate here',N'TRANSLATEDGPTVDTTANS',N'TRANSLATEDGPTVDTT',N'TRANSLATEEN',N'2',N'10',N'Text',N'',N'0',N'',N'OPD_MEDICAL REPORT_EN', '1');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá phát triển tinh thần theo tuổi',N'Đánh giá phát triển tinh thần theo tuổi',N'TRANSLATEDGPTTTTT',N'TRANSLATEVI',N'TRANSLATEVI',N'1',N'9',N'Label',N'',N'0',N'',N'OPD_MEDICAL REPORT_VI', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dịch tại đây',N'Dịch tại đây',N'TRANSLATEDGPTTTTTANS',N'TRANSLATEDGPTTTTT',N'TRANSLATEVI',N'2',N'10',N'Text',N'',N'0',N'',N'OPD_MEDICAL REPORT_VI', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Assessment of mental development by ag',N'Assessment of mental development by age',N'TRANSLATEDGPTTTTT',N'TRANSLATEEN',N'TRANSLATEEN',N'1',N'9',N'Label',N'',N'0',N'',N'OPD_MEDICAL REPORT_EN', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Translate here',N'Translate here',N'TRANSLATEDGPTTTTTANS',N'TRANSLATEDGPTTTTT',N'TRANSLATEEN',N'2',N'10',N'Text',N'',N'0',N'',N'OPD_MEDICAL REPORT_EN', '1');



Update MasterDatas
set Clinic = 'EOC_TRANSFER LETTER_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKLS'

Update MasterDatas
set Clinic = 'EOC_TRANSFER LETTER_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKLS'

Update MasterDatas
set Clinic =  'EOC_TRANSFER LETTER_VI,EOC_MEDICAL REPORT_VI,EOC_REFERRAL LETTER_VI'
where Form = 'TRANSLATEVI' and Code = 'TRANSLATEKLSANS'

Update MasterDatas
set Clinic =  'EOC_TRANSFER LETTER_EN,EOC_MEDICAL REPORT_EN,EOC_REFERRAL LETTER_EN'
where Form = 'TRANSLATEEN' and Code = 'TRANSLATEKLSANS'