//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.EsignService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="responseReturn", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class responseReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EsignService.serviceSignFileSoap")]
    public interface serviceSignFileSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/API_ESIGN_SERVER", ReplyAction="*")]
        Clients.EsignService.API_ESIGN_SERVERResponse API_ESIGN_SERVER(Clients.EsignService.API_ESIGN_SERVERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/API_ESIGN_SERVER", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.EsignService.API_ESIGN_SERVERResponse> API_ESIGN_SERVERAsync(Clients.EsignService.API_ESIGN_SERVERRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fs_QUYTRINH_KC", ReplyAction="*")]
        Clients.EsignService.Fs_QUYTRINH_KCResponse Fs_QUYTRINH_KC(Clients.EsignService.Fs_QUYTRINH_KCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fs_QUYTRINH_KC", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.EsignService.Fs_QUYTRINH_KCResponse> Fs_QUYTRINH_KCAsync(Clients.EsignService.Fs_QUYTRINH_KCRequest request);
        
        // CODEGEN: Generating message contract since element name b_ssid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/API_ESIGN_SERVER_C", ReplyAction="*")]
        Clients.EsignService.API_ESIGN_SERVER_CResponse API_ESIGN_SERVER_C(Clients.EsignService.API_ESIGN_SERVER_CRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/API_ESIGN_SERVER_C", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.EsignService.API_ESIGN_SERVER_CResponse> API_ESIGN_SERVER_CAsync(Clients.EsignService.API_ESIGN_SERVER_CRequest request);
        
        // CODEGEN: Generating message contract since element name b_base64 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fs_DOC2PDF", ReplyAction="*")]
        Clients.EsignService.Fs_DOC2PDFResponse Fs_DOC2PDF(Clients.EsignService.Fs_DOC2PDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fs_DOC2PDF", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.EsignService.Fs_DOC2PDFResponse> Fs_DOC2PDFAsync(Clients.EsignService.Fs_DOC2PDFRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fs_TRANGTHAI", ReplyAction="*")]
        Clients.EsignService.Fs_TRANGTHAIResponse Fs_TRANGTHAI(Clients.EsignService.Fs_TRANGTHAIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fs_TRANGTHAI", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.EsignService.Fs_TRANGTHAIResponse> Fs_TRANGTHAIAsync(Clients.EsignService.Fs_TRANGTHAIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class API_ESIGN_SERVERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="API_ESIGN_SERVER", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.API_ESIGN_SERVERRequestBody Body;
        
        public API_ESIGN_SERVERRequest() {
        }
        
        public API_ESIGN_SERVERRequest(Clients.EsignService.API_ESIGN_SERVERRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class API_ESIGN_SERVERRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string b_dvi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string b_vaitro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string b_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dataBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string imageSignBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string typeSign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string locationKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public float positionX;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public float positionY;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public float withImg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public float heightImg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int pageIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string sw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string typefollow;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string followCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string link_callback;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string signobj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string tempmail_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string invisible;
        
        public API_ESIGN_SERVERRequestBody() {
        }
        
        public API_ESIGN_SERVERRequestBody(
                    string userName, 
                    string passWord, 
                    string b_dvi, 
                    string b_vaitro, 
                    string b_Id, 
                    string dataBase64, 
                    string imageSignBase64, 
                    string type, 
                    string typeSign, 
                    string locationKey, 
                    float positionX, 
                    float positionY, 
                    float withImg, 
                    float heightImg, 
                    int pageIndex, 
                    string sw, 
                    string typefollow, 
                    string email, 
                    string followCode, 
                    string link_callback, 
                    string signobj, 
                    string tempmail_code, 
                    string invisible) {
            this.userName = userName;
            this.passWord = passWord;
            this.b_dvi = b_dvi;
            this.b_vaitro = b_vaitro;
            this.b_Id = b_Id;
            this.dataBase64 = dataBase64;
            this.imageSignBase64 = imageSignBase64;
            this.type = type;
            this.typeSign = typeSign;
            this.locationKey = locationKey;
            this.positionX = positionX;
            this.positionY = positionY;
            this.withImg = withImg;
            this.heightImg = heightImg;
            this.pageIndex = pageIndex;
            this.sw = sw;
            this.typefollow = typefollow;
            this.email = email;
            this.followCode = followCode;
            this.link_callback = link_callback;
            this.signobj = signobj;
            this.tempmail_code = tempmail_code;
            this.invisible = invisible;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class API_ESIGN_SERVERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="API_ESIGN_SERVERResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.API_ESIGN_SERVERResponseBody Body;
        
        public API_ESIGN_SERVERResponse() {
        }
        
        public API_ESIGN_SERVERResponse(Clients.EsignService.API_ESIGN_SERVERResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class API_ESIGN_SERVERResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Clients.EsignService.responseReturn API_ESIGN_SERVERResult;
        
        public API_ESIGN_SERVERResponseBody() {
        }
        
        public API_ESIGN_SERVERResponseBody(Clients.EsignService.responseReturn API_ESIGN_SERVERResult) {
            this.API_ESIGN_SERVERResult = API_ESIGN_SERVERResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fs_QUYTRINH_KCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fs_QUYTRINH_KC", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.Fs_QUYTRINH_KCRequestBody Body;
        
        public Fs_QUYTRINH_KCRequest() {
        }
        
        public Fs_QUYTRINH_KCRequest(Clients.EsignService.Fs_QUYTRINH_KCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Fs_QUYTRINH_KCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string b_idvb;
        
        public Fs_QUYTRINH_KCRequestBody() {
        }
        
        public Fs_QUYTRINH_KCRequestBody(string userName, string passWord, string b_idvb) {
            this.userName = userName;
            this.passWord = passWord;
            this.b_idvb = b_idvb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fs_QUYTRINH_KCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fs_QUYTRINH_KCResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.Fs_QUYTRINH_KCResponseBody Body;
        
        public Fs_QUYTRINH_KCResponse() {
        }
        
        public Fs_QUYTRINH_KCResponse(Clients.EsignService.Fs_QUYTRINH_KCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Fs_QUYTRINH_KCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Clients.EsignService.ArrayOfAnyType Fs_QUYTRINH_KCResult;
        
        public Fs_QUYTRINH_KCResponseBody() {
        }
        
        public Fs_QUYTRINH_KCResponseBody(Clients.EsignService.ArrayOfAnyType Fs_QUYTRINH_KCResult) {
            this.Fs_QUYTRINH_KCResult = Fs_QUYTRINH_KCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class API_ESIGN_SERVER_CRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="API_ESIGN_SERVER_C", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.API_ESIGN_SERVER_CRequestBody Body;
        
        public API_ESIGN_SERVER_CRequest() {
        }
        
        public API_ESIGN_SERVER_CRequest(Clients.EsignService.API_ESIGN_SERVER_CRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class API_ESIGN_SERVER_CRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string b_ssid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string b_vaitro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string imageSignBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string invisible;
        
        public API_ESIGN_SERVER_CRequestBody() {
        }
        
        public API_ESIGN_SERVER_CRequestBody(string b_ssid, string b_vaitro, string imageSignBase64, string invisible) {
            this.b_ssid = b_ssid;
            this.b_vaitro = b_vaitro;
            this.imageSignBase64 = imageSignBase64;
            this.invisible = invisible;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class API_ESIGN_SERVER_CResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="API_ESIGN_SERVER_CResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.API_ESIGN_SERVER_CResponseBody Body;
        
        public API_ESIGN_SERVER_CResponse() {
        }
        
        public API_ESIGN_SERVER_CResponse(Clients.EsignService.API_ESIGN_SERVER_CResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class API_ESIGN_SERVER_CResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string API_ESIGN_SERVER_CResult;
        
        public API_ESIGN_SERVER_CResponseBody() {
        }
        
        public API_ESIGN_SERVER_CResponseBody(string API_ESIGN_SERVER_CResult) {
            this.API_ESIGN_SERVER_CResult = API_ESIGN_SERVER_CResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fs_DOC2PDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fs_DOC2PDF", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.Fs_DOC2PDFRequestBody Body;
        
        public Fs_DOC2PDFRequest() {
        }
        
        public Fs_DOC2PDFRequest(Clients.EsignService.Fs_DOC2PDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Fs_DOC2PDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string b_base64;
        
        public Fs_DOC2PDFRequestBody() {
        }
        
        public Fs_DOC2PDFRequestBody(string b_base64) {
            this.b_base64 = b_base64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fs_DOC2PDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fs_DOC2PDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.Fs_DOC2PDFResponseBody Body;
        
        public Fs_DOC2PDFResponse() {
        }
        
        public Fs_DOC2PDFResponse(Clients.EsignService.Fs_DOC2PDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Fs_DOC2PDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Fs_DOC2PDFResult;
        
        public Fs_DOC2PDFResponseBody() {
        }
        
        public Fs_DOC2PDFResponseBody(string Fs_DOC2PDFResult) {
            this.Fs_DOC2PDFResult = Fs_DOC2PDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fs_TRANGTHAIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fs_TRANGTHAI", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.Fs_TRANGTHAIRequestBody Body;
        
        public Fs_TRANGTHAIRequest() {
        }
        
        public Fs_TRANGTHAIRequest(Clients.EsignService.Fs_TRANGTHAIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Fs_TRANGTHAIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string b_idvb;
        
        public Fs_TRANGTHAIRequestBody() {
        }
        
        public Fs_TRANGTHAIRequestBody(string userName, string passWord, string b_idvb) {
            this.userName = userName;
            this.passWord = passWord;
            this.b_idvb = b_idvb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fs_TRANGTHAIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fs_TRANGTHAIResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.EsignService.Fs_TRANGTHAIResponseBody Body;
        
        public Fs_TRANGTHAIResponse() {
        }
        
        public Fs_TRANGTHAIResponse(Clients.EsignService.Fs_TRANGTHAIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Fs_TRANGTHAIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Fs_TRANGTHAIResult;
        
        public Fs_TRANGTHAIResponseBody() {
        }
        
        public Fs_TRANGTHAIResponseBody(string Fs_TRANGTHAIResult) {
            this.Fs_TRANGTHAIResult = Fs_TRANGTHAIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceSignFileSoapChannel : Clients.EsignService.serviceSignFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceSignFileSoapClient : System.ServiceModel.ClientBase<Clients.EsignService.serviceSignFileSoap>, Clients.EsignService.serviceSignFileSoap {
        
        public serviceSignFileSoapClient() {
        }
        
        public serviceSignFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceSignFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSignFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSignFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.EsignService.API_ESIGN_SERVERResponse Clients.EsignService.serviceSignFileSoap.API_ESIGN_SERVER(Clients.EsignService.API_ESIGN_SERVERRequest request) {
            return base.Channel.API_ESIGN_SERVER(request);
        }
        
        public Clients.EsignService.responseReturn API_ESIGN_SERVER(
                    string userName, 
                    string passWord, 
                    string b_dvi, 
                    string b_vaitro, 
                    string b_Id, 
                    string dataBase64, 
                    string imageSignBase64, 
                    string type, 
                    string typeSign, 
                    string locationKey, 
                    float positionX, 
                    float positionY, 
                    float withImg, 
                    float heightImg, 
                    int pageIndex, 
                    string sw, 
                    string typefollow, 
                    string email, 
                    string followCode, 
                    string link_callback, 
                    string signobj, 
                    string tempmail_code, 
                    string invisible) {
            Clients.EsignService.API_ESIGN_SERVERRequest inValue = new Clients.EsignService.API_ESIGN_SERVERRequest();
            inValue.Body = new Clients.EsignService.API_ESIGN_SERVERRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.b_dvi = b_dvi;
            inValue.Body.b_vaitro = b_vaitro;
            inValue.Body.b_Id = b_Id;
            inValue.Body.dataBase64 = dataBase64;
            inValue.Body.imageSignBase64 = imageSignBase64;
            inValue.Body.type = type;
            inValue.Body.typeSign = typeSign;
            inValue.Body.locationKey = locationKey;
            inValue.Body.positionX = positionX;
            inValue.Body.positionY = positionY;
            inValue.Body.withImg = withImg;
            inValue.Body.heightImg = heightImg;
            inValue.Body.pageIndex = pageIndex;
            inValue.Body.sw = sw;
            inValue.Body.typefollow = typefollow;
            inValue.Body.email = email;
            inValue.Body.followCode = followCode;
            inValue.Body.link_callback = link_callback;
            inValue.Body.signobj = signobj;
            inValue.Body.tempmail_code = tempmail_code;
            inValue.Body.invisible = invisible;
            Clients.EsignService.API_ESIGN_SERVERResponse retVal = ((Clients.EsignService.serviceSignFileSoap)(this)).API_ESIGN_SERVER(inValue);
            return retVal.Body.API_ESIGN_SERVERResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.EsignService.API_ESIGN_SERVERResponse> Clients.EsignService.serviceSignFileSoap.API_ESIGN_SERVERAsync(Clients.EsignService.API_ESIGN_SERVERRequest request) {
            return base.Channel.API_ESIGN_SERVERAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.EsignService.API_ESIGN_SERVERResponse> API_ESIGN_SERVERAsync(
                    string userName, 
                    string passWord, 
                    string b_dvi, 
                    string b_vaitro, 
                    string b_Id, 
                    string dataBase64, 
                    string imageSignBase64, 
                    string type, 
                    string typeSign, 
                    string locationKey, 
                    float positionX, 
                    float positionY, 
                    float withImg, 
                    float heightImg, 
                    int pageIndex, 
                    string sw, 
                    string typefollow, 
                    string email, 
                    string followCode, 
                    string link_callback, 
                    string signobj, 
                    string tempmail_code, 
                    string invisible) {
            Clients.EsignService.API_ESIGN_SERVERRequest inValue = new Clients.EsignService.API_ESIGN_SERVERRequest();
            inValue.Body = new Clients.EsignService.API_ESIGN_SERVERRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.b_dvi = b_dvi;
            inValue.Body.b_vaitro = b_vaitro;
            inValue.Body.b_Id = b_Id;
            inValue.Body.dataBase64 = dataBase64;
            inValue.Body.imageSignBase64 = imageSignBase64;
            inValue.Body.type = type;
            inValue.Body.typeSign = typeSign;
            inValue.Body.locationKey = locationKey;
            inValue.Body.positionX = positionX;
            inValue.Body.positionY = positionY;
            inValue.Body.withImg = withImg;
            inValue.Body.heightImg = heightImg;
            inValue.Body.pageIndex = pageIndex;
            inValue.Body.sw = sw;
            inValue.Body.typefollow = typefollow;
            inValue.Body.email = email;
            inValue.Body.followCode = followCode;
            inValue.Body.link_callback = link_callback;
            inValue.Body.signobj = signobj;
            inValue.Body.tempmail_code = tempmail_code;
            inValue.Body.invisible = invisible;
            return ((Clients.EsignService.serviceSignFileSoap)(this)).API_ESIGN_SERVERAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.EsignService.Fs_QUYTRINH_KCResponse Clients.EsignService.serviceSignFileSoap.Fs_QUYTRINH_KC(Clients.EsignService.Fs_QUYTRINH_KCRequest request) {
            return base.Channel.Fs_QUYTRINH_KC(request);
        }
        
        public Clients.EsignService.ArrayOfAnyType Fs_QUYTRINH_KC(string userName, string passWord, string b_idvb) {
            Clients.EsignService.Fs_QUYTRINH_KCRequest inValue = new Clients.EsignService.Fs_QUYTRINH_KCRequest();
            inValue.Body = new Clients.EsignService.Fs_QUYTRINH_KCRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.b_idvb = b_idvb;
            Clients.EsignService.Fs_QUYTRINH_KCResponse retVal = ((Clients.EsignService.serviceSignFileSoap)(this)).Fs_QUYTRINH_KC(inValue);
            return retVal.Body.Fs_QUYTRINH_KCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.EsignService.Fs_QUYTRINH_KCResponse> Clients.EsignService.serviceSignFileSoap.Fs_QUYTRINH_KCAsync(Clients.EsignService.Fs_QUYTRINH_KCRequest request) {
            return base.Channel.Fs_QUYTRINH_KCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.EsignService.Fs_QUYTRINH_KCResponse> Fs_QUYTRINH_KCAsync(string userName, string passWord, string b_idvb) {
            Clients.EsignService.Fs_QUYTRINH_KCRequest inValue = new Clients.EsignService.Fs_QUYTRINH_KCRequest();
            inValue.Body = new Clients.EsignService.Fs_QUYTRINH_KCRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.b_idvb = b_idvb;
            return ((Clients.EsignService.serviceSignFileSoap)(this)).Fs_QUYTRINH_KCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.EsignService.API_ESIGN_SERVER_CResponse Clients.EsignService.serviceSignFileSoap.API_ESIGN_SERVER_C(Clients.EsignService.API_ESIGN_SERVER_CRequest request) {
            return base.Channel.API_ESIGN_SERVER_C(request);
        }
        
        public string API_ESIGN_SERVER_C(string b_ssid, string b_vaitro, string imageSignBase64, string invisible) {
            Clients.EsignService.API_ESIGN_SERVER_CRequest inValue = new Clients.EsignService.API_ESIGN_SERVER_CRequest();
            inValue.Body = new Clients.EsignService.API_ESIGN_SERVER_CRequestBody();
            inValue.Body.b_ssid = b_ssid;
            inValue.Body.b_vaitro = b_vaitro;
            inValue.Body.imageSignBase64 = imageSignBase64;
            inValue.Body.invisible = invisible;
            Clients.EsignService.API_ESIGN_SERVER_CResponse retVal = ((Clients.EsignService.serviceSignFileSoap)(this)).API_ESIGN_SERVER_C(inValue);
            return retVal.Body.API_ESIGN_SERVER_CResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.EsignService.API_ESIGN_SERVER_CResponse> Clients.EsignService.serviceSignFileSoap.API_ESIGN_SERVER_CAsync(Clients.EsignService.API_ESIGN_SERVER_CRequest request) {
            return base.Channel.API_ESIGN_SERVER_CAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.EsignService.API_ESIGN_SERVER_CResponse> API_ESIGN_SERVER_CAsync(string b_ssid, string b_vaitro, string imageSignBase64, string invisible) {
            Clients.EsignService.API_ESIGN_SERVER_CRequest inValue = new Clients.EsignService.API_ESIGN_SERVER_CRequest();
            inValue.Body = new Clients.EsignService.API_ESIGN_SERVER_CRequestBody();
            inValue.Body.b_ssid = b_ssid;
            inValue.Body.b_vaitro = b_vaitro;
            inValue.Body.imageSignBase64 = imageSignBase64;
            inValue.Body.invisible = invisible;
            return ((Clients.EsignService.serviceSignFileSoap)(this)).API_ESIGN_SERVER_CAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.EsignService.Fs_DOC2PDFResponse Clients.EsignService.serviceSignFileSoap.Fs_DOC2PDF(Clients.EsignService.Fs_DOC2PDFRequest request) {
            return base.Channel.Fs_DOC2PDF(request);
        }
        
        public string Fs_DOC2PDF(string b_base64) {
            Clients.EsignService.Fs_DOC2PDFRequest inValue = new Clients.EsignService.Fs_DOC2PDFRequest();
            inValue.Body = new Clients.EsignService.Fs_DOC2PDFRequestBody();
            inValue.Body.b_base64 = b_base64;
            Clients.EsignService.Fs_DOC2PDFResponse retVal = ((Clients.EsignService.serviceSignFileSoap)(this)).Fs_DOC2PDF(inValue);
            return retVal.Body.Fs_DOC2PDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.EsignService.Fs_DOC2PDFResponse> Clients.EsignService.serviceSignFileSoap.Fs_DOC2PDFAsync(Clients.EsignService.Fs_DOC2PDFRequest request) {
            return base.Channel.Fs_DOC2PDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.EsignService.Fs_DOC2PDFResponse> Fs_DOC2PDFAsync(string b_base64) {
            Clients.EsignService.Fs_DOC2PDFRequest inValue = new Clients.EsignService.Fs_DOC2PDFRequest();
            inValue.Body = new Clients.EsignService.Fs_DOC2PDFRequestBody();
            inValue.Body.b_base64 = b_base64;
            return ((Clients.EsignService.serviceSignFileSoap)(this)).Fs_DOC2PDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.EsignService.Fs_TRANGTHAIResponse Clients.EsignService.serviceSignFileSoap.Fs_TRANGTHAI(Clients.EsignService.Fs_TRANGTHAIRequest request) {
            return base.Channel.Fs_TRANGTHAI(request);
        }
        
        public string Fs_TRANGTHAI(string userName, string passWord, string b_idvb) {
            Clients.EsignService.Fs_TRANGTHAIRequest inValue = new Clients.EsignService.Fs_TRANGTHAIRequest();
            inValue.Body = new Clients.EsignService.Fs_TRANGTHAIRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.b_idvb = b_idvb;
            Clients.EsignService.Fs_TRANGTHAIResponse retVal = ((Clients.EsignService.serviceSignFileSoap)(this)).Fs_TRANGTHAI(inValue);
            return retVal.Body.Fs_TRANGTHAIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.EsignService.Fs_TRANGTHAIResponse> Clients.EsignService.serviceSignFileSoap.Fs_TRANGTHAIAsync(Clients.EsignService.Fs_TRANGTHAIRequest request) {
            return base.Channel.Fs_TRANGTHAIAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.EsignService.Fs_TRANGTHAIResponse> Fs_TRANGTHAIAsync(string userName, string passWord, string b_idvb) {
            Clients.EsignService.Fs_TRANGTHAIRequest inValue = new Clients.EsignService.Fs_TRANGTHAIRequest();
            inValue.Body = new Clients.EsignService.Fs_TRANGTHAIRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.b_idvb = b_idvb;
            return ((Clients.EsignService.serviceSignFileSoap)(this)).Fs_TRANGTHAIAsync(inValue);
        }
    }
}
