Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xác nhận chuẩn bị công cụ dụng cụ để tháo/ghép trước phẫu thuật đầy đủ và phù hợp',N'Confirm that the preparation of instruments for removal/implantation is complete and appropriate',N'EDJCFAOSXNCBCC',N'EDJCFAOS',N'EDJCFAOS',N'1',N'592',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xác nhận chuẩn bị công cụ dụng cụ để tháo/ghép trước phẫu thuật đầy đủ và phù hợp',N'Confirm that the preparation of instruments for removal/implantation is complete and appropriate',N'EDJCFAOSXNCBCCCD1',N'EDJCFAOSXNCBCC',N'EDJCFAOS',N'2',N'593',N'Checkbox',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thành viên trong một gia đình đã có biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 đã biết, bao gồm các biến thể được tìm thấy trong thử nghiệm nghiên cứu.',N'Thành viên trong một gia đình đã có biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 đã biết, bao gồm các biến thể được tìm thấy trong thử nghiệm nghiên cứu.',N'OPDGENBRCA1',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'1',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thành viên trong một gia đình đã có biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 đã biết, bao gồm các biến thể được tìm thấy trong thử nghiệm nghiên cứu.',N'Thành viên trong một gia đình đã có biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 đã biết, bao gồm các biến thể được tìm thấy trong thử nghiệm nghiên cứu.',N'OPDGENBRCA2',N'OPDGENBRCA1',N'A03_119_201119_V',N'2',N'2',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử đã mắc ung thư vú + một hoặc một số các tiêu chí sau đây:',N'Tiền sử đã mắc ung thư vú + một hoặc một số các tiêu chí sau đây:',N'OPDGENBRCA3',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'3',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử đã mắc ung thư vú + một hoặc một số các tiêu chí sau đây: ',N'Tiền sử đã mắc ung thư vú + một hoặc một số các tiêu chí sau đây: ',N'OPDGENBRCA4',N'OPDGENBRCA3',N'A03_119_201119_V',N'2',N'4',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Được chẩn đoán ≤ 45 tuổi',N'Được chẩn đoán ≤ 45 tuổi',N'OPDGENBRCA5',N'OPDGENBRCA3',N'A03_119_201119_V',N'2',N'5',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán 46-50 tuổi với: ',N'Chẩn đoán 46-50 tuổi với: ',N'OPDGENBRCA6',N'OPDGENBRCA3',N'A03_119_201119_V',N'2',N'6',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán 46-50 tuổi với: ',N'Chẩn đoán 46-50 tuổi với: ',N'OPDGENBRCA7',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'7',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có thêm một ung thư vú nguyên phát ở mọi lứa tuổi',N'Có thêm một ung thư vú nguyên phát ở mọi lứa tuổi',N'OPDGENBRCA8',N'OPDGENBRCA7',N'A03_119_201119_V',N'2',N'8',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư vú ở mọi lứa tuổi',N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư vú ở mọi lứa tuổi',N'OPDGENBRCA9',N'OPDGENBRCA7',N'A03_119_201119_V',N'2',N'9',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư tuyến tiền liệt mức độ cao (điểm Gleason ≥7)',N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư tuyến tiền liệt mức độ cao (điểm Gleason ≥7)',N'OPDGENBRCA10',N'OPDGENBRCA7',N'A03_119_201119_V',N'2',N'10',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có tiền sử gia đình không rõ hoặc hạn chế',N'Có tiền sử gia đình không rõ hoặc hạn chế',N'OPDGENBRCA11',N'OPDGENBRCA7',N'A03_119_201119_V',N'2',N'11',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Được chẩn đoán ≤ 60 tuổi với:',N'Được chẩn đoán ≤ 60 tuổi với:',N'OPDGENBRCA12',N'OPDGENBRCA3',N'A03_119_201119_V',N'2',N'12',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Được chẩn đoán ≤ 60 tuổi với:',N'Được chẩn đoán ≤ 60 tuổi với:',N'OPDGENBRCA13',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'13',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ung thư vú với bộ ba âm tính (ER, PR và HER2 âm tính)',N'Ung thư vú với bộ ba âm tính (ER, PR và HER2 âm tính)',N'OPDGENBRCA14',N'OPDGENBRCA13',N'A03_119_201119_V',N'2',N'14',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Được chẩn đoán ở mọi lứa tuổi với: ',N'Được chẩn đoán ở mọi lứa tuổi với: ',N'OPDGENBRCA15',N'OPDGENBRCA3',N'A03_119_201119_V',N'2',N'15',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Được chẩn đoán ở mọi lứa tuổi với: ',N'Được chẩn đoán ở mọi lứa tuổi với: ',N'OPDGENBRCA16',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'16',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 với:',N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 với:',N'OPDGENBRCA17',N'OPDGENBRCA16',N'A03_119_201119_V',N'2',N'17',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 với:',N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 với:',N'OPDGENBRCA18',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'18',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Được chẩn đoán ung thư vú ≤ 50 tuổi; hoặc',N'Được chẩn đoán ung thư vú ≤ 50 tuổi; hoặc',N'OPDGENBRCA19',N'OPDGENBRCA18',N'A03_119_201119_V',N'2',N'19',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ung thư biểu mô buồng trứng; hoặc',N'Ung thư biểu mô buồng trứng; hoặc',N'OPDGENBRCA20',N'OPDGENBRCA18',N'A03_119_201119_V',N'2',N'20',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ung thư vú nam; hoặc',N'Ung thư vú nam; hoặc',N'OPDGENBRCA21',N'OPDGENBRCA18',N'A03_119_201119_V',N'2',N'21',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ung thư tuyến tiền liệt di căn; hoặc',N'Ung thư tuyến tiền liệt di căn; hoặc',N'OPDGENBRCA22',N'OPDGENBRCA18',N'A03_119_201119_V',N'2',N'22',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ung thư tuyến tụy',N'Ung thư tuyến tụy',N'OPDGENBRCA23',N'OPDGENBRCA18',N'A03_119_201119_V',N'2',N'23',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 2 chẩn đoán bổ sung về ung thư vú ở mọi lứa tuổi ở bệnh nhân và / hoặc ở người có quan hệ huyết thống mức 1,2 & 3',N'≥ 2 chẩn đoán bổ sung về ung thư vú ở mọi lứa tuổi ở bệnh nhân và / hoặc ở người có quan hệ huyết thống mức 1,2 & 3',N'OPDGENBRCA24',N'OPDGENBRCA16',N'A03_119_201119_V',N'2',N'24',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tổ tiên là người Do Thái Ashkenazi',N'Tổ tiên là người Do Thái Ashkenazi',N'OPDGENBRCA25',N'OPDGENBRCA16',N'A03_119_201119_V',N'2',N'25',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư biểu mô buồng trứng',N'Tiền sử mắc ung thư biểu mô buồng trứng',N'OPDGENBRCA26',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'26',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư biểu mô buồng trứng',N'Tiền sử mắc ung thư biểu mô buồng trứng',N'OPDGENBRCA27',N'OPDGENBRCA26',N'A03_119_201119_V',N'2',N'27',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người nam có tiền sử mắc ung thư vú',N'Người nam có tiền sử mắc ung thư vú',N'OPDGENBRCA28',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'28',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người nam có tiền sử mắc ung thư vú',N'Người nam có tiền sử mắc ung thư vú',N'OPDGENBRCA29',N'OPDGENBRCA28',N'A03_119_201119_V',N'2',N'29',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư tuyến tụy',N'Tiền sử mắc ung thư tuyến tụy',N'OPDGENBRCA30',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'30',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư tuyến tụy',N'Tiền sử mắc ung thư tuyến tụy',N'OPDGENBRCA31',N'OPDGENBRCA30',N'A03_119_201119_V',N'2',N'31',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư tuyến tiền liệt di căn',N'Tiền sử mắc ung thư tuyến tiền liệt di căn',N'OPDGENBRCA32',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'32',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư tuyến tiền liệt di căn',N'Tiền sử mắc ung thư tuyến tiền liệt di căn',N'OPDGENBRCA33',N'OPDGENBRCA32',N'A03_119_201119_V',N'2',N'33',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư tuyến tiền liệt mức độ cao (điểm Gleason ≥7) ở mọi lứa tuổi với',N'Tiền sử mắc ung thư tuyến tiền liệt mức độ cao (điểm Gleason ≥7) ở mọi lứa tuổi với',N'OPDGENBRCA34',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'34',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử mắc ung thư tuyến tiền liệt mức độ cao (điểm Gleason ≥7) ở mọi lứa tuổi với',N'Tiền sử mắc ung thư tuyến tiền liệt mức độ cao (điểm Gleason ≥7) ở mọi lứa tuổi với',N'OPDGENBRCA35',N'OPDGENBRCA34',N'A03_119_201119_V',N'2',N'35',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư biểu mô buồng trứng, ung thư tuyến tụy hoặc ung thư tuyến tiền liệt di căn ở mọi lứa tuổi hoặc ung thư vú < 50 tuổi; hoặc',N'≥ 1 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư biểu mô buồng trứng, ung thư tuyến tụy hoặc ung thư tuyến tiền liệt di căn ở mọi lứa tuổi hoặc ung thư vú < 50 tuổi; hoặc',N'OPDGENBRCA36',N'OPDGENBRCA34',N'A03_119_201119_V',N'2',N'36',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'≥ 2 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư vú, hoặc ung thư tuyến tiền liệt (bất kỳ cấp độ nào) ở mọi lứa tuổi; hoặc',N'≥ 2 người có quan hệ huyết thống mức 1,2 & 3 mắc ung thư vú, hoặc ung thư tuyến tiền liệt (bất kỳ cấp độ nào) ở mọi lứa tuổi; hoặc',N'OPDGENBRCA37',N'OPDGENBRCA34',N'A03_119_201119_V',N'2',N'37',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tổ tiên là người Do Thái Ashkenazi',N'Tổ tiên là người Do Thái Ashkenazi',N'OPDGENBRCA38',N'OPDGENBRCA34',N'A03_119_201119_V',N'2',N'38',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 được phát hiện ở khối u trên bất kỳ loại khối u nào trong trường hợp không có phân tích biến thể gây bệnh / có khả năng gây bệnh ở tế bào dòng sinh dục (germline)',N'Biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 được phát hiện ở khối u trên bất kỳ loại khối u nào trong trường hợp không có phân tích biến thể gây bệnh / có khả năng gây bệnh ở tế bào dòng sinh dục (germline)',N'OPDGENBRCA39',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'39',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 được phát hiện ở khối u trên bất kỳ loại khối u nào trong trường hợp không có phân tích biến thể gây bệnh / có khả năng gây bệnh ở tế bào dòng sinh dục (germline)',N'Biến thể gây bệnh/có khả năng gây bệnh của gen BRCA1/2 được phát hiện ở khối u trên bất kỳ loại khối u nào trong trường hợp không có phân tích biến thể gây bệnh / có khả năng gây bệnh ở tế bào dòng sinh dục (germline)',N'OPDGENBRCA40',N'OPDGENBRCA39',N'A03_119_201119_V',N'2',N'40',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bất kể tiền sử gia đình, một số người mắc bệnh ung thư liên quan đến gen BRCA có thể được hưởng lợi từ xét nghiệm di truyền để xác định đủ điều kiện điều trị theo mục tiêu (targeted treatment)',N'Bất kể tiền sử gia đình, một số người mắc bệnh ung thư liên quan đến gen BRCA có thể được hưởng lợi từ xét nghiệm di truyền để xác định đủ điều kiện điều trị theo mục tiêu (targeted treatment)',N'OPDGENBRCA41',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'41',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bất kể tiền sử gia đình, một số người mắc bệnh ung thư liên quan đến gen BRCA có thể được hưởng lợi từ xét nghiệm di truyền để xác định đủ điều kiện điều trị theo mục tiêu (targeted treatment)',N'Bất kể tiền sử gia đình, một số người mắc bệnh ung thư liên quan đến gen BRCA có thể được hưởng lợi từ xét nghiệm di truyền để xác định đủ điều kiện điều trị theo mục tiêu (targeted treatment)',N'OPDGENBRCA42',N'OPDGENBRCA41',N'A03_119_201119_V',N'2',N'42',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Một cá nhân không đáp ứng các tiêu chí khác nhưng có ≥1 người có quan hệ huyết thống cấp một hoặc cấp hai đáp ứng bất kỳ tiêu chí nào ở trên. (Trong trường hợp này nên trao đổi về những hạn chế đáng kể trong việc diễn giải kết quả xét nghiệm di truyền ở người không bị bệnh)',N'Một cá nhân không đáp ứng các tiêu chí khác nhưng có ≥1 người có quan hệ huyết thống cấp một hoặc cấp hai đáp ứng bất kỳ tiêu chí nào ở trên. (Trong trường hợp này nên trao đổi về những hạn chế đáng kể trong việc diễn giải kết quả xét nghiệm di truyền ở người không bị bệnh)',N'OPDGENBRCA43',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'43',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Một cá nhân không đáp ứng các tiêu chí khác nhưng có ≥1 người có quan hệ huyết thống cấp một hoặc cấp hai đáp ứng bất kỳ tiêu chí nào ở trên. (Trong trường hợp này nên trao đổi về những hạn chế đáng kể trong việc diễn giải kết quả xét nghiệm di truyền ở người không bị bệnh)',N'Một cá nhân không đáp ứng các tiêu chí khác nhưng có ≥1 người có quan hệ huyết thống cấp một hoặc cấp hai đáp ứng bất kỳ tiêu chí nào ở trên. (Trong trường hợp này nên trao đổi về những hạn chế đáng kể trong việc diễn giải kết quả xét nghiệm di truyền ở người không bị bệnh)',N'OPDGENBRCA44',N'OPDGENBRCA43',N'A03_119_201119_V',N'2',N'44',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh nhân có tiền sử cá nhân hoặc gia đình gợi ý về một hội chứng ung thư di truyền có thể do nhiều hơn một gen chi phối',N'Bệnh nhân có tiền sử cá nhân hoặc gia đình gợi ý về một hội chứng ung thư di truyền có thể do nhiều hơn một gen chi phối',N'OPDGENBRCA45',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'45',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh nhân có tiền sử cá nhân hoặc gia đình gợi ý về một hội chứng ung thư di truyền có thể do nhiều hơn một gen chi phối',N'Bệnh nhân có tiền sử cá nhân hoặc gia đình gợi ý về một hội chứng ung thư di truyền có thể do nhiều hơn một gen chi phối',N'OPDGENBRCA46',N'OPDGENBRCA45',N'A03_119_201119_V',N'2',N'46',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người đã có xét nghiệm âm tính (hoặc không xác định được) đối với một hội chứng liên quan đến đột biến đơn gen, nhưng tiền sử cá nhân hoặc gia đình vẫn gợi ý về khả năng có vai trò của yếu tố di truyền',N'Người đã có xét nghiệm âm tính (hoặc không xác định được) đối với một hội chứng liên quan đến đột biến đơn gen, nhưng tiền sử cá nhân hoặc gia đình vẫn gợi ý về khả năng có vai trò của yếu tố di truyền',N'OPDGENBRCA47',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'47',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Người đã có xét nghiệm âm tính (hoặc không xác định được) đối với một hội chứng liên quan đến đột biến đơn gen, nhưng tiền sử cá nhân hoặc gia đình vẫn gợi ý về khả năng có vai trò của yếu tố di truyền',N'Người đã có xét nghiệm âm tính (hoặc không xác định được) đối với một hội chứng liên quan đến đột biến đơn gen, nhưng tiền sử cá nhân hoặc gia đình vẫn gợi ý về khả năng có vai trò của yếu tố di truyền',N'OPDGENBRCA48',N'OPDGENBRCA47',N'A03_119_201119_V',N'2',N'48',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'KHÔNG ĐỦ TIÊU CHUẨN',N'KHÔNG ĐỦ TIÊU CHUẨN',N'OPDGENBRCA49',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'49',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'KHÔNG ĐỦ TIÊU CHUẨN',N'KHÔNG ĐỦ TIÊU CHUẨN',N'OPDGENBRCA50',N'OPDGENBRCA49',N'A03_119_201119_V',N'2',N'50',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐỦ TIÊU CHUẨN',N'ĐỦ TIÊU CHUẨN',N'OPDGENBRCA51',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'51',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐỦ TIÊU CHUẨN',N'ĐỦ TIÊU CHUẨN',N'OPDGENBRCA52',N'OPDGENBRCA51',N'A03_119_201119_V',N'2',N'52',N'Checkbox',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày đánh giá',N'Ngày đánh giá',N'OPDGENBRCA53',N'OPDGENBRCA',N'A03_119_201119_V',N'1',N'53',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày đánh giá',N'Ngày đánh giá',N'OPDGENBRCA54',N'OPDGENBRCA53',N'A03_119_201119_V',N'2',N'54',N'Text',N'',N'',N'',N'', '1');



--haulv
delete from MasterDatas where Form = 'PFEF' and [Order] >= 7 and [Order] <= 9 and [Group] = 'PFEFEN0'

delete from MasterDatas where Clinic = 'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH'

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả phẫu thuật, thủ thuật',N'Results of surgery and procedures',N'PFEFEN0ROA',N'PFEFEN0',N'PFEF',N'2',N'7',N'Select',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tập vận động PHCN',N'Rehabilitation',N'PFEFEN0REH',N'PFEFEN0',N'PFEF',N'2',N'8',N'Select',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tư vấn trước ra viện',N'Pre-discharge counselling',N'PFEFEN0PDC',N'PFEFEN0',N'PFEF',N'2',N'9',N'Select',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Others',N'PFEFEN0OTH',N'PFEFEN0',N'PFEF',N'2',N'10',N'Select',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thời điểm GDSK',N'Time of education',N'PFEFTOE',N'PFEF',N'PFEF',N'1',N'9',N'',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày đầu',N'First day',N'PFEFTOEFD0',N'PFEFTOE',N'PFEF',N'2',N'1',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Sau mổ',N'After surgery',N'PFEFTOEAS0',N'PFEFTOE',N'PFEF',N'2',N'2',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Others',N'PFEFTOEOTH',N'PFEFTOE',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mô tả',N'Others (please specify)',N'PFEFTOEANS',N'PFEFTOE',N'PFEF',N'2',N'4',N'Text',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Yêu cầu của người bệnh/ thân nhân về phương pháp tư vấn',N'Preferred counseling method',N'PFEFPCM',N'PFEF',N'PFEF',N'1',N'10',N'',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Lời nói',N'Verbal',N'PFEFPCMVER',N'PFEFPCM',N'PFEF',N'2',N'1',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tờ rơi',N'Written material(s)',N'PFEFPCMWM0',N'PFEFPCM',N'PFEF',N'2',N'2',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tư liệu hình ảnh',N'Audio visual',N'PFEFPCMAV0',N'PFEFPCM',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thực hành',N'Demonstration',N'PFEFPCMDEM',N'PFEFPCM',N'PFEF',N'2',N'4',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hình thức khác',N'Others (Specify)',N'PFEFPCMOTH',N'PFEFPCM',N'PFEF',N'2',N'5',N'Radio',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mô tả',N'Others (Specify)',N'PFEFPCMANS',N'PFEFPCM',N'PFEF',N'2',N'6',N'Text',N'',N'',N'',N'PFEFEN0PM0,PFEFEN0MU0,PFEFEN0CP0,PFEFEN0NC0,PFEFEN0HHI,PFEFEN0ROM,PFEFEN0ROA,PFEFEN0REH,PFEFEN0PDC,PFEFEN0OTH', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Những phát hiện trong thủ thuật, phẫu thuật',N'Procedural, surgical findings',N'PFEFPSF',N'PFEF',N'PFEF',N'1',N'47',N'Label',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Những phát hiện trong thủ thuật, phẫu thuật',N'Procedural, surgical findings',N'PFEFPSF0',N'PFEFPSF',N'PFEF',N'2',N'1',N'Checkbox',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'NU',N'NU',N'PFEFPSFNU',N'PFEFPSF',N'PFEF',N'2',N'2',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'U',N'U',N'PFEFPSFU',N'PFEFPSF',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'P',N'P',N'PFEFPSFP',N'PFEFPSF',N'PFEF',N'2',N'4',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phương thức xử trí, điều trị',N'Treatment',N'PFEFTTT',N'PFEF',N'PFEF',N'1',N'48',N'Label',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phương thức xử trí, điều trị',N'Treatment',N'PFEFTTT0',N'PFEFTTT',N'PFEF',N'2',N'1',N'Checkbox',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'NU',N'NU',N'PFEFTTTNU',N'PFEFTTT',N'PFEF',N'2',N'2',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'U',N'U',N'PFEFTTTU',N'PFEFTTT',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'P',N'P',N'PFEFTTTP',N'PFEFTTT',N'PFEF',N'2',N'4',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các biến chứng nếu có',N'Complications if any',N'PFEFCIA',N'PFEF',N'PFEF',N'1',N'49',N'Label',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các biến chứng nếu có',N'Complications if any',N'PFEFCIA0',N'PFEFCIA',N'PFEF',N'2',N'1',N'Checkbox',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'NU',N'NU',N'PFEFCIANU',N'PFEFCIA',N'PFEF',N'2',N'2',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'U',N'U',N'PFEFCIAU',N'PFEFCIA',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'P',N'P',N'PFEFCIAP',N'PFEFCIA',N'PFEF',N'2',N'4',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các sự cố không mong muốn nếu có',N'Unexpected events if any',N'PFEFUEIA',N'PFEF',N'PFEF',N'1',N'50',N'Label',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các sự cố không mong muốn nếu có',N'Unexpected events if any',N'PFEFUEIA0',N'PFEFUEIA',N'PFEF',N'2',N'1',N'Checkbox',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'NU',N'NU',N'PFEFUEIANU',N'PFEFUEIA',N'PFEF',N'2',N'2',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'U',N'U',N'PFEFUEIAU',N'PFEFUEIA',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'P',N'P',N'PFEFUEIAP',N'PFEFUEIA',N'PFEF',N'2',N'4',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kế hoạch chăm sóc và lưu chuyển người bệnh',N'Plan and transition of care',N'PFEFPATOA',N'PFEF',N'PFEF',N'1',N'51',N'Label',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kế hoạch chăm sóc và lưu chuyển người bệnh',N'Plan and transition of care',N'PFEFPATOA0',N'PFEFPATOA',N'PFEF',N'2',N'1',N'Checkbox',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'NU',N'NU',N'PFEFPATOANU',N'PFEFPATOA',N'PFEF',N'2',N'2',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'U',N'U',N'PFEFPATOAU',N'PFEFPATOA',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'P',N'P',N'PFEFPATOAP',N'PFEFPATOA',N'PFEF',N'2',N'4',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Others',N'PFEFROSAPO',N'PFEF',N'PFEF',N'1',N'52',N'Label',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Others',N'PFEFROSAPOCHK',N'PFEFROSAPO',N'PFEF',N'2',N'1',N'Checkbox',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác (mô tả)',N'Others (please specify)',N'PFEFROSAPO0',N'PFEFROSAPO',N'PFEF',N'2',N'2',N'Text',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'NU',N'NU',N'PFEFROSAPONU',N'PFEFROSAPO',N'PFEF',N'2',N'3',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'U',N'U',N'PFEFROSAPOU',N'PFEFROSAPO',N'PFEF',N'2',N'4',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'P',N'P',N'PFEFROSAPOP',N'PFEFROSAPO',N'PFEF',N'2',N'5',N'Radio',N'',N'',N'',N'PFEFEN0ROA', '2');



Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thông tin tiêm vắc xin và thông tin tư vấn',N'Vaccination and consulting information (if any)',N'IPDIAATSDTTTTVX',N'IPDMEDHIS',N'A03_120_120421_VE',N'1',N'1115',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thông tin tiêm vắc xin và thông tin tư vấn',N'Vaccination and consulting information (if any)',N'IPDIAATSDTTTTVXCD1',N'IPDIAATSDTTTTVX',N'A03_120_120421_VE',N'2',N'1116',N'Text',N'',N'0',N'',N'', '');




UPDATE MasterDatas SET EnName = N'Summary of patient’s condition' WHERE Code = 'EDJCFAOSSOP'
UPDATE MasterDatas SET EnName = N'Coagulation tests' WHERE Code = 'EDJCFAOSTOC'
UPDATE MasterDatas SET ViName = N'Dự trù máu', EnName = N'Order for potential transfusion' WHERE Code = 'EDJCFAOSPT0'
UPDATE MasterDatas SET ViName = N'Dự trù máu', EnName = N'Order for potential transfusion' WHERE Code = 'EDJCFAOSPT0ANS'
UPDATE MasterDatas SET EnName = N'Anaesthesia method' WHERE Code = 'EDJCFAOSAM0'
UPDATE MasterDatas SET EnName = N'Anaesthesia method' WHERE Code = 'EDJCFAOSAM0ANS'
UPDATE MasterDatas SET EnName = N'Anticipated complication(s), risk, difficulties which required special attention' WHERE Code = 'EDJCFAOSCRDANS'
UPDATE MasterDatas SET EnName = N'Anticipated complication(s), risk, difficulties which required special attention' WHERE Code = 'EDJCFAOSCRD'

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xác nhận bệnh tật',N'Confirmation of illness',N'OPDOENXNBT',N'OPDOEN',N'OPDOEN',N'1',N'303',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'OPDOENXNBTYES',N'OPDOENXNBT',N'OPDOEN',N'2',N'304',N'Radio',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'OPDOENXNBTNO',N'OPDOENXNBT',N'OPDOEN',N'2',N'305',N'Radio',N'',N'0',N'',N'', '');



Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu đánh giá tiêu chuẩn chỉ định xét nghiệm GEN BRCA',N'Criteria Assesssment for GEN BRCA Test already',N'A03_119_201119_V',N'OPDSANPHUKHOA',N'A03_119_201119_V',N'',N'',N'',N'OPD',N'',N'',N'', '');
update MasterDatas set EnName = N'The Dental- Maxillofacial Medical Record'
where Form = 'A01_040_050919_V'
update IPDSetupMedicalRecords set EnName = N'The Dental- Maxillofacial Medical Record'
where Formcode = 'A01_040_050919_V'





Update MasterDatas set EnName = N'1. Cured' where code = N'IPDMRPEKQDTKHO';
Update MasterDatas set EnName = N'2. Improved' where code = N'IPDMRPEKQDTDOG';
Update MasterDatas set EnName = N'3. Unchanged' where code = N'IPDMRPEKQDTKTD';
Update MasterDatas set EnName = N'4. Worsened' where code = N'IPDMRPEKQDTNAH';
Update MasterDatas set EnName = N'5. Deceased' where code = N'IPDMRPEKQDTTUV';

Update MasterDatas set EnName = N'Accident' where code = N'IPDMRPE899';


delete from MasterDatas where Form = 'IPDIAACIN'
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày, giờ phẫu thuật:',N'Surgery date:',N'IPDIAACINNGPT',N'IPDIAACIN',N'IPDIAACIN',N'1',N'750',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ngày, giờ phẫu thuật',N'Surgery date',N'IPDIAACINNGPTIP',N'IPDIAACINNGPT',N'IPDIAACIN',N'2',N'751',N'Datetime',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán lâm sàng trước thủ thuật:',N'Clinical diagnosis before operation:',N'IPDIAACINCDBO',N'IPDIAACIN',N'IPDIAACIN',N'1',N'752',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD10',N'IPDIAACINSLICD',N'IPDIAACINCDBO',N'IPDIAACIN',N'2',N'753',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD10',N'IPDIAACINSLICDT',N'IPDIAACINCDBO',N'IPDIAACIN',N'2',N'754',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'PTV chính',N'Principal interventionist',N'IPDIAACINPIT',N'IPDIAACIN',N'IPDIAACIN',N'1',N'755',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'PTV chính',N'Principal interventionist',N'IPDIAACINPITCL',N'IPDIAACINPIT',N'IPDIAACIN',N'2',N'756',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'PTV phụ',N'Other interventionist',N'IPDIAACINOTT',N'IPDIAACIN',N'IPDIAACIN',N'1',N'757',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'PTV phụ',N'Other interventionist',N'IPDIAACINOTTCL',N'IPDIAACINOTT',N'IPDIAACIN',N'2',N'758',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐD dụng cụ',N'Instrumentalist nurse',N'IPDIAACININ',N'IPDIAACIN',N'IPDIAACIN',N'1',N'759',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐD dụng cụ',N'Instrumentalist nurse',N'IPDIAACININCL',N'IPDIAACININ',N'IPDIAACIN',N'2',N'760',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐD phụ',N'Other nurses',N'IPDIAACINONS',N'IPDIAACIN',N'IPDIAACIN',N'1',N'761',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐD phụ',N'Other nurses',N'IPDIAACINONSCL',N'IPDIAACINONS',N'IPDIAACIN',N'2',N'762',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sĩ gây mê',N'Anesthesiologist',N'IPDIAACINALT',N'IPDIAACIN',N'IPDIAACIN',N'1',N'763',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sĩ gây mê',N'Anesthesiologist',N'IPDIAACINALTCL',N'IPDIAACINALT',N'IPDIAACIN',N'2',N'764',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐD gây mê',N'Nurse anesthetist',N'IPDIAACINNAT',N'IPDIAACIN',N'IPDIAACIN',N'1',N'765',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐD gây mê',N'Nurse anesthetist',N'IPDIAACINNATCL',N'IPDIAACINNAT',N'IPDIAACIN',N'2',N'766',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phương pháp vô cảm',N'Anesthesia method',N'IPDIAACINAMD',N'IPDIAACIN',N'IPDIAACIN',N'1',N'767',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phương pháp vô cảm',N'Anesthesia method',N'IPDIAACINAMDCL',N'IPDIAACINAMD',N'IPDIAACIN',N'2',N'768',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dấu hiệu sinh tồn trước thủ thuật',N'Vital signs before procedure',N'IPDIAACINVSBP',N'IPDIAACIN',N'IPDIAACIN',N'1',N'769',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Huyết áp',N'Blood Pressure',N'IPDIAACINMMHG',N'IPDIAACINVSBP',N'IPDIAACIN',N'2',N'770',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mạch',N'Pusle',N'IPDIAACINBPM',N'IPDIAACINVSBP',N'IPDIAACIN',N'2',N'771',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nhịp thở',N'Respiration',N'IPDIAACINBNTT',N'IPDIAACINVSBP',N'IPDIAACIN',N'2',N'772',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Sp02',N'Sp02',N'IPDIAACINSPO2',N'IPDIAACINVSBP',N'IPDIAACIN',N'2',N'773',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'TÓM TẮT QUY TRÌNH',N' Summary of the process',N'IPDIAACINSOTP',N'IPDIAACIN',N'IPDIAACIN',N'1',N'774',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nong ĐMV',N'Coronary dilatation',N'IPDIAACINNDMV',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'775',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Stent ĐMV',N' Coronary stenting',N'IPDIAACINCSDMV',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'776',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đường vào',N'Acces point',N'IPDIAACINACCP',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'777',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kích thước ống vào',N'Introducer',N'IPDIAACINITDC',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'778',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dây dẫn',N'Guidewire',N'IPDIAACINGDW',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'779',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ống thông',N'Catheter',N'IPDIAACINCTH',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'780',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Loại khác',N'Other',N'IPDIAACINLOTH',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'781',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bóng',N'Balloon',N'IPDIAACINBLLL',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'782',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giá đỡ',N'Stent',N'IPDIAACINBSTE',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'783',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thuốc cản quang',N'Contrast media',N'IPDIAACINBTCQ',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'784',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tổng liều tia',N'Medication dose',N'IPDIAACINBTTD',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'785',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các nhãn vật tư',N'Consumable labels',N'IPDIAACINCNVT',N'IPDIAACIN',N'IPDIAACIN',N'1',N'786',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các nhãn vật tư',N'Consumable labels',N'IPDIAACINCNVTCLD',N'IPDIAACINCNVT',N'IPDIAACIN',N'2',N'787',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các thăm dò khác kèm theo',N'Other explorations',N'IPDIAACINOES',N'IPDIAACIN',N'IPDIAACIN',N'1',N'788',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Các thăm dò khác kèm theo',N'Other explorations',N'IPDIAACINOESCLD',N'IPDIAACINOES',N'IPDIAACIN',N'2',N'789',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biến chứng/ Diễn biến bất thường',N'Complications/ Adverse events',N'IPDIAACINCAES',N'IPDIAACIN',N'IPDIAACIN',N'1',N'790',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Rối loạn nhịp',N'Arrhythmia',N'IPDIAACINCAES1',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'791',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tổn thương mạch',N'Vascular injury',N'IPDIAACINCAES2',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'792',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Co thắt mạch',N'Vasoconstriction',N'IPDIAACINCAES3',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'793',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thủng ĐMV',N'Coronary perforation',N'IPDIAACINCAES4',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'794',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tụt HA',N'Hypotension',N'IPDIAACINCAES5',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'795',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chảy máu',N'Bleeding',N'IPDIAACINCAES6',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'796',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N' Tràn dịch MNT',N'Pericardial effusion',N'IPDIAACINCAES7',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'797',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tắc ĐMV cấp',N'Acute coronary thrombosis',N'IPDIAACINCAES8',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'798',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác ',N'Other',N'IPDIAACINCAES9',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'799',N'Checkbox',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác ',N'Other',N'IPDIAACINCAES10',N'IPDIAACINCAES',N'IPDIAACIN',N'2',N'800',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nhận xét khác',N'Other comments',N'IPDIAACINNXK',N'IPDIAACIN',N'IPDIAACIN',N'1',N'801',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nhận xét khác',N'Other comments',N'IPDIAACINNXKCD',N'IPDIAACINNXK',N'IPDIAACIN',N'2',N'802',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Lượng máu mất',N'Blood loss volume',N'IPDIAACINBLV',N'IPDIAACIN',N'IPDIAACIN',N'1',N'803',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Lượng máu mất',N'Blood loss volume',N'IPDIAACINBLVCD',N'IPDIAACINBLV',N'IPDIAACIN',N'2',N'804',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Số mẫu bệnh phẩm',N'Serial of samples',N'IPDIAACINSMBP',N'IPDIAACIN',N'IPDIAACIN',N'1',N'805',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Số mẫu bệnh phẩm',N'Serial of samples',N'IPDIAACINSMBPCD',N'IPDIAACINSMBP',N'IPDIAACIN',N'2',N'806',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'KẾT LUẬN',N'Conclusion',N'IPDIAACINKLC',N'IPDIAACIN',N'IPDIAACIN',N'1',N'807',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'KẾT LUẬN',N'Conclusion',N'IPDIAACINKLCCD',N'IPDIAACINKLC',N'IPDIAACIN',N'2',N'808',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐỀ XUẤT',N'Suggestion',N'IPDIAACINSGG',N'IPDIAACIN',N'IPDIAACIN',N'1',N'809',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐỀ XUẤT',N'Suggestion',N'IPDIAACINSGGCD',N'IPDIAACINSGG',N'IPDIAACIN',N'2',N'810',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán lâm sàng trước thủ thuật',N'Clinical diagnosis before operation',N'IPDIAACINCDBOD',N'IPDIAACIN',N'IPDIAACIN',N'1',N'811',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD10',N'IPDIAACINCDBODCLIP',N'IPDIAACINCDBOD',N'IPDIAACIN',N'2',N'812',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD11',N'IPDIAACINCDBODCLIPCD',N'IPDIAACINCDBOD',N'IPDIAACIN',N'2',N'813',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán lâm sàng sau thủ thuật:',N'Diagnosis after operation:',N'IPDIAACINCDLSSTT',N'IPDIAACIN',N'IPDIAACIN',N'1',N'814',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD10',N'IPDIAACINCDLSSTTCD1',N'IPDIAACINCDLSSTT',N'IPDIAACIN',N'2',N'815',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD10',N'IPDIAACINCDLSSTTCD2',N'IPDIAACINCDLSSTT',N'IPDIAACIN',N'2',N'816',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kích thước ống vào',N'Size of introducer',N'IPDIAACINKTOV',N'IPDIAACIN',N'IPDIAACIN',N'1',N'817',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kích thước ống vào',N'Size of introducer',N'IPDIAACINCD1',N'IPDIAACINKTOV',N'IPDIAACIN',N'2',N'818',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dây dẫn',N'Guidewire',N'IPDIAACINDAYDAN',N'IPDIAACIN',N'IPDIAACIN',N'1',N'819',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dây dẫn',N'Guidewire',N'IPDIAACINDAYDANCD1',N'IPDIAACINDAYDAN',N'IPDIAACIN',N'2',N'820',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD10',N'IPDIAACINSLICDSTT',N'IPDIAACINCDBO',N'IPDIAACIN',N'2',N'821',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chọn ICD10',N'Select ICD10',N'IPDIAACINSLICDSTTCD1',N'IPDIAACINCDBO',N'IPDIAACIN',N'2',N'822',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kích thước ống vào',N'Size of introducer',N'IPDIAACINACCPKTOV',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'823',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thiết bị đóng mạch',N'Closure device',N'IPDIAACINACCPTBDM',N'IPDIAACINSOTP',N'IPDIAACIN',N'2',N'824',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACINUPLOAD',N'IPDIAACIN',N'IPDIAACIN',N'1',N'825',N'Label',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACINUPLOADCD1',N'IPDIAACINUPLOAD',N'IPDIAACIN',N'2',N'826',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACINUPLOADCD2',N'IPDIAACINUPLOAD',N'IPDIAACIN',N'2',N'827',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tổng thời gian thực hiện thủ thuật',N'Total procedure time',N'IPDIAACINACCTTGTH',N'IPDIAACINCDBO',N'IPDIAACIN',N'2',N'828',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACINUPLOADCD3',N'IPDIAACINUPLOAD',N'IPDIAACIN',N'2',N'829',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACINUPLOADCD4',N'IPDIAACINUPLOAD',N'IPDIAACIN',N'2',N'830',N'Text',N'',N'0',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'UploadFile',N'UploadFile',N'IPDIAACINUPLOADCD5',N'IPDIAACINUPLOAD',N'IPDIAACIN',N'2',N'831',N'Text',N'',N'0',N'',N'', '');

