Update MasterDatas set EnName = N'+ Circulatory system' where code = N'IPDMRPTTUHO';
Update MasterDatas set EnName = N'+ Respiratory system' where code = N'IPDMRPTHOHA';
Update MasterDatas set EnName = N'+ Digestive system' where code = N'IPDMRPTTIHO';
Update MasterDatas set EnName = N'+ Nervous system' where code = N'IPDMRPTTHKI';
Update MasterDatas set EnName = N'+ Musculoskeletal system' where code = N'IPDMRPTCOXK';
Update MasterDatas set EnName = N'+ Nephro-urological system' where code = N'IPDMRPTTTNS';
Update MasterDatas set EnName = N'Yes' where code = N'IPDMRPEGIPBYES';
Update MasterDatas set EnName = N'No' where code = N'IPDMRPEGIPBNOO';
Update MasterDatas set EnName = N'2. After 24 hours of admission' where code = N'IPDMRPTTTTVSAU';
Update MasterDatas set EnName = N'3. Medical history' where code = N'IPDMRPTTISB';
Update MasterDatas set EnName = N'Pulse' where code = N'IPDMRPTMACH';
Update MasterDatas set EnName = N'Temp' where code = N'IPDMRPTNHDO';
Update MasterDatas set EnName = N'BP' where code = N'IPDMRPTHUAP';
Update MasterDatas set EnName = N'RR' where code = N'IPDMRPTNHTH';
Update MasterDatas set EnName = N'Height' where code = N'IPDMRPTCICA';
Update MasterDatas set EnName = N'Weight' where code = N'IPDMRPTCANA';
Update MasterDatas set EnName = N'Yes' where code = N'IPDMRPEGIPBYES';
Update MasterDatas set EnName = N'No' where code = N'IPDMRPEGIPBNOO';
Update MasterDatas set EnName = N'Significant medications' where code = N'IPDMRPETCDD';
Update MasterDatas set EnName = N'Patient status at discharge' where code = N'IPDMRPETTNB';
Update MasterDatas set EnName = N'+ ICD10 Co-morbidity (if having)' where code = N'IPDMRPEICDP';
Update MasterDatas set EnName = N'4. Used Medication List' where code = N'IPDMRPETCDD';
Update MasterDatas set EnName = N'5. Patient status at discharge' where code = N'IPDMRPETTNB';
Update MasterDatas set EnName = N'6. Indication and follow-up plan' where code = N'IPDMRPEHDTV';
Update MasterDatas set EnName = N'Specimen' where code = N'IPDMRPEBEPH';
Update MasterDatas set EnName = N'1. History of present illness' where code = N'IPDMRPTQTBL';
Update MasterDatas set EnName = N'Surgical diseases' where code = N'IPDMRPTBNK0001';
Update MasterDatas set EnName = N'Specialized examination' where code = N'IPDMRPT10023';
Update MasterDatas set EnName = N'Right' where code = N'IPDMRPT10026';
Update MasterDatas set EnName = N'Front' where code = N'IPDMRPT10028';
Update MasterDatas set EnName = N'Left' where code = N'IPDMRPT10030';
Update MasterDatas set EnName = N'Upper jaw and throat' where code = N'IPDMRPT10032';
Update MasterDatas set EnName = N'Lower jaw' where code = N'IPDMRPT10034';
Update MasterDatas set EnName = N'lip-palate' where code = N'IPDMRPT10036';
Update MasterDatas set EnName = N'Psychological, nervous system' where code = N'IPDMRPTTHKI';
Update MasterDatas set EnName = N'Skin and subcutaneous tissue' where code = N'IPDMRPT10021';
Update MasterDatas set EnName = N'Nephro-urological system' where code = N'IPDMRPTTTNS';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPTNTDD';
Update MasterDatas set EnName = N'Specialized examination' where code = N'IPDMRPT10000';
Update MasterDatas set EnName = N'Drawing of injury at admission' where code = N'IPDMRPT10002';
Update MasterDatas set EnName = N'Right tympanic membrane' where code = N'IPDMRPT10003';
Update MasterDatas set EnName = N'Left tympanic membrane' where code = N'IPDMRPT10005';
Update MasterDatas set EnName = N'Anterior nose' where code = N'IPDMRPT10007';
Update MasterDatas set EnName = N'Posterior nose' where code = N'IPDMRPT10009';
Update MasterDatas set EnName = N'Larynx' where code = N'IPDMRPT10011';
Update MasterDatas set EnName = N'Pharynx' where code = N'IPDMRPT10013';
Update MasterDatas set EnName = N'Neck turning left' where code = N'IPDMRPT10015';
Update MasterDatas set EnName = N'Neck turning right' where code = N'IPDMRPT10017';
Update MasterDatas set EnName = N'2. Other organs' where code = N'IPDMRPTCACQ';
Update MasterDatas set EnName = N'3. Neccessary laboratory tests' where code = N'IPDMRPTCXNC';
Update MasterDatas set EnName = N'4. Summary' where code = N'IPDMRPTTTBA';
Update MasterDatas set EnName = N'Accident' where code = N'IPDMRPETHPTTHU';
Update MasterDatas set EnName = N'Complication' where code = N'IPDMRPETHPTPHA';
Update MasterDatas set EnName = N'Monther’s blood group' where code = N'IPDMRPOS9';
Update MasterDatas set EnName = N'History of pregnancy (Para)' where code = N'IPDMRPOS11';
Update MasterDatas set EnName = N'Full-term' where code = N'IPDMRPOS12';
Update MasterDatas set EnName = N'Pre-term' where code = N'IPDMRPOS13';
Update MasterDatas set EnName = N'Misscarriage (Suction, D&E)' where code = N'IPDMRPOS14';
Update MasterDatas set EnName = N'Alive' where code = N'IPDMRPOS15';
Update MasterDatas set EnName = N'Labour' where code = N'IPDMRPT62';
Update MasterDatas set EnName = N'Amniotic membrance rupture' where code = N'IPDMRPT63';
Update MasterDatas set EnName = N'Colour' where code = N'IPDMRPT65';
Update MasterDatas set EnName = N'Delivery mode' where code = N'IPDMRPT67';
Update MasterDatas set EnName = N'Vaginally' where code = N'IPDMRPT68';
Update MasterDatas set EnName = N'Intervention' where code = N'IPDMRPT69';
Update MasterDatas set EnName = N'Newborn’s condition at birth' where code = N'IPDMRPT74';
Update MasterDatas set EnName = N'Cry immediately' where code = N'IPDMRPT75';
Update MasterDatas set EnName = N'Birth asphyxia' where code = N'IPDMRPT76';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPT77';
Update MasterDatas set EnName = N'Name of deliver' where code = N'IPDMRPT78';
Update MasterDatas set EnName = N'1 minute' where code = N'IPDMRPT82';
Update MasterDatas set EnName = N'5 minute' where code = N'IPDMRPT85';
Update MasterDatas set EnName = N'10 minute' where code = N'IPDMRPT88';
Update MasterDatas set EnName = N'Score' where code = N'IPDMRPT84';
Update MasterDatas set EnName = N'Score' where code = N'IPDMRPT87';
Update MasterDatas set EnName = N'Score' where code = N'IPDMRPT90';
Update MasterDatas set EnName = N'Nutritionnal status after birth' where code = N'IPDMRPT91';
Update MasterDatas set EnName = N'c.  Method of neonatal resuscitation' where code = N'IPDMRPT93';
Update MasterDatas set EnName = N'Suctioning' where code = N'IPDMRPT94';
Update MasterDatas set EnName = N'Chest compression' where code = N'IPDMRPT96';
Update MasterDatas set EnName = N'Oxygen supply' where code = N'IPDMRPT97';
Update MasterDatas set EnName = N'Endotracheal intubation' where code = N'IPDMRPT98';
Update MasterDatas set EnName = N'BVM ventilation' where code = N'IPDMRPT99';
Update MasterDatas set EnName = N'Other' where code = N'IPDMRPT100';
Update MasterDatas set EnName = N'Name of neonatal referrer' where code = N'IPDMRPT102';
Update MasterDatas set EnName = N'1. General status' where code = N'IPDMRPT104';
Update MasterDatas set EnName = N'- Congenital anomalies' where code = N'IPDMRPT105';
Update MasterDatas set EnName = N'- Anus presence' where code = N'IPDMRPT106';
Update MasterDatas set EnName = N'- Newborn’s condition in admission' where code = N'IPDMRPT109';
Update MasterDatas set EnName = N'+ Overall condition:' where code = N'IPDMRPT112';
Update MasterDatas set EnName = N'+ Skin colour:' where code = N'IPDMRPT114';
Update MasterDatas set EnName = N'Reason for intervention' where code = N'IPDMRPT72';
Update MasterDatas set EnName = N'Detailed congenital anomalies' where code = N'IPDMRPT107';
Update MasterDatas set EnName = N'1. Pink' where code = N'IPDMRPT115';
Update MasterDatas set EnName = N'2. Pale' where code = N'IPDMRPT116';
Update MasterDatas set EnName = N'3. Icteric' where code = N'IPDMRPT117';
Update MasterDatas set EnName = N'4. Cyanosis' where code = N'IPDMRPT118';
Update MasterDatas set EnName = N'5. Other' where code = N'IPDMRPT119';
Update MasterDatas set EnName = N'Breath rate:' where code = N'IPDMRPT141';
Update MasterDatas set EnName = N'+ Lung auscultation:' where code = N'IPDMRPT121';
Update MasterDatas set EnName = N'+ Silverman index:' where code = N'IPDMRPT123';
Update MasterDatas set EnName = N'- Cardiac exam:' where code = N'IPDMRPT125';
Update MasterDatas set EnName = N'Heart rate' where code = N'IPDMRPT143';
Update MasterDatas set EnName = N'- Abdomen:' where code = N'IPDMRPT127';
Update MasterDatas set EnName = N'- Genital organs:' where code = N'IPDMRPT129';
Update MasterDatas set EnName = N'- Bone and joints:' where code = N'IPDMRPT131';
Update MasterDatas set EnName = N'- Neurology:' where code = N'IPDMRPT133';
Update MasterDatas set EnName = N'+ Reflex:' where code = N'IPDMRPT134';
Update MasterDatas set EnName = N'+ Mucle tone:' where code = N'IPDMRPT136';
Update MasterDatas set EnName = N'5. Indication for monitoring:' where code = N'IPDMRPT138';
Update MasterDatas set EnName = N'Head' where code = N'IPDMRPT110';
Update MasterDatas set EnName = N'1. History of present illness and clinical developements' where code = N'IPDMRPEQTBL';
Update MasterDatas set EnName = N'Summary of valuable para-clinical laboratory test results' where code = N'IPDMRPETTKQ';
Update MasterDatas set EnName = N'3. Treatment methods' where code = N'IPDMRPEPPDT';
Update MasterDatas set EnName = N'Chief complaints' where code = N'IPDMRPTLDVV';
Update MasterDatas set EnName = N'+ ICD10 Main disease' where code = N'IPDMRPTICDC';
Update MasterDatas set EnName = N'+ Main disease' where code = N'IPDMRPTCDBC';
Update MasterDatas set EnName = N'+ ICD10 Co-morbidity (if having)' where code = N'IPDMRPTICDP';
Update MasterDatas set EnName = N'+ Co-morbidity (if having)' where code = N'IPDMRPTCDKT';
Update MasterDatas set EnName = N'+ Differential diagnosis(if any)' where code = N'IPDMRPTPHBI';
Update MasterDatas set EnName = N'2. Summary of laboratory tests for diagnosis' where code = N'IPDMRPETTKQ';
Update MasterDatas set EnName = N'Procedure' where code = N'IPDMRPTTHPTTHU';
Update MasterDatas set EnName = N'Surgery' where code = N'IPDMRPTTHPTPHA';
Update MasterDatas set EnName = N'2. After 48 hours of admission' where code = N'IPDMRPT951';
Update MasterDatas set EnName = N'Specialize' where code = N'IPDMRPGRV02';
Update MasterDatas set EnName = N'Economy' where code = N'IPDMRPGRV03';
Update MasterDatas set EnName = N'Other' where code = N'IPDMRPGRV04';
Update MasterDatas set EnName = N'Uterine control' where code = N'IPDMRPE847';
Update MasterDatas set EnName = N'Drawing of injury at admission' where code = N'IPDMRPT10025';
Update MasterDatas set EnName = N'Date of birth' where code = N'IPDMRPOS3';
Update MasterDatas set EnName = N'This is time of delivery' where code = N'IPDMRPOS5';
Update MasterDatas set EnName = N'1. Cured' where code = N'IPDMRPEKQDTKHO';
Update MasterDatas set EnName = N'2. Improved' where code = N'IPDMRPEKQDTDOG';
Update MasterDatas set EnName = N'3. Unchanged' where code = N'IPDMRPEKQDTKTD';
Update MasterDatas set EnName = N'4. Worsened' where code = N'IPDMRPEKQDTNAH';
Update MasterDatas set EnName = N'5. Deceased' where code = N'IPDMRPEKQDTTUV';
Update MasterDatas set EnName = N'+ Resporatory system' where code = N'IPDMRPTHOHAANS';
Update MasterDatas set EnName = N'+ Digestive system' where code = N'IPDMRPTTIHOANS';
Update MasterDatas set EnName = N'+ Renal - Urogenital - Genital system' where code = N'IPDMRPTTTNSANS';
Update MasterDatas set EnName = N'+ Nervous system' where code = N'IPDMRPTTHKIANS';
Update MasterDatas set EnName = N'+ Musculoskeletal system' where code = N'IPDMRPTCOXKANS';
Update MasterDatas set EnName = N'+ Ear - Nose - Throat' where code = N'IPDMRPTTAMHANS';
Update MasterDatas set EnName = N'+ Dento-maxillofacial' where code = N'IPDMRPTRAHMANS';
Update MasterDatas set EnName = N'+ Eye' where code = N'IPDMRPTMMATANS';
Update MasterDatas set EnName = N'+ Endocrine, Nutrition and other diseases' where code = N'IPDMRPTNTDDANS';
Update MasterDatas set EnName = N'3. Neccessary laboratory tests' where code = N'IPDMRPTCXNCANS';
Update MasterDatas set EnName = N'3. Summary' where code = N'IPDMRPTTTBAANS';
Update MasterDatas set EnName = N'4. Patient status at discharge' where code = N'IPDMRPTTTBAANS';
Update MasterDatas set EnName = N'1. History of present illness and clinical developments' where code = N'IPDMRPEQTBLANS';
Update MasterDatas set EnName = N'2. Summary of laboratory tests for diagnosis' where code = N'IPDMRPETTKQANS';
Update MasterDatas set EnName = N'3. Treatment methods' where code = N'IPDMRPEPPDTANS';
Update MasterDatas set EnName = N'+ Main disease' where code = N'IPDMRPECDBCANS';
Update MasterDatas set EnName = N'6. Indication and follow-up plan' where code = N'IPDMRPEHDTVANS';
Update MasterDatas set EnName = N'Treatment result' where code = N'IPDMRPEKQDT';
Update MasterDatas set EnName = N'1. Clinical evolution' where code = N'IPDMRPTQTBLANS';
Update MasterDatas set EnName = N'+ Personal medical history' where code = N'IPDMRPTBATHANS';
Update MasterDatas set EnName = N'+ Family medical history' where code = N'IPDMRPTGIDIANS';
Update MasterDatas set EnName = N'Transfer Date time' where code = N'IPDMRPTCHVHANS';
Update MasterDatas set EnName = N'+ Circulatory system' where code = N'IPDMRPTTUHOANS';
Update MasterDatas set EnName = N'Transfer' where code = N'IPDMRPTCHVI';
Update MasterDatas set EnName = N'Chief complaints' where code = N'IPDMRPTLDVVANS';
Update MasterDatas set EnName = N'+ Main disease' where code = N'IPDMRPTCDBCANS';
Update MasterDatas set EnName = N'5. Patient status at discharge' where code = N'IPDMRPETTNBANS';
Update MasterDatas set EnName = N'On day' where code = N'IPDMRPTVANTANS';
Update MasterDatas set EnName = N'1. General status:( consciousess, skin and mucosa, lymphatic system, thyroid gland, location, size, quantity)' where code = N'IPDMRPTTTYTANS';
Update MasterDatas set EnName = N'+ ICD10 Main disease' where code = N'IPDMRPTICDCANS';
Update MasterDatas set EnName = N'4. Used Medication List' where code = N'IPDMRPETCDDANS';
Update MasterDatas set EnName = N'Specialized examination' where code = N'IPDMRPT10024';
Update MasterDatas set EnName = N'+ Skin and subcutaneous tissue' where code = N'IPDMRPT10022';
Update MasterDatas set EnName = N'Reason for transfer' where code = N'IPDMRPTLDCKANS';
Update MasterDatas set EnName = N'Receiving' where code = N'IPDMRPTNONHANS';
Update MasterDatas set EnName = N'Discharge form' where code = N'IPDMRPTHTRV';
Update MasterDatas set EnName = N'Dead Date time' where code = N'IPDMRPTNGTVANS';
Update MasterDatas set EnName = N'Pass away' where code = N'IPDMRPTLDTV';
Update MasterDatas set EnName = N'Pass away' where code = N'IPDMRPTTTTV';
Update MasterDatas set EnName = N'ICD10 CODE' where code = N'IPDMRPTICDTANS';
Update MasterDatas set EnName = N'Main disease' where code = N'IPDMRPTBCTVANS';
Update MasterDatas set EnName = N'1. Benign' where code = N'IPDMRPEGIPBLAT';
Update MasterDatas set EnName = N'2. Suspicious' where code = N'IPDMRPEGIPBNGN';
Update MasterDatas set EnName = N'3. Malignant' where code = N'IPDMRPEGIPBACT';
Update MasterDatas set EnName = N'+ ICD10 Main disease' where code = N'IPDMRPEICDC';
Update MasterDatas set EnName = N'+ Co-morbidity (if having)' where code = N'IPDMRPECDKT';
Update MasterDatas set EnName = N'Discharge Date time' where code = N'IPDMRPTCDRVANS';
Update MasterDatas set EnName = N'Specialized examination' where code = N'IPDMRPT10001';


Update MasterDatas set EnName = N'Tiền sử sản khoa' where code = N'IPDSANTBL1';
Update MasterDatas set EnName = N'Number of pregnancy' where code = N'IPDSANTBL2';
Update MasterDatas set EnName = N'Year' where code = N'IPDSANTBL3';
Update MasterDatas set EnName = N'Full-term' where code = N'IPDSANTBL4';
Update MasterDatas set EnName = N'Pre-term' where code = N'IPDSANTBL5';
Update MasterDatas set EnName = N'Miscarriage' where code = N'IPDSANTBL6';
Update MasterDatas set EnName = N'Suction' where code = N'IPDSANTBL7';
Update MasterDatas set EnName = N'D&E' where code = N'IPDSANTBL8';
Update MasterDatas set EnName = N'Co-vac' where code = N'IPDSANTBL9';
Update MasterDatas set EnName = N'Ectopic pregnancy' where code = N'IPDSANTBL10';
Update MasterDatas set EnName = N'Hydatidiform mole' where code = N'IPDSANTBL11';
Update MasterDatas set EnName = N'Stillbirth' where code = N'IPDSANTBL12';
Update MasterDatas set EnName = N'Alive' where code = N'IPDSANTBL13';
Update MasterDatas set EnName = N'Weight' where code = N'IPDSANTBL14';
Update MasterDatas set EnName = N'Labour method' where code = N'IPDSANTBL15';
Update MasterDatas set EnName = N'Accident' where code = N'IPDSANTBL16';

Update MasterDatas set EnName = N'Tình hình phẫu thuật' where code = N'IPDSANTHPT1';
Update MasterDatas set EnName = N'Hour, date' where code = N'IPDSANTHPT2';
Update MasterDatas set EnName = N'Surgical/Anesthesia methods' where code = N'IPDSANTHPT3';
Update MasterDatas set EnName = N'Surgeon' where code = N'IPDSANTHPT4';
Update MasterDatas set EnName = N'Anesthesiologist' where code = N'IPDSANTHPT5';

Update MasterDatas set EnName = N'IV. Monitoring in labour ward' where code = N'IPDMRPE800';
Update MasterDatas set EnName = N'Admitted to labour ward at:' where code = N'IPDMRPE801';
Update MasterDatas set EnName = N'Admitted to labour ward at:' where code = N'IPDMRPE802';
Update MasterDatas set EnName = N'Delivery date (C-section)' where code = N'IPDMRPE803';
Update MasterDatas set EnName = N'Delivery date (C-section)' where code = N'IPDMRPE804';
Update MasterDatas set EnName = N'Observer' where code = N'IPDMRPE805';
Update MasterDatas set EnName = N'Observer' where code = N'IPDMRPE806';
Update MasterDatas set EnName = N'Delivery at' where code = N'IPDMRPE807';
Update MasterDatas set EnName = N'Delivery at' where code = N'IPDMRPE808';
Update MasterDatas set EnName = N'Neonate' where code = N'IPDMRPE809';
Update MasterDatas set EnName = N'a - Alive' where code = N'IPDMRPE810';
Update MasterDatas set EnName = N'b - Dead' where code = N'IPDMRPE811';
Update MasterDatas set EnName = N'Đơn/Đa thai' where code = N'IPDMRPE812';
Update MasterDatas set EnName = N'Single' where code = N'IPDMRPE813';
Update MasterDatas set EnName = N'Male' where code = N'IPDMRPE814';
Update MasterDatas set EnName = N'Female' where code = N'IPDMRPE815';
Update MasterDatas set EnName = N'Multiple' where code = N'IPDMRPE816';
Update MasterDatas set EnName = N'Male' where code = N'IPDMRPE817';
Update MasterDatas set EnName = N'Female' where code = N'IPDMRPE818';
Update MasterDatas set EnName = N'Baby physical status after birth' where code = N'IPDMRPE819';
Update MasterDatas set EnName = N'Baby physical status after birth' where code = N'IPDMRPE820';
Update MasterDatas set EnName = N'Interventions and results' where code = N'IPDMRPE821';
Update MasterDatas set EnName = N'Interventions and results' where code = N'IPDMRPE822';
Update MasterDatas set EnName = N'2. Delivery of placenta' where code = N'IPDMRPE823';
Update MasterDatas set EnName = N'Placenta asound the neck' where code = N'IPDMRPE824';
Update MasterDatas set EnName = N'Placenta asound the neck' where code = N'IPDMRPE825';
Update MasterDatas set EnName = N'Placenta' where code = N'IPDMRPE826';
Update MasterDatas set EnName = N'Artificial' where code = N'IPDMRPE827';
Update MasterDatas set EnName = N'Natural' where code = N'IPDMRPE828';
Update MasterDatas set EnName = N'Delivery of placenta at:' where code = N'IPDMRPE829';
Update MasterDatas set EnName = N'Delivery of placenta at:' where code = N'IPDMRPE830';
Update MasterDatas set EnName = N'Bleeding after placenta delivery' where code = N'IPDMRPE831';
Update MasterDatas set EnName = N'Bleeding after placenta delivery' where code = N'IPDMRPE832';
Update MasterDatas set EnName = N'Bleeding after placenta delivery' where code = N'IPDMRPE833';
Update MasterDatas set EnName = N'Type of placenta delivery' where code = N'IPDMRPE834';
Update MasterDatas set EnName = N'Type of placenta delivery' where code = N'IPDMRPE835';
Update MasterDatas set EnName = N'Fetal surface' where code = N'IPDMRPE836';
Update MasterDatas set EnName = N'Fetal surface' where code = N'IPDMRPE837';
Update MasterDatas set EnName = N'Maternal surface' where code = N'IPDMRPE838';
Update MasterDatas set EnName = N'Maternal surface' where code = N'IPDMRPE839';
Update MasterDatas set EnName = N'Placenta' where code = N'IPDMRPE840';
Update MasterDatas set EnName = N'Placenta' where code = N'IPDMRPE841';
Update MasterDatas set EnName = N'Weight' where code = N'IPDMRPE842';
Update MasterDatas set EnName = N'Weight' where code = N'IPDMRPE843';
Update MasterDatas set EnName = N'Length of placenta stem' where code = N'IPDMRPE844';
Update MasterDatas set EnName = N'Length of placenta stem' where code = N'IPDMRPE845';
Update MasterDatas set EnName = N'Uterine management' where code = N'IPDMRPE846';
Update MasterDatas set EnName = N'Uterine management' where code = N'IPDMRPE847';
Update MasterDatas set EnName = N'Intervention and results' where code = N'IPDMRPE848';
Update MasterDatas set EnName = N'Intervention and results' where code = N'IPDMRPE849';
Update MasterDatas set EnName = N'3. Status of new mother after delivery' where code = N'IPDMRPE850';
Update MasterDatas set EnName = N'Pulse' where code = N'IPDMRPE851';
Update MasterDatas set EnName = N'Pulse' where code = N'IPDMRPE852';
Update MasterDatas set EnName = N'Temp' where code = N'IPDMRPE853';
Update MasterDatas set EnName = N'Temp' where code = N'IPDMRPE854';
Update MasterDatas set EnName = N'BP' where code = N'IPDMRPE855';
Update MasterDatas set EnName = N'BP' where code = N'IPDMRPE856';
Update MasterDatas set EnName = N'RR' where code = N'IPDMRPE857';
Update MasterDatas set EnName = N'RR' where code = N'IPDMRPE858';
Update MasterDatas set EnName = N'Skin, mucosa' where code = N'IPDMRPE859';
Update MasterDatas set EnName = N'Skin, mucosa' where code = N'IPDMRPE860';
Update MasterDatas set EnName = N'Type of delivery' where code = N'IPDMRPE861';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPE862';
Update MasterDatas set EnName = N'Forceps' where code = N'IPDMRPE863';
Update MasterDatas set EnName = N'Vacuum' where code = N'IPDMRPE864';
Update MasterDatas set EnName = N'C-section' where code = N'IPDMRPE865';
Update MasterDatas set EnName = N'Elective' where code = N'IPDMRPE866';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPE867';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPE868';
Update MasterDatas set EnName = N'Intervention reason' where code = N'IPDMRPE869';
Update MasterDatas set EnName = N'Intervention reason' where code = N'IPDMRPE870';
Update MasterDatas set EnName = N'Perineum' where code = N'IPDMRPE871';
Update MasterDatas set EnName = N'Intact' where code = N'IPDMRPE872';
Update MasterDatas set EnName = N'Tear' where code = N'IPDMRPE873';
Update MasterDatas set EnName = N'Cut' where code = N'IPDMRPE874';
Update MasterDatas set EnName = N'If any, type of suture and stitch' where code = N'IPDMRPE875';
Update MasterDatas set EnName = N'If any, type of suture and stitch' where code = N'IPDMRPE876';
Update MasterDatas set EnName = N'Number of stitches' where code = N'IPDMRPE877';
Update MasterDatas set EnName = N'Number of stitches' where code = N'IPDMRPE878';
Update MasterDatas set EnName = N'Cervix' where code = N'IPDMRPE879';
Update MasterDatas set EnName = N'Intact' where code = N'IPDMRPE880';
Update MasterDatas set EnName = N'Tear' where code = N'IPDMRPE881';
Update MasterDatas set EnName = N'5. Surgical status (If any)' where code = N'IPDMRPE882';
Update MasterDatas set EnName = N'No' where code = N'IPDMRPE883';
Update MasterDatas set EnName = N'Yes' where code = N'IPDMRPE884';
Update MasterDatas set EnName = N'Cấp cứu/ Chủ động' where code = N'IPDMRPE885';
Update MasterDatas set EnName = N'1. Emergency' where code = N'IPDMRPE886';
Update MasterDatas set EnName = N'2. Elective' where code = N'IPDMRPE887';
Update MasterDatas set EnName = N'Pre-operative diagnosis' where code = N'IPDMRPE888';
Update MasterDatas set EnName = N'IDC10 Code' where code = N'IPDMRPE889';
Update MasterDatas set EnName = N'Pre-operative diagnosis' where code = N'IPDMRPE890';
Update MasterDatas set EnName = N'Post-operative diagnosis' where code = N'IPDMRPE891';
Update MasterDatas set EnName = N'IDC10 Code' where code = N'IPDMRPE892';
Update MasterDatas set EnName = N'Post-operative diagnosis' where code = N'IPDMRPE893';
Update MasterDatas set EnName = N'Surgical times' where code = N'IPDMRPE894';
Update MasterDatas set EnName = N'Surgical times' where code = N'IPDMRPE895';
Update MasterDatas set EnName = N'Post-operative hospital stay' where code = N'IPDMRPE896';
Update MasterDatas set EnName = N'Post-operative hospital stay' where code = N'IPDMRPE897';
Update MasterDatas set EnName = N'Tai biến phẫu thuật ; Biến chứng' where code = N'IPDMRPE898';
Update MasterDatas set EnName = N'Surgical accident' where code = N'IPDMRPE899';
Update MasterDatas set EnName = N'Complication' where code = N'IPDMRPE900';
Update MasterDatas set EnName = N'Do' where code = N'IPDMRPE901';
Update MasterDatas set EnName = N'Surgical cause' where code = N'IPDMRPE902';
Update MasterDatas set EnName = N'Anesthesia cause' where code = N'IPDMRPE903';
Update MasterDatas set EnName = N'Infection cause' where code = N'IPDMRPE904';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPE905';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPE906';
Update MasterDatas set EnName = N'1 minute' where code = N'IPDMRPE907';
Update MasterDatas set EnName = N'1 minute' where code = N'IPDMRPE908';
Update MasterDatas set EnName = N'5 minute' where code = N'IPDMRPE909';
Update MasterDatas set EnName = N'5 minute' where code = N'IPDMRPE910';
Update MasterDatas set EnName = N'10 minute' where code = N'IPDMRPE911';
Update MasterDatas set EnName = N'10 minute' where code = N'IPDMRPE912';
Update MasterDatas set EnName = N'Anus presence' where code = N'IPDMRPE913';
Update MasterDatas set EnName = N'Anus presence' where code = N'IPDMRPE914';
Update MasterDatas set EnName = N'Congenital disabilities' where code = N'IPDMRPE915';
Update MasterDatas set EnName = N'Congenital disabilities' where code = N'IPDMRPE916';
Update MasterDatas set EnName = N'Detailed congenital disabilities' where code = N'IPDMRPE917';
Update MasterDatas set EnName = N'Detailed congenital disabilities' where code = N'IPDMRPE918';
Update MasterDatas set EnName = N'Trai/Gái' where code = N'IPDMRPE919';
Update MasterDatas set EnName = N'Male' where code = N'IPDMRPE920';
Update MasterDatas set EnName = N'Female' where code = N'IPDMRPE921';
Update MasterDatas set EnName = N'Trai/Gái2' where code = N'IPDMRPE922';
Update MasterDatas set EnName = N'Male' where code = N'IPDMRPE923';
Update MasterDatas set EnName = N'Female' where code = N'IPDMRPE924';
Update MasterDatas set EnName = N'Title' where code = N'IPDMRPE925';
Insert into MasterDatas (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'5. Chuyển viện',N'5. Disposition',N'IPDMRPEKQDTCV',N'IPDMRPEKQDT',N'IPDMRPE',N'2',N'926',N'Radio',N'',N'',N'',N'A01_035_050919_V127', '1');

Update MasterDatas set EnName = N'2. Progression of this pregnancy' where code = N'IPDMRPT800';
Update MasterDatas set EnName = N'Last menstrual period from date:' where code = N'IPDMRPT801';
Update MasterDatas set EnName = N'Last menstrual period from date:' where code = N'IPDMRPT802';
Update MasterDatas set EnName = N'Gestational age' where code = N'IPDMRPT803';
Update MasterDatas set EnName = N'Gestational age' where code = N'IPDMRPT804';
Update MasterDatas set EnName = N'Prenatal check-up at' where code = N'IPDMRPT805';
Update MasterDatas set EnName = N'Prenatal check-up at' where code = N'IPDMRPT806';
Update MasterDatas set EnName = N'Tetanus vaccination' where code = N'IPDMRPT807';
Update MasterDatas set EnName = N'No' where code = N'IPDMRPT808';
Update MasterDatas set EnName = N'Yes' where code = N'IPDMRPT809';
Update MasterDatas set EnName = N'Vaccinated' where code = N'IPDMRPT810';
Update MasterDatas set EnName = N'Labour started at:' where code = N'IPDMRPT811';
Update MasterDatas set EnName = N'Labour started at:' where code = N'IPDMRPT812';
Update MasterDatas set EnName = N'Early signs of labour' where code = N'IPDMRPT813';
Update MasterDatas set EnName = N'Early signs of labour' where code = N'IPDMRPT814';
Update MasterDatas set EnName = N'Progression' where code = N'IPDMRPT815';
Update MasterDatas set EnName = N'Progression' where code = N'IPDMRPT816';
Update MasterDatas set EnName = N'4. Obstetric history' where code = N'IPDMRPT817';
Update MasterDatas set EnName = N'Menstruation started (in year)' where code = N'IPDMRPT818';
Update MasterDatas set EnName = N'Menstruation started (in year)' where code = N'IPDMRPT819';
Update MasterDatas set EnName = N'Menstrual characteristics' where code = N'IPDMRPT820';
Update MasterDatas set EnName = N'Menstrual characteristics' where code = N'IPDMRPT821';
Update MasterDatas set EnName = N'Cycle' where code = N'IPDMRPT822';
Update MasterDatas set EnName = N'Cycle' where code = N'IPDMRPT823';
Update MasterDatas set EnName = N'Period volume' where code = N'IPDMRPT824';
Update MasterDatas set EnName = N'Period volume' where code = N'IPDMRPT825';
Update MasterDatas set EnName = N'Year of marriage' where code = N'IPDMRPT826';
Update MasterDatas set EnName = N'Year of marriage' where code = N'IPDMRPT827';
Update MasterDatas set EnName = N'Previous gynecologic disorders' where code = N'IPDMRPT828';
Update MasterDatas set EnName = N'Previous gynecologic disorders' where code = N'IPDMRPT829';
Update MasterDatas set EnName = N'+ Other organs' where code = N'IPDMRPT830';
Update MasterDatas set EnName = N'+ Other organs' where code = N'IPDMRPT831';
Update MasterDatas set EnName = N'2. External examination' where code = N'IPDMRPT832';
Update MasterDatas set EnName = N'Prior abdominal surgical scar' where code = N'IPDMRPT833';
Update MasterDatas set EnName = N'Yes' where code = N'IPDMRPT834';
Update MasterDatas set EnName = N'No' where code = N'IPDMRPT835';
Update MasterDatas set EnName = N'Uterine shape' where code = N'IPDMRPT836';
Update MasterDatas set EnName = N'Uterine shape' where code = N'IPDMRPT837';
Update MasterDatas set EnName = N'Position' where code = N'IPDMRPT838';
Update MasterDatas set EnName = N'Position' where code = N'IPDMRPT839';
Update MasterDatas set EnName = N'Unterine contractions' where code = N'IPDMRPT840';
Update MasterDatas set EnName = N'Unterine contractions' where code = N'IPDMRPT841';
Update MasterDatas set EnName = N'Abdominal circumference' where code = N'IPDMRPT842';
Update MasterDatas set EnName = N'Abdominal circumference' where code = N'IPDMRPT843';
Update MasterDatas set EnName = N'Uterine height' where code = N'IPDMRPT844';
Update MasterDatas set EnName = N'Uterine height' where code = N'IPDMRPT845';
Update MasterDatas set EnName = N'Fetal heart rate' where code = N'IPDMRPT846';
Update MasterDatas set EnName = N'Fetal heart rate' where code = N'IPDMRPT847';
Update MasterDatas set EnName = N'Breasts' where code = N'IPDMRPT848';
Update MasterDatas set EnName = N'Breasts' where code = N'IPDMRPT849';
Update MasterDatas set EnName = N'3. Vaginal exmination' where code = N'IPDMRPT850';
Update MasterDatas set EnName = N'Bishop index' where code = N'IPDMRPT851';
Update MasterDatas set EnName = N'Bishop index' where code = N'IPDMRPT852';
Update MasterDatas set EnName = N'Vulva' where code = N'IPDMRPT853';
Update MasterDatas set EnName = N'Vulva' where code = N'IPDMRPT854';
Update MasterDatas set EnName = N'Vagina' where code = N'IPDMRPT855';
Update MasterDatas set EnName = N'Vagina' where code = N'IPDMRPT856';
Update MasterDatas set EnName = N'Perineum' where code = N'IPDMRPT857';
Update MasterDatas set EnName = N'Perineum' where code = N'IPDMRPT858';
Update MasterDatas set EnName = N'Cervix' where code = N'IPDMRPT859';
Update MasterDatas set EnName = N'Cervix' where code = N'IPDMRPT860';
Update MasterDatas set EnName = N'Adnexa' where code = N'IPDMRPT861';
Update MasterDatas set EnName = N'Adnexa' where code = N'IPDMRPT862';
Update MasterDatas set EnName = N'Amniotic status' where code = N'IPDMRPT863';
Update MasterDatas set EnName = N'Buldging' where code = N'IPDMRPT864';
Update MasterDatas set EnName = N'Flat' where code = N'IPDMRPT865';
Update MasterDatas set EnName = N'Protruding' where code = N'IPDMRPT866';
Update MasterDatas set EnName = N'Type of ROM' where code = N'IPDMRPT867';
Update MasterDatas set EnName = N'1 Natural ROM' where code = N'IPDMRPT868';
Update MasterDatas set EnName = N'2. AROM' where code = N'IPDMRPT869';
Update MasterDatas set EnName = N'Amniotic fluid color' where code = N'IPDMRPT870';
Update MasterDatas set EnName = N'Amniotic fluid color' where code = N'IPDMRPT871';
Update MasterDatas set EnName = N'Amniotic fluid volume' where code = N'IPDMRPT872';
Update MasterDatas set EnName = N'Amniotic fluid volume' where code = N'IPDMRPT873';
Update MasterDatas set EnName = N'Presentation' where code = N'IPDMRPT874';
Update MasterDatas set EnName = N'Presentation' where code = N'IPDMRPT875';
Update MasterDatas set EnName = N'Position' where code = N'IPDMRPT876';
Update MasterDatas set EnName = N'Position' where code = N'IPDMRPT877';
Update MasterDatas set EnName = N'Types of position' where code = N'IPDMRPT878';
Update MasterDatas set EnName = N'Types of position' where code = N'IPDMRPT879';
Update MasterDatas set EnName = N'Descendent of fetal head' where code = N'IPDMRPT880';
Update MasterDatas set EnName = N'1. Above' where code = N'IPDMRPT881';
Update MasterDatas set EnName = N'2. High' where code = N'IPDMRPT882';
Update MasterDatas set EnName = N'3. Fixed' where code = N'IPDMRPT883';
Update MasterDatas set EnName = N'4. Engaged' where code = N'IPDMRPT884';
Update MasterDatas set EnName = N'Diagonal conjugate diameter' where code = N'IPDMRPT885';
Update MasterDatas set EnName = N'Diagonal conjugate diameter' where code = N'IPDMRPT886';
Update MasterDatas set EnName = N'to date:' where code = N'IPDMRPT887';
Update MasterDatas set EnName = N'to date:' where code = N'IPDMRPT888';
Update MasterDatas set EnName = N'ROM at:' where code = N'IPDMRPT889';
Update MasterDatas set EnName = N'ROM at:' where code = N'IPDMRPT890';


Update MasterDatas set EnName = N'3. Obstetric-gynecological history:' where code = N'IPDMRPT900';
Update MasterDatas set EnName = N'Menstruation started (in year)' where code = N'IPDMRPT901';
Update MasterDatas set EnName = N'Menstruation started (in year)' where code = N'IPDMRPT902';
Update MasterDatas set EnName = N'At age' where code = N'IPDMRPT903';
Update MasterDatas set EnName = N'At age' where code = N'IPDMRPT904';
Update MasterDatas set EnName = N'Menstrual characteristics' where code = N'IPDMRPT905';
Update MasterDatas set EnName = N'Menstrual characteristics' where code = N'IPDMRPT906';
Update MasterDatas set EnName = N'Cycle' where code = N'IPDMRPT907';
Update MasterDatas set EnName = N'Cycle' where code = N'IPDMRPT908';
Update MasterDatas set EnName = N'Length of period (days)' where code = N'IPDMRPT909';
Update MasterDatas set EnName = N'Length of period (days)' where code = N'IPDMRPT910';
Update MasterDatas set EnName = N'Period volume' where code = N'IPDMRPT911';
Update MasterDatas set EnName = N'Period volume' where code = N'IPDMRPT912';
Update MasterDatas set EnName = N'Last menstrual period' where code = N'IPDMRPT913';
Update MasterDatas set EnName = N'Last menstrual period' where code = N'IPDMRPT914';
Update MasterDatas set EnName = N'Abdominal pain' where code = N'IPDMRPT915';
Update MasterDatas set EnName = N'Abdominal pain' where code = N'IPDMRPT916';
Update MasterDatas set EnName = N'1. Before period' where code = N'IPDMRPT917';
Update MasterDatas set EnName = N'2. During period' where code = N'IPDMRPT918';
Update MasterDatas set EnName = N'3. After period' where code = N'IPDMRPT919';
Update MasterDatas set EnName = N'Year of marriage' where code = N'IPDMRPT920';
Update MasterDatas set EnName = N'Year of marriage' where code = N'IPDMRPT921';
Update MasterDatas set EnName = N'At age' where code = N'IPDMRPT922';
Update MasterDatas set EnName = N'Year of menopause' where code = N'IPDMRPT923';
Update MasterDatas set EnName = N'Year of menopause' where code = N'IPDMRPT924';
Update MasterDatas set EnName = N'At age' where code = N'IPDMRPT925';
Update MasterDatas set EnName = N'Previous gynecologic disorders' where code = N'IPDMRPT926';
Update MasterDatas set EnName = N'Previous gynecologic disorders' where code = N'IPDMRPT927';
Update MasterDatas set EnName = N'4. Obstetric history' where code = N'IPDMRPT928';
Update MasterDatas set EnName = N'Skin and mucosa' where code = N'IPDMRPT929';
Update MasterDatas set EnName = N'Lymphatic system' where code = N'IPDMRPT930';
Update MasterDatas set EnName = N'Breasts' where code = N'IPDMRPT931';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPT932';
Update MasterDatas set EnName = N'3. Specialized examination' where code = N'IPDMRPT933';
Update MasterDatas set EnName = N'a. External examination' where code = N'IPDMRPT934';
Update MasterDatas set EnName = N'Secondary sexual characteristics' where code = N'IPDMRPT935';
Update MasterDatas set EnName = N'Labia majora' where code = N'IPDMRPT936';
Update MasterDatas set EnName = N'Labia minora' where code = N'IPDMRPT937';
Update MasterDatas set EnName = N'Clitoris' where code = N'IPDMRPT938';
Update MasterDatas set EnName = N'Vulva' where code = N'IPDMRPT939';
Update MasterDatas set EnName = N'Hymen' where code = N'IPDMRPT940';
Update MasterDatas set EnName = N'Perineum' where code = N'IPDMRPT941';
Update MasterDatas set EnName = N'b. Vaginal exmination' where code = N'IPDMRPT942';
Update MasterDatas set EnName = N'Body of uterus' where code = N'IPDMRPT943';
Update MasterDatas set EnName = N'Body of uterus' where code = N'IPDMRPT944';
Update MasterDatas set EnName = N'Pouches' where code = N'IPDMRPT945';
Update MasterDatas set EnName = N'Pouches' where code = N'IPDMRPT946';
Update MasterDatas set EnName = N'4. Para-clinical laboratory tests to do' where code = N'IPDMRPT947';
Update MasterDatas set EnName = N'4. Para-clinical laboratory tests to do' where code = N'IPDMRPT948';
Update MasterDatas set EnName = N'Time' where code = N'IPDMRPT949';
Update MasterDatas set EnName = N'1. Circulatory system' where code = N'IPDMRPTTTYT2';

Update MasterDatas set EnName = N'Bảng phẫu thuật' where code = N'IPDPHUTBL1';
Update MasterDatas set EnName = N'Hour, date' where code = N'IPDPHUTBL2';
Update MasterDatas set EnName = N'Surgical/Anesthesia methods' where code = N'IPDPHUTBL3';
Update MasterDatas set EnName = N'Surgeon' where code = N'IPDPHUTBL4';
Update MasterDatas set EnName = N'Anesthesiologist' where code = N'IPDPHUTBL5';


Update MasterDatas set EnName = N'Father’s full name' where code = N'IPDMRPO56';
Update MasterDatas set EnName = N'Father’s full name' where code = N'IPDMRPO57';
Update MasterDatas set EnName = N'Father’s educational level' where code = N'IPDMRPO58';
Update MasterDatas set EnName = N'Father’s educational level' where code = N'IPDMRPO59';
Update MasterDatas set EnName = N'Father’s occupation' where code = N'IPDMRPO60';
Update MasterDatas set EnName = N'Father’s occupation' where code = N'IPDMRPO61';
Update MasterDatas set EnName = N'Mother’s full name' where code = N'IPDMRPO62';
Update MasterDatas set EnName = N'Mother’s full name' where code = N'IPDMRPO63';
Update MasterDatas set EnName = N'Mother’s educational level' where code = N'IPDMRPO64';
Update MasterDatas set EnName = N'Mother’s educational level' where code = N'IPDMRPO65';
Update MasterDatas set EnName = N'Mother’s occupation' where code = N'IPDMRPO66';
Update MasterDatas set EnName = N'Mother’s occupation' where code = N'IPDMRPO67';

Update MasterDatas set EnName = N'+ Allergy' where code = N'IPDMRPT01';
Update MasterDatas set EnName = N'+ Allergy' where code = N'IPDMRPT02';
Update MasterDatas set EnName = N'Thông tin khai thác tiền sử bệnh' where code = N'IPDMRPT03';
Update MasterDatas set EnName = N'Thông tin khai thác các thuốc đã dùng trên hệ thống' where code = N'IPDMRPT04';
Update MasterDatas set EnName = N'3. Child development:' where code = N'IPDMRPT05';
Update MasterDatas set EnName = N'- The child is' where code = N'IPDMRPT06';
Update MasterDatas set EnName = N'- The child is' where code = N'IPDMRPT07';
Update MasterDatas set EnName = N'- History of pregnancy (Para)' where code = N'IPDMRPT08';
Update MasterDatas set EnName = N'Full-term' where code = N'IPDMRPT09';
Update MasterDatas set EnName = N'Full-term' where code = N'IPDMRPT10';
Update MasterDatas set EnName = N'Pre-term' where code = N'IPDMRPT11';
Update MasterDatas set EnName = N'Pre-term' where code = N'IPDMRPT12';
Update MasterDatas set EnName = N'Misscarriage (Suction, D&E)' where code = N'IPDMRPT13';
Update MasterDatas set EnName = N'Misscarriage (Suction, D&E)' where code = N'IPDMRPT14';
Update MasterDatas set EnName = N'Alive' where code = N'IPDMRPT15';
Update MasterDatas set EnName = N'Alive' where code = N'IPDMRPT16';
Update MasterDatas set EnName = N'-Condition at birth:' where code = N'IPDMRPT17';
Update MasterDatas set EnName = N'1. Normal' where code = N'IPDMRPT18';
Update MasterDatas set EnName = N'2.Forceps' where code = N'IPDMRPT19';
Update MasterDatas set EnName = N'3. Vacuum' where code = N'IPDMRPT20';
Update MasterDatas set EnName = N'4. C-section' where code = N'IPDMRPT21';
Update MasterDatas set EnName = N'5. Elective' where code = N'IPDMRPT22';
Update MasterDatas set EnName = N'6. Others' where code = N'IPDMRPT23';
Update MasterDatas set EnName = N'6. Others' where code = N'IPDMRPT24';
Update MasterDatas set EnName = N'- Weight at birth:' where code = N'IPDMRPT25';
Update MasterDatas set EnName = N'- Weight at birth:' where code = N'IPDMRPT26';
Update MasterDatas set EnName = N'- Congenital anomalies:' where code = N'IPDMRPT27';
Update MasterDatas set EnName = N'Yes' where code = N'IPDMRPT28';
Update MasterDatas set EnName = N'No' where code = N'IPDMRPT29';
Update MasterDatas set EnName = N'- Congenital anomalies:' where code = N'IPDMRPT30';
Update MasterDatas set EnName = N'- Mental development abnormality' where code = N'IPDMRPT31';
Update MasterDatas set EnName = N'- Mental development abnormality' where code = N'IPDMRPT32';
Update MasterDatas set EnName = N'- Motor development abnormality' where code = N'IPDMRPT33';
Update MasterDatas set EnName = N'- Motor development abnormality' where code = N'IPDMRPT34';
Update MasterDatas set EnName = N'- Other diseases' where code = N'IPDMRPT35';
Update MasterDatas set EnName = N'- Other diseases' where code = N'IPDMRPT36';
Update MasterDatas set EnName = N'- Nourishment' where code = N'IPDMRPT37';
Update MasterDatas set EnName = N'1. Breast milk' where code = N'IPDMRPT38';
Update MasterDatas set EnName = N'2. Formula milk' where code = N'IPDMRPT39';
Update MasterDatas set EnName = N'3. Mixed' where code = N'IPDMRPT40';
Update MasterDatas set EnName = N'- Weaning at:' where code = N'IPDMRPT41';
Update MasterDatas set EnName = N'- Weaning at:' where code = N'IPDMRPT42';
Update MasterDatas set EnName = N'- Child care' where code = N'IPDMRPT43';
Update MasterDatas set EnName = N'1. At kindergarten' where code = N'IPDMRPT44';
Update MasterDatas set EnName = N'2. At home' where code = N'IPDMRPT45';
Update MasterDatas set EnName = N'- Vaccinated' where code = N'IPDMRPT46';
Update MasterDatas set EnName = N'1. Tuberculosis' where code = N'IPDMRPT47';
Update MasterDatas set EnName = N'2. Poliomyelitis' where code = N'IPDMRPT48';
Update MasterDatas set EnName = N'3. Measles' where code = N'IPDMRPT49';
Update MasterDatas set EnName = N'4. Pertussis' where code = N'IPDMRPT50';
Update MasterDatas set EnName = N'5. Tetanus' where code = N'IPDMRPT51';
Update MasterDatas set EnName = N'6. Diphtheria' where code = N'IPDMRPT52';
Update MasterDatas set EnName = N'7. Other vaccination' where code = N'IPDMRPT53';
Update MasterDatas set EnName = N'- Other vaccinations:' where code = N'IPDMRPT54';

Update MasterDatas set EnName = N'2. Clinical evolution' where code = N'IPDMRPT1050';
Update MasterDatas set EnName = N'Onset of disease' where code = N'IPDMRPT1051';
Update MasterDatas set EnName = N'Onset of disease' where code = N'IPDMRPT1052';
Update MasterDatas set EnName = N'Causes (if any)' where code = N'IPDMRPT1053';
Update MasterDatas set EnName = N'Causes (if any)' where code = N'IPDMRPT1054';
Update MasterDatas set EnName = N'Treatment methods received' where code = N'IPDMRPT1055';
Update MasterDatas set EnName = N'Treatment methods received' where code = N'IPDMRPT1056';
Update MasterDatas set EnName = N'Eye condition' where code = N'IPDMRPT1057';
Update MasterDatas set EnName = N'Eye condition' where code = N'IPDMRPT1058';
Update MasterDatas set EnName = N'Eye condition' where code = N'IPDMRPT1059';
Update MasterDatas set EnName = N'Eye condition' where code = N'IPDMRPT1060';
Update MasterDatas set EnName = N'General condition' where code = N'IPDMRPT1061';
Update MasterDatas set EnName = N'General condition' where code = N'IPDMRPT1062';
Update MasterDatas set EnName = N'4.1 Eye examination' where code = N'IPDMRPT1063';
Update MasterDatas set EnName = N'1. Visual acuity' where code = N'IPDMRPT1064';
Update MasterDatas set EnName = N'2. IOP' where code = N'IPDMRPT1065';
Update MasterDatas set EnName = N'3. Strabismus and eye movement' where code = N'IPDMRPT1066';
Update MasterDatas set EnName = N'4. Nasolacrimal duct   ' where code = N'IPDMRPT1067';
Update MasterDatas set EnName = N'5. Eyelid' where code = N'IPDMRPT1068';
Update MasterDatas set EnName = N'6. Conjunctiva' where code = N'IPDMRPT1069';
Update MasterDatas set EnName = N'7. Cornea' where code = N'IPDMRPT1070';
Update MasterDatas set EnName = N'8. Sclera' where code = N'IPDMRPT1071';
Update MasterDatas set EnName = N'9. Anterior chamber (anterior chamber angle)' where code = N'IPDMRPT1072';
Update MasterDatas set EnName = N'10. Iris' where code = N'IPDMRPT1073';
Update MasterDatas set EnName = N'11. Pupil' where code = N'IPDMRPT1074';
Update MasterDatas set EnName = N'12. Crystalline lens' where code = N'IPDMRPT1075';
Update MasterDatas set EnName = N'13. Vitreous body' where code = N'IPDMRPT1076';
Update MasterDatas set EnName = N'14. Fundus' where code = N'IPDMRPT1077';
Update MasterDatas set EnName = N'15. Orbit' where code = N'IPDMRPT1078';
Update MasterDatas set EnName = N'Unaided' where code = N'IPDMRPTR1079';
Update MasterDatas set EnName = N'Unaided' where code = N'IPDMRPTR1080';
Update MasterDatas set EnName = N'Pinhole' where code = N'IPDMRPTR1081';
Update MasterDatas set EnName = N'Pinhole' where code = N'IPDMRPTR1082';
Update MasterDatas set EnName = N'Aided' where code = N'IPDMRPTR1083';
Update MasterDatas set EnName = N'Aided' where code = N'IPDMRPTR1084';
Update MasterDatas set EnName = N'Near vision' where code = N'IPDMRPTR1085';
Update MasterDatas set EnName = N'Near vision' where code = N'IPDMRPTR1086';
Update MasterDatas set EnName = N'IOP' where code = N'IPDMRPTR1087';
Update MasterDatas set EnName = N'IOP' where code = N'IPDMRPTR1088';
Update MasterDatas set EnName = N'Strabismus and eye movement' where code = N'IPDMRPTR1089';
Update MasterDatas set EnName = N'Strabismus and eye movement' where code = N'IPDMRPTR1090';
Update MasterDatas set EnName = N'Lacrimal irrigation' where code = N'IPDMRPTR1091';
Update MasterDatas set EnName = N'Good drainage' where code = N'IPDMRPTR1092';
Update MasterDatas set EnName = N'Trào' where code = N'IPDMRPTR1093';
Update MasterDatas set EnName = N'Fluid refluxes through the opposite canaliculus' where code = N'IPDMRPTR1094';
Update MasterDatas set EnName = N'Refluxes through the same canaliculus' where code = N'IPDMRPTR1095';
Update MasterDatas set EnName = N'Eyelid' where code = N'IPDMRPTR1096';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1097';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTR1098';
Update MasterDatas set EnName = N'Chalazion' where code = N'IPDMRPTR1099';
Update MasterDatas set EnName = N'Stye' where code = N'IPDMRPTR1100';
Update MasterDatas set EnName = N'Eyelid skin scar' where code = N'IPDMRPTR1101';
Update MasterDatas set EnName = N'Blepharoptosis' where code = N'IPDMRPTR1102';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPTR1103';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPTR1104';
Update MasterDatas set EnName = N'Entropion' where code = N'IPDMRPTR1105';
Update MasterDatas set EnName = N'Lagophthalmos' where code = N'IPDMRPTR1106';
Update MasterDatas set EnName = N'Ectropion' where code = N'IPDMRPTR1107';
Update MasterDatas set EnName = N'Blepharitis (eyelash root)' where code = N'IPDMRPTR1108';
Update MasterDatas set EnName = N'Eyelid tumor' where code = N'IPDMRPTR1109';
Update MasterDatas set EnName = N'Eyelid tumor' where code = N'IPDMRPTR1110';
Update MasterDatas set EnName = N'Properties of tumor' where code = N'IPDMRPTR1111';
Update MasterDatas set EnName = N'Location' where code = N'IPDMRPTR1112';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTR1113';
Update MasterDatas set EnName = N'Meibominal gland' where code = N'IPDMRPTR1114';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1115';
Update MasterDatas set EnName = N'Mild obstruction' where code = N'IPDMRPTR1116';
Update MasterDatas set EnName = N'Moderate' where code = N'IPDMRPTR1117';
Update MasterDatas set EnName = N'Severe' where code = N'IPDMRPTR1118';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1119';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1120';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1121';
Update MasterDatas set EnName = N'Congestion' where code = N'IPDMRPTR1122';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTR1123';
Update MasterDatas set EnName = N'Marginal' where code = N'IPDMRPTR1124';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTR1125';
Update MasterDatas set EnName = N'Hemorrhage' where code = N'IPDMRPTR1126';
Update MasterDatas set EnName = N'Keratotis' where code = N'IPDMRPTR1127';
Update MasterDatas set EnName = N'Papillae' where code = N'IPDMRPTR1128';
Update MasterDatas set EnName = N'Granuloma' where code = N'IPDMRPTR1129';
Update MasterDatas set EnName = N'Scar' where code = N'IPDMRPTR1130';
Update MasterDatas set EnName = N'Conjunctival tumor' where code = N'IPDMRPTR1131';
Update MasterDatas set EnName = N'Conjunctival tumor' where code = N'IPDMRPTR1132';
Update MasterDatas set EnName = N'Properties' where code = N'IPDMRPTR1133';
Update MasterDatas set EnName = N'Location' where code = N'IPDMRPTR1134';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTR1135';
Update MasterDatas set EnName = N'Fornix' where code = N'IPDMRPTR1136';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1137';
Update MasterDatas set EnName = N'Shallow' where code = N'IPDMRPTR1138';
Update MasterDatas set EnName = N'Adhesive' where code = N'IPDMRPTR1139';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1140';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1141';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1142';
Update MasterDatas set EnName = N'Hình vẽ giác mạc' where code = N'IPDMRPTR1143';
Update MasterDatas set EnName = N'Hình vẽ' where code = N'IPDMRPTR1144';
Update MasterDatas set EnName = N'Upload' where code = N'IPDMRPTR1145';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTR1146';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1147';
Update MasterDatas set EnName = N'Large' where code = N'IPDMRPTR1148';
Update MasterDatas set EnName = N'Small' where code = N'IPDMRPTR1149';
Update MasterDatas set EnName = N'Shape' where code = N'IPDMRPTR1150';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1151';
Update MasterDatas set EnName = N'Conical' where code = N'IPDMRPTR1152';
Update MasterDatas set EnName = N'Globular' where code = N'IPDMRPTR1153';
Update MasterDatas set EnName = N'Epithelium' where code = N'IPDMRPTR1154';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1155';
Update MasterDatas set EnName = N'Punctate lesions' where code = N'IPDMRPTR1156';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1157';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1158';
Update MasterDatas set EnName = N'Bullous epithelial edema' where code = N'IPDMRPTR1159';
Update MasterDatas set EnName = N'Mild' where code = N'IPDMRPTR1160';
Update MasterDatas set EnName = N'Moderate' where code = N'IPDMRPTR1161';
Update MasterDatas set EnName = N'Severe' where code = N'IPDMRPTR1162';
Update MasterDatas set EnName = N'Margins of lesion' where code = N'IPDMRPTR1163';
Update MasterDatas set EnName = N'Ragged' where code = N'IPDMRPTR1164';
Update MasterDatas set EnName = N'Smooth' where code = N'IPDMRPTR1165';
Update MasterDatas set EnName = N'Grooved' where code = N'IPDMRPTR1166';
Update MasterDatas set EnName = N'Thoái hoá' where code = N'IPDMRPTR1167';
Update MasterDatas set EnName = N'Band keratopathy' where code = N'IPDMRPTR1168';
Update MasterDatas set EnName = N'Drug-related corneal deposits' where code = N'IPDMRPTR1169';
Update MasterDatas set EnName = N'Stroma' where code = N'IPDMRPTR1170';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1171';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTR1172';
Update MasterDatas set EnName = N'Infiltration' where code = N'IPDMRPTR1173';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1174';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1175';
Update MasterDatas set EnName = N'Stroma' where code = N'IPDMRPTR1176';
Update MasterDatas set EnName = N'Superficial' where code = N'IPDMRPTR1177';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTR1178';
Update MasterDatas set EnName = N'Very deep' where code = N'IPDMRPTR1179';
Update MasterDatas set EnName = N'Stroma' where code = N'IPDMRPTR1180';
Update MasterDatas set EnName = N'Local' where code = N'IPDMRPTR1181';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTR1182';
Update MasterDatas set EnName = N'Multiple satellite foci' where code = N'IPDMRPTR1183';
Update MasterDatas set EnName = N'Endothelium&Descemet' where code = N'IPDMRPTR1184';
Update MasterDatas set EnName = N'Fold' where code = N'IPDMRPTR1185';
Update MasterDatas set EnName = N'Pigmented precipitates in posterior surface of the cornea' where code = N'IPDMRPTR1186';
Update MasterDatas set EnName = N'Pus in posterior surface of the cornea' where code = N'IPDMRPTR1187';
Update MasterDatas set EnName = N'Exudates in posterior surface' where code = N'IPDMRPTR1188';
Update MasterDatas set EnName = N'Guttata' where code = N'IPDMRPTR1189';
Update MasterDatas set EnName = N'Descemet membrane stretching' where code = N'IPDMRPTR1190';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1191';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1192';
Update MasterDatas set EnName = N'Endothelium&Descemet' where code = N'IPDMRPTR1193';
Update MasterDatas set EnName = N'Threatened perforation' where code = N'IPDMRPTR1194';
Update MasterDatas set EnName = N'Iris incarceration' where code = N'IPDMRPTR1195';
Update MasterDatas set EnName = N'Corneal perforation' where code = N'IPDMRPTR1196';
Update MasterDatas set EnName = N'Corneal perforation box' where code = N'IPDMRPTR1197';
Update MasterDatas set EnName = N'Central' where code = N'IPDMRPTR1198';
Update MasterDatas set EnName = N'Paracentral' where code = N'IPDMRPTR1199';
Update MasterDatas set EnName = N'Marginal' where code = N'IPDMRPTR1200';
Update MasterDatas set EnName = N'Endothelium&Descemet Corneal perforation' where code = N'IPDMRPTR1201';
Update MasterDatas set EnName = N'Seidel' where code = N'IPDMRPTR1202';
Update MasterDatas set EnName = N'Perforation diameter' where code = N'IPDMRPTR1203';
Update MasterDatas set EnName = N'Perforation diameter' where code = N'IPDMRPTR1204';
Update MasterDatas set EnName = N'Self-sealed perforation' where code = N'IPDMRPTR1205';
Update MasterDatas set EnName = N'Corneal reflex' where code = N'IPDMRPTR1206';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTR1207';
Update MasterDatas set EnName = N'Reduced' where code = N'IPDMRPTR1208';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1209';
Update MasterDatas set EnName = N'Neovascularization' where code = N'IPDMRPTR1210';
Update MasterDatas set EnName = N'Superficial, afferent' where code = N'IPDMRPTR1211';
Update MasterDatas set EnName = N'Centrifugal' where code = N'IPDMRPTR1212';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTR1213';
Update MasterDatas set EnName = N'Limbus' where code = N'IPDMRPTR1214';
Update MasterDatas set EnName = N'Age-related degeneration' where code = N'IPDMRPTR1215';
Update MasterDatas set EnName = N'Calcium deposits' where code = N'IPDMRPTR1216';
Update MasterDatas set EnName = N'Other abnormalities' where code = N'IPDMRPTR1217';
Update MasterDatas set EnName = N'Other abnormalities' where code = N'IPDMRPTR1218';
Update MasterDatas set EnName = N'Other abnormalities' where code = N'IPDMRPTR1219';
Update MasterDatas set EnName = N'Sclera' where code = N'IPDMRPTR1220';
Update MasterDatas set EnName = N'Inflamation' where code = N'IPDMRPTR1221';
Update MasterDatas set EnName = N'Episcleritis' where code = N'IPDMRPTR1222';
Update MasterDatas set EnName = N'Staphyloma' where code = N'IPDMRPTR1223';
Update MasterDatas set EnName = N'Thinning' where code = N'IPDMRPTR1224';
Update MasterDatas set EnName = N'Necrosis' where code = N'IPDMRPTR1225';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTR1226';
Update MasterDatas set EnName = N'Củng mạc Viêm' where code = N'IPDMRPTR1227';
Update MasterDatas set EnName = N'Nodular' where code = N'IPDMRPTR1228';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTR1229';
Update MasterDatas set EnName = N'Abscess' where code = N'IPDMRPTR1230';
Update MasterDatas set EnName = N'Superficial' where code = N'IPDMRPTR1231';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTR1232';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1233';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1234';
Update MasterDatas set EnName = N'Shallow / absent / deep' where code = N'IPDMRPTR1235';
Update MasterDatas set EnName = N'Shallow' where code = N'IPDMRPTR1236';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTR1237';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTR1238';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1239';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1240';
Update MasterDatas set EnName = N'Anterior chamber ' where code = N'IPDMRPTR1241';
Update MasterDatas set EnName = N'Anterior chamber ' where code = N'IPDMRPTR1242';
Update MasterDatas set EnName = N'Pus' where code = N'IPDMRPTR1243';
Update MasterDatas set EnName = N'Pus' where code = N'IPDMRPTR1244';
Update MasterDatas set EnName = N'Pus' where code = N'IPDMRPTR1245';
Update MasterDatas set EnName = N'Blood' where code = N'IPDMRPTR1246';
Update MasterDatas set EnName = N'Blood' where code = N'IPDMRPTR1247';
Update MasterDatas set EnName = N'Blood' where code = N'IPDMRPTR1248';
Update MasterDatas set EnName = N'Tyndal(+)' where code = N'IPDMRPTR1249';
Update MasterDatas set EnName = N'Tyndal(+)' where code = N'IPDMRPTR1250';
Update MasterDatas set EnName = N'Exudative membrane' where code = N'IPDMRPTR1251';
Update MasterDatas set EnName = N'Exudative membrane' where code = N'IPDMRPTR1252';
Update MasterDatas set EnName = N'Hình vẽ / Ảnh' where code = N'IPDMRPTR1253';
Update MasterDatas set EnName = N'Hình vẽ / Ảnh' where code = N'IPDMRPTR1254';
Update MasterDatas set EnName = N'Hình vẽ / Ảnh' where code = N'IPDMRPTR1255';
Update MasterDatas set EnName = N'Iris' where code = N'IPDMRPTR1256';
Update MasterDatas set EnName = N'Spongy' where code = N'IPDMRPTR1257';
Update MasterDatas set EnName = N'Atrophic' where code = N'IPDMRPTR1258';
Update MasterDatas set EnName = N'Congestive' where code = N'IPDMRPTR1259';
Update MasterDatas set EnName = N'Neovascularization' where code = N'IPDMRPTR1260';
Update MasterDatas set EnName = N'Prolapse' where code = N'IPDMRPTR1261';
Update MasterDatas set EnName = N'Incarceration' where code = N'IPDMRPTR1262';
Update MasterDatas set EnName = N'Diameter' where code = N'IPDMRPTR1263';
Update MasterDatas set EnName = N'Diameter' where code = N'IPDMRPTR1264';
Update MasterDatas set EnName = N'Pupil' where code = N'IPDMRPTR1265';
Update MasterDatas set EnName = N'Round' where code = N'IPDMRPTR1266';
Update MasterDatas set EnName = N'Distorted' where code = N'IPDMRPTR1267';
Update MasterDatas set EnName = N'Adhesive' where code = N'IPDMRPTR1268';
Update MasterDatas set EnName = N'Adhesive location' where code = N'IPDMRPTR1269';
Update MasterDatas set EnName = N'Light reflex' where code = N'IPDMRPTR1270';
Update MasterDatas set EnName = N'Good' where code = N'IPDMRPTR1271';
Update MasterDatas set EnName = N'Poor' where code = N'IPDMRPTR1272';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTR1273';
Update MasterDatas set EnName = N'Red reflex' where code = N'IPDMRPTR1274';
Update MasterDatas set EnName = N'Pink' where code = N'IPDMRPTR1275';
Update MasterDatas set EnName = N'Grey' where code = N'IPDMRPTR1276';
Update MasterDatas set EnName = N'Unable to see' where code = N'IPDMRPTR1277';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1278';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1279';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1280';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1281';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1282';
Update MasterDatas set EnName = N'Cataracts' where code = N'IPDMRPTR1283';
Update MasterDatas set EnName = N'Cataracts' where code = N'IPDMRPTR1284';
Update MasterDatas set EnName = N'Morphological type of cataracts' where code = N'IPDMRPTR1285';
Update MasterDatas set EnName = N'Deviated' where code = N'IPDMRPTR1286';
Update MasterDatas set EnName = N'Deviated' where code = N'IPDMRPTR1287';
Update MasterDatas set EnName = N'IOL' where code = N'IPDMRPTR1288';
Update MasterDatas set EnName = N'IOL' where code = N'IPDMRPTR1289';
Update MasterDatas set EnName = N'Well-positioned' where code = N'IPDMRPTR1290';
Update MasterDatas set EnName = N'Deviated' where code = N'IPDMRPTR1291';
Update MasterDatas set EnName = N'Posterior capsular opacification' where code = N'IPDMRPTR1292';
Update MasterDatas set EnName = N'ACIOL' where code = N'IPDMRPTR1293';
Update MasterDatas set EnName = N'PCIOL' where code = N'IPDMRPTR1294';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1295';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1296';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1297';
Update MasterDatas set EnName = N'Vitreous body' where code = N'IPDMRPTR1298';
Update MasterDatas set EnName = N'Clean' where code = N'IPDMRPTR1299';
Update MasterDatas set EnName = N'Hazy' where code = N'IPDMRPTR1300';
Update MasterDatas set EnName = N'Hemorrhage' where code = N'IPDMRPTR1301';
Update MasterDatas set EnName = N'Suppurative inflammation' where code = N'IPDMRPTR1302';
Update MasterDatas set EnName = N'Suppurative inflammation' where code = N'IPDMRPTR1303';
Update MasterDatas set EnName = N'Vitreous body' where code = N'IPDMRPTR1304';
Update MasterDatas set EnName = N'Hemorrhage' where code = N'IPDMRPTR1305';
Update MasterDatas set EnName = N'Turbidity' where code = N'IPDMRPTR1306';
Update MasterDatas set EnName = N'Posterior vitreous detachment' where code = N'IPDMRPTR1307';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1308';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1309';
Update MasterDatas set EnName = N'Optic disc' where code = N'IPDMRPTR1310';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1311';
Update MasterDatas set EnName = N'Optic disc cupping' where code = N'IPDMRPTR1312';
Update MasterDatas set EnName = N'C/D' where code = N'IPDMRPTR1313';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTR1314';
Update MasterDatas set EnName = N'Atrophic' where code = N'IPDMRPTR1315';
Update MasterDatas set EnName = N'Pale' where code = N'IPDMRPTR1316';
Update MasterDatas set EnName = N'Macula' where code = N'IPDMRPTR1317';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1318';
Update MasterDatas set EnName = N'Absent reflex of macula' where code = N'IPDMRPTR1319';
Update MasterDatas set EnName = N'Macular scar' where code = N'IPDMRPTR1320';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTR1321';
Update MasterDatas set EnName = N'Macula' where code = N'IPDMRPTR1322';
Update MasterDatas set EnName = N'Local' where code = N'IPDMRPTR1323';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTR1324';
Update MasterDatas set EnName = N'Retina' where code = N'IPDMRPTR1325';
Update MasterDatas set EnName = N'Vessel system' where code = N'IPDMRPTR1326';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1327';
Update MasterDatas set EnName = N'Retinal artery occlusion' where code = N'IPDMRPTR1328';
Update MasterDatas set EnName = N'Retinal vein occlusion' where code = N'IPDMRPTR1329';
Update MasterDatas set EnName = N'Neovascularization' where code = N'IPDMRPTR1330';
Update MasterDatas set EnName = N'Retinal degeneration' where code = N'IPDMRPTR1331';
Update MasterDatas set EnName = N'Võng mạc Thoái hoá VM:' where code = N'IPDMRPTR1332';
Update MasterDatas set EnName = N'Peripheral' where code = N'IPDMRPTR1333';
Update MasterDatas set EnName = N'Central' where code = N'IPDMRPTR1334';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTR1335';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTR1336';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTR1337';
Update MasterDatas set EnName = N'Orbit' where code = N'IPDMRPTR1338';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1339';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPTR1340';
Update MasterDatas set EnName = N'Description' where code = N'IPDMRPTR1341';
Update MasterDatas set EnName = N'Unaided' where code = N'IPDMRPTL1079';
Update MasterDatas set EnName = N'Unaided' where code = N'IPDMRPTL1080';
Update MasterDatas set EnName = N'Pinhole' where code = N'IPDMRPTL1081';
Update MasterDatas set EnName = N'Pinhole' where code = N'IPDMRPTL1082';
Update MasterDatas set EnName = N'Aided' where code = N'IPDMRPTL1083';
Update MasterDatas set EnName = N'Aided' where code = N'IPDMRPTL1084';
Update MasterDatas set EnName = N'Near vision' where code = N'IPDMRPTL1085';
Update MasterDatas set EnName = N'Near vision' where code = N'IPDMRPTL1086';
Update MasterDatas set EnName = N'IOP' where code = N'IPDMRPTL1087';
Update MasterDatas set EnName = N'IOP' where code = N'IPDMRPTL1088';
Update MasterDatas set EnName = N'Strabismus and eye movement' where code = N'IPDMRPTL1089';
Update MasterDatas set EnName = N'Strabismus and eye movement' where code = N'IPDMRPTL1090';
Update MasterDatas set EnName = N'Lacrimal irrigation' where code = N'IPDMRPTL1091';
Update MasterDatas set EnName = N'Good drainage' where code = N'IPDMRPTL1092';
Update MasterDatas set EnName = N'Trào' where code = N'IPDMRPTL1093';
Update MasterDatas set EnName = N'Fluid refluxes through the opposite canaliculus' where code = N'IPDMRPTL1094';
Update MasterDatas set EnName = N'Refluxes through the same canaliculus' where code = N'IPDMRPTL1095';
Update MasterDatas set EnName = N'Eyelid' where code = N'IPDMRPTL1096';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1097';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTL1098';
Update MasterDatas set EnName = N'Chalazion' where code = N'IPDMRPTL1099';
Update MasterDatas set EnName = N'Stye' where code = N'IPDMRPTL1100';
Update MasterDatas set EnName = N'Eyelid skin scar' where code = N'IPDMRPTL1101';
Update MasterDatas set EnName = N'Blepharoptosis' where code = N'IPDMRPTL1102';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPTL1103';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPTL1104';
Update MasterDatas set EnName = N'Entropion' where code = N'IPDMRPTL1105';
Update MasterDatas set EnName = N'Lagophthalmos' where code = N'IPDMRPTL1106';
Update MasterDatas set EnName = N'Ectropion' where code = N'IPDMRPTL1107';
Update MasterDatas set EnName = N'Blepharitis (eyelash root)' where code = N'IPDMRPTL1108';
Update MasterDatas set EnName = N'Eyelid tumor' where code = N'IPDMRPTL1109';
Update MasterDatas set EnName = N'Eyelid tumor' where code = N'IPDMRPTL1110';
Update MasterDatas set EnName = N'Properties of tumor' where code = N'IPDMRPTL1111';
Update MasterDatas set EnName = N'Location' where code = N'IPDMRPTL1112';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTL1113';
Update MasterDatas set EnName = N'Meibominal gland' where code = N'IPDMRPTL1114';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1115';
Update MasterDatas set EnName = N'Mild obstruction' where code = N'IPDMRPTL1116';
Update MasterDatas set EnName = N'Moderate' where code = N'IPDMRPTL1117';
Update MasterDatas set EnName = N'Severe' where code = N'IPDMRPTL1118';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1119';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1120';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1121';
Update MasterDatas set EnName = N'Congestion' where code = N'IPDMRPTL1122';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTL1123';
Update MasterDatas set EnName = N'Marginal' where code = N'IPDMRPTL1124';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTL1125';
Update MasterDatas set EnName = N'Hemorrhage' where code = N'IPDMRPTL1126';
Update MasterDatas set EnName = N'Keratotis' where code = N'IPDMRPTL1127';
Update MasterDatas set EnName = N'Papillae' where code = N'IPDMRPTL1128';
Update MasterDatas set EnName = N'Granuloma' where code = N'IPDMRPTL1129';
Update MasterDatas set EnName = N'Scar' where code = N'IPDMRPTL1130';
Update MasterDatas set EnName = N'Conjunctival tumor' where code = N'IPDMRPTL1131';
Update MasterDatas set EnName = N'Conjunctival tumor' where code = N'IPDMRPTL1132';
Update MasterDatas set EnName = N'Properties' where code = N'IPDMRPTL1133';
Update MasterDatas set EnName = N'Location' where code = N'IPDMRPTL1134';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTL1135';
Update MasterDatas set EnName = N'Fornix' where code = N'IPDMRPTL1136';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1137';
Update MasterDatas set EnName = N'Shallow' where code = N'IPDMRPTL1138';
Update MasterDatas set EnName = N'Adhesive' where code = N'IPDMRPTL1139';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1140';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1141';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1142';
Update MasterDatas set EnName = N'Hình vẽ giác mạc' where code = N'IPDMRPTL1143';
Update MasterDatas set EnName = N'Hình vẽ' where code = N'IPDMRPTL1144';
Update MasterDatas set EnName = N'Upload' where code = N'IPDMRPTL1145';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTL1146';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1147';
Update MasterDatas set EnName = N'Large' where code = N'IPDMRPTL1148';
Update MasterDatas set EnName = N'Small' where code = N'IPDMRPTL1149';
Update MasterDatas set EnName = N'Shape' where code = N'IPDMRPTL1150';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1151';
Update MasterDatas set EnName = N'Conical' where code = N'IPDMRPTL1152';
Update MasterDatas set EnName = N'Globular' where code = N'IPDMRPTL1153';
Update MasterDatas set EnName = N'Epithelium' where code = N'IPDMRPTL1154';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1155';
Update MasterDatas set EnName = N'Punctate lesions' where code = N'IPDMRPTL1156';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1157';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1158';
Update MasterDatas set EnName = N'Bullous epithelial edema' where code = N'IPDMRPTL1159';
Update MasterDatas set EnName = N'Mild' where code = N'IPDMRPTL1160';
Update MasterDatas set EnName = N'Moderate' where code = N'IPDMRPTL1161';
Update MasterDatas set EnName = N'Severe' where code = N'IPDMRPTL1162';
Update MasterDatas set EnName = N'Margins of lesion' where code = N'IPDMRPTL1163';
Update MasterDatas set EnName = N'Ragged' where code = N'IPDMRPTL1164';
Update MasterDatas set EnName = N'Smooth' where code = N'IPDMRPTL1165';
Update MasterDatas set EnName = N'Grooved' where code = N'IPDMRPTL1166';
Update MasterDatas set EnName = N'Thoái hoá' where code = N'IPDMRPTL1167';
Update MasterDatas set EnName = N'Band keratopathy' where code = N'IPDMRPTL1168';
Update MasterDatas set EnName = N'Drug-related corneal deposits' where code = N'IPDMRPTL1169';
Update MasterDatas set EnName = N'Stroma' where code = N'IPDMRPTL1170';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1171';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTL1172';
Update MasterDatas set EnName = N'Infiltration' where code = N'IPDMRPTL1173';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1174';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1175';
Update MasterDatas set EnName = N'Stroma' where code = N'IPDMRPTL1176';
Update MasterDatas set EnName = N'Superficial' where code = N'IPDMRPTL1177';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTL1178';
Update MasterDatas set EnName = N'Very deep' where code = N'IPDMRPTL1179';
Update MasterDatas set EnName = N'Stroma' where code = N'IPDMRPTL1180';
Update MasterDatas set EnName = N'Local' where code = N'IPDMRPTL1181';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTL1182';
Update MasterDatas set EnName = N'Multiple satellite foci' where code = N'IPDMRPTL1183';
Update MasterDatas set EnName = N'Endothelium&Descemet' where code = N'IPDMRPTL1184';
Update MasterDatas set EnName = N'Fold' where code = N'IPDMRPTL1185';
Update MasterDatas set EnName = N'Pigmented precipitates in posterior surface of the cornea' where code = N'IPDMRPTL1186';
Update MasterDatas set EnName = N'Pus in posterior surface of the cornea' where code = N'IPDMRPTL1187';
Update MasterDatas set EnName = N'Exudates in posterior surface' where code = N'IPDMRPTL1188';
Update MasterDatas set EnName = N'Guttata' where code = N'IPDMRPTL1189';
Update MasterDatas set EnName = N'Descemet membrane stretching' where code = N'IPDMRPTL1190';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1191';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1192';
Update MasterDatas set EnName = N'Endothelium&Descemet' where code = N'IPDMRPTL1193';
Update MasterDatas set EnName = N'Threatened perforation' where code = N'IPDMRPTL1194';
Update MasterDatas set EnName = N'Iris incarceration' where code = N'IPDMRPTL1195';
Update MasterDatas set EnName = N'Corneal perforation' where code = N'IPDMRPTL1196';
Update MasterDatas set EnName = N'Corneal perforation box' where code = N'IPDMRPTL1197';
Update MasterDatas set EnName = N'Central' where code = N'IPDMRPTL1198';
Update MasterDatas set EnName = N'Paracentral' where code = N'IPDMRPTL1199';
Update MasterDatas set EnName = N'Marginal' where code = N'IPDMRPTL1200';
Update MasterDatas set EnName = N'Endothelium&Descemet Corneal perforation' where code = N'IPDMRPTL1201';
Update MasterDatas set EnName = N'Seidel' where code = N'IPDMRPTL1202';
Update MasterDatas set EnName = N'Perforation diameter' where code = N'IPDMRPTL1203';
Update MasterDatas set EnName = N'Perforation diameter' where code = N'IPDMRPTL1204';
Update MasterDatas set EnName = N'Self-sealed perforation' where code = N'IPDMRPTL1205';
Update MasterDatas set EnName = N'Corneal reflex' where code = N'IPDMRPTL1206';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTL1207';
Update MasterDatas set EnName = N'Reduced' where code = N'IPDMRPTL1208';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1209';
Update MasterDatas set EnName = N'Neovascularization' where code = N'IPDMRPTL1210';
Update MasterDatas set EnName = N'Superficial, afferent' where code = N'IPDMRPTL1211';
Update MasterDatas set EnName = N'Centrifugal' where code = N'IPDMRPTL1212';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTL1213';
Update MasterDatas set EnName = N'Limbus' where code = N'IPDMRPTL1214';
Update MasterDatas set EnName = N'Age-related degeneration' where code = N'IPDMRPTL1215';
Update MasterDatas set EnName = N'Calcium deposits' where code = N'IPDMRPTL1216';
Update MasterDatas set EnName = N'Other abnormalities' where code = N'IPDMRPTL1217';
Update MasterDatas set EnName = N'Other abnormalities' where code = N'IPDMRPTL1218';
Update MasterDatas set EnName = N'Other abnormalities' where code = N'IPDMRPTL1219';
Update MasterDatas set EnName = N'Sclera' where code = N'IPDMRPTL1220';
Update MasterDatas set EnName = N'Inflamation' where code = N'IPDMRPTL1221';
Update MasterDatas set EnName = N'Episcleritis' where code = N'IPDMRPTL1222';
Update MasterDatas set EnName = N'Staphyloma' where code = N'IPDMRPTL1223';
Update MasterDatas set EnName = N'Thinning' where code = N'IPDMRPTL1224';
Update MasterDatas set EnName = N'Necrosis' where code = N'IPDMRPTL1225';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTL1226';
Update MasterDatas set EnName = N'Củng mạc Viêm' where code = N'IPDMRPTL1227';
Update MasterDatas set EnName = N'Nodular' where code = N'IPDMRPTL1228';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTL1229';
Update MasterDatas set EnName = N'Abscess' where code = N'IPDMRPTL1230';
Update MasterDatas set EnName = N'Superficial' where code = N'IPDMRPTL1231';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTL1232';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1233';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1234';
Update MasterDatas set EnName = N'Shallow / absent / deep' where code = N'IPDMRPTL1235';
Update MasterDatas set EnName = N'Shallow' where code = N'IPDMRPTL1236';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTL1237';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTL1238';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1239';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1240';
Update MasterDatas set EnName = N'Anterior chamber ' where code = N'IPDMRPTL1241';
Update MasterDatas set EnName = N'Anterior chamber ' where code = N'IPDMRPTL1242';
Update MasterDatas set EnName = N'Pus' where code = N'IPDMRPTL1243';
Update MasterDatas set EnName = N'Pus' where code = N'IPDMRPTL1244';
Update MasterDatas set EnName = N'Pus' where code = N'IPDMRPTL1245';
Update MasterDatas set EnName = N'Blood' where code = N'IPDMRPTL1246';
Update MasterDatas set EnName = N'Blood' where code = N'IPDMRPTL1247';
Update MasterDatas set EnName = N'Blood' where code = N'IPDMRPTL1248';
Update MasterDatas set EnName = N'Tyndal(+)' where code = N'IPDMRPTL1249';
Update MasterDatas set EnName = N'Tyndal(+)' where code = N'IPDMRPTL1250';
Update MasterDatas set EnName = N'Exudative membrane' where code = N'IPDMRPTL1251';
Update MasterDatas set EnName = N'Exudative membrane' where code = N'IPDMRPTL1252';
Update MasterDatas set EnName = N'Hình vẽ / Ảnh' where code = N'IPDMRPTL1253';
Update MasterDatas set EnName = N'Hình vẽ / Ảnh' where code = N'IPDMRPTL1254';
Update MasterDatas set EnName = N'Hình vẽ / Ảnh' where code = N'IPDMRPTL1255';
Update MasterDatas set EnName = N'Iris' where code = N'IPDMRPTL1256';
Update MasterDatas set EnName = N'Spongy' where code = N'IPDMRPTL1257';
Update MasterDatas set EnName = N'Atrophic' where code = N'IPDMRPTL1258';
Update MasterDatas set EnName = N'Congestive' where code = N'IPDMRPTL1259';
Update MasterDatas set EnName = N'Neovascularization' where code = N'IPDMRPTL1260';
Update MasterDatas set EnName = N'Prolapse' where code = N'IPDMRPTL1261';
Update MasterDatas set EnName = N'Incarceration' where code = N'IPDMRPTL1262';
Update MasterDatas set EnName = N'Diameter' where code = N'IPDMRPTL1263';
Update MasterDatas set EnName = N'Diameter' where code = N'IPDMRPTL1264';
Update MasterDatas set EnName = N'Pupil' where code = N'IPDMRPTL1265';
Update MasterDatas set EnName = N'Round' where code = N'IPDMRPTL1266';
Update MasterDatas set EnName = N'Distorted' where code = N'IPDMRPTL1267';
Update MasterDatas set EnName = N'Adhesive' where code = N'IPDMRPTL1268';
Update MasterDatas set EnName = N'Adhesive location' where code = N'IPDMRPTL1269';
Update MasterDatas set EnName = N'Light reflex' where code = N'IPDMRPTL1270';
Update MasterDatas set EnName = N'Good' where code = N'IPDMRPTL1271';
Update MasterDatas set EnName = N'Poor' where code = N'IPDMRPTL1272';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTL1273';
Update MasterDatas set EnName = N'Red reflex' where code = N'IPDMRPTL1274';
Update MasterDatas set EnName = N'Pink' where code = N'IPDMRPTL1275';
Update MasterDatas set EnName = N'Grey' where code = N'IPDMRPTL1276';
Update MasterDatas set EnName = N'Unable to see' where code = N'IPDMRPTL1277';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1278';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1279';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1280';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1281';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1282';
Update MasterDatas set EnName = N'Cataracts' where code = N'IPDMRPTL1283';
Update MasterDatas set EnName = N'Cataracts' where code = N'IPDMRPTL1284';
Update MasterDatas set EnName = N'Morphological type of cataracts' where code = N'IPDMRPTL1285';
Update MasterDatas set EnName = N'Deviated' where code = N'IPDMRPTL1286';
Update MasterDatas set EnName = N'Deviated' where code = N'IPDMRPTL1287';
Update MasterDatas set EnName = N'IOL' where code = N'IPDMRPTL1288';
Update MasterDatas set EnName = N'IOL' where code = N'IPDMRPTL1289';
Update MasterDatas set EnName = N'Well-positioned' where code = N'IPDMRPTL1290';
Update MasterDatas set EnName = N'Deviated' where code = N'IPDMRPTL1291';
Update MasterDatas set EnName = N'Posterior capsular opacification' where code = N'IPDMRPTL1292';
Update MasterDatas set EnName = N'ACIOL' where code = N'IPDMRPTL1293';
Update MasterDatas set EnName = N'PCIOL' where code = N'IPDMRPTL1294';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1295';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1296';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1297';
Update MasterDatas set EnName = N'Vitreous body' where code = N'IPDMRPTL1298';
Update MasterDatas set EnName = N'Clean' where code = N'IPDMRPTL1299';
Update MasterDatas set EnName = N'Hazy' where code = N'IPDMRPTL1300';
Update MasterDatas set EnName = N'Hemorrhage' where code = N'IPDMRPTL1301';
Update MasterDatas set EnName = N'Suppurative inflammation' where code = N'IPDMRPTL1302';
Update MasterDatas set EnName = N'Suppurative inflammation' where code = N'IPDMRPTL1303';
Update MasterDatas set EnName = N'Vitreous body' where code = N'IPDMRPTL1304';
Update MasterDatas set EnName = N'Hemorrhage' where code = N'IPDMRPTL1305';
Update MasterDatas set EnName = N'Turbidity' where code = N'IPDMRPTL1306';
Update MasterDatas set EnName = N'Posterior vitreous detachment' where code = N'IPDMRPTL1307';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1308';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1309';
Update MasterDatas set EnName = N'Optic disc' where code = N'IPDMRPTL1310';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1311';
Update MasterDatas set EnName = N'Optic disc cupping' where code = N'IPDMRPTL1312';
Update MasterDatas set EnName = N'C/D' where code = N'IPDMRPTL1313';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTL1314';
Update MasterDatas set EnName = N'Atrophic' where code = N'IPDMRPTL1315';
Update MasterDatas set EnName = N'Pale' where code = N'IPDMRPTL1316';
Update MasterDatas set EnName = N'Macula' where code = N'IPDMRPTL1317';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1318';
Update MasterDatas set EnName = N'Absent reflex of macula' where code = N'IPDMRPTL1319';
Update MasterDatas set EnName = N'Macular scar' where code = N'IPDMRPTL1320';
Update MasterDatas set EnName = N'Edema' where code = N'IPDMRPTL1321';
Update MasterDatas set EnName = N'Macula' where code = N'IPDMRPTL1322';
Update MasterDatas set EnName = N'Local' where code = N'IPDMRPTL1323';
Update MasterDatas set EnName = N'Diffuse' where code = N'IPDMRPTL1324';
Update MasterDatas set EnName = N'Retina' where code = N'IPDMRPTL1325';
Update MasterDatas set EnName = N'Vessel system' where code = N'IPDMRPTL1326';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1327';
Update MasterDatas set EnName = N'Retinal artery occlusion' where code = N'IPDMRPTL1328';
Update MasterDatas set EnName = N'Retinal vein occlusion' where code = N'IPDMRPTL1329';
Update MasterDatas set EnName = N'Neovascularization' where code = N'IPDMRPTL1330';
Update MasterDatas set EnName = N'Retinal degeneration' where code = N'IPDMRPTL1331';
Update MasterDatas set EnName = N'Võng mạc Thoái hoá VM:' where code = N'IPDMRPTL1332';
Update MasterDatas set EnName = N'Peripheral' where code = N'IPDMRPTL1333';
Update MasterDatas set EnName = N'Central' where code = N'IPDMRPTL1334';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTL1335';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTL1336';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTL1337';
Update MasterDatas set EnName = N'Orbit' where code = N'IPDMRPTL1338';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1339';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPTL1340';
Update MasterDatas set EnName = N'Description' where code = N'IPDMRPTL1341';
Update MasterDatas set EnName = N'4.2 Full body medical examination' where code = N'IPDMRPT1605';
Update MasterDatas set EnName = N'Blood pressure' where code = N'IPDMRPT1606';
Update MasterDatas set EnName = N'Blood pressure' where code = N'IPDMRPT1607';
Update MasterDatas set EnName = N'Temperature' where code = N'IPDMRPT1608';
Update MasterDatas set EnName = N'Temperature' where code = N'IPDMRPT1609';
Update MasterDatas set EnName = N'Pulse' where code = N'IPDMRPT1610';
Update MasterDatas set EnName = N'Pulse' where code = N'IPDMRPT1611';
Update MasterDatas set EnName = N'Endocrinology' where code = N'IPDMRPT1612';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPT1613';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1614';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1615';
Update MasterDatas set EnName = N'Mentality,neurology' where code = N'IPDMRPT1616';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPT1617';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1618';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1619';
Update MasterDatas set EnName = N'Circulation' where code = N'IPDMRPT1620';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPT1621';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1622';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1623';
Update MasterDatas set EnName = N'Respiration' where code = N'IPDMRPT1624';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPT1625';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1626';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1627';
Update MasterDatas set EnName = N'Digestion' where code = N'IPDMRPT1628';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPT1629';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1630';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1631';
Update MasterDatas set EnName = N'Musculoskeletal system' where code = N'IPDMRPT1632';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPT1633';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1634';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1635';
Update MasterDatas set EnName = N'Urology, genitals' where code = N'IPDMRPT1636';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPT1637';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1638';
Update MasterDatas set EnName = N'Pathologic' where code = N'IPDMRPT1639';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPT1640';
Update MasterDatas set EnName = N'Others' where code = N'IPDMRPT1641';
Update MasterDatas set EnName = N'7. Prognosis' where code = N'IPDMRPT1642';
Update MasterDatas set EnName = N'7. Prognosis' where code = N'IPDMRPT1643';
Update MasterDatas set EnName = N'General condition' where code = N'IPDMRPT1644';
Update MasterDatas set EnName = N'General condition' where code = N'IPDMRPT1645';
Update MasterDatas set EnName = N'8. Treatment plan' where code = N'IPDMRPT1646';
Update MasterDatas set EnName = N'8. Treatment plan' where code = N'IPDMRPT1647';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTR1648';
Update MasterDatas set EnName = N'Other findings' where code = N'IPDMRPTL1648';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1650';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1651';
Update MasterDatas set EnName = N'Shallow' where code = N'IPDMRPTR1652';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTR1653';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTR1654';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1655';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1650';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1651';
Update MasterDatas set EnName = N'Shallow' where code = N'IPDMRPTL1652';
Update MasterDatas set EnName = N'Absent' where code = N'IPDMRPTL1653';
Update MasterDatas set EnName = N'Deep' where code = N'IPDMRPTL1654';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1655';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTR1662';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1663';
Update MasterDatas set EnName = N'Large' where code = N'IPDMRPTR1664';
Update MasterDatas set EnName = N'Small' where code = N'IPDMRPTR1665';
Update MasterDatas set EnName = N'Shape' where code = N'IPDMRPTR1666';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTR1667';
Update MasterDatas set EnName = N'Conical' where code = N'IPDMRPTR1668';
Update MasterDatas set EnName = N'Globular' where code = N'IPDMRPTR1669';
Update MasterDatas set EnName = N'Size' where code = N'IPDMRPTL1662';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1663';
Update MasterDatas set EnName = N'Large' where code = N'IPDMRPTL1664';
Update MasterDatas set EnName = N'Small' where code = N'IPDMRPTL1665';
Update MasterDatas set EnName = N'Shape' where code = N'IPDMRPTL1666';
Update MasterDatas set EnName = N'Normal' where code = N'IPDMRPTL1667';
Update MasterDatas set EnName = N'Conical' where code = N'IPDMRPTL1668';
Update MasterDatas set EnName = N'Globular' where code = N'IPDMRPTL1669';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTR1678';
Update MasterDatas set EnName = N'Other lesions' where code = N'IPDMRPTL1678';


Update MasterDatas set EnName = N'3. Primary diagnosis' where code = N'IPDMRPE1050';
Update MasterDatas set EnName = N'+ Clinical' where code = N'IPDMRPE1051';
Update MasterDatas set EnName = N'+ Clinical' where code = N'IPDMRPE1052';
Update MasterDatas set EnName = N'+ Cause' where code = N'IPDMRPE1053';
Update MasterDatas set EnName = N'+ Cause' where code = N'IPDMRPE1054';
Update MasterDatas set EnName = N'4. Treatment process' where code = N'IPDMRPE1055';
Update MasterDatas set EnName = N'+ Medicine treatment' where code = N'IPDMRPE1056';
Update MasterDatas set EnName = N'+ Medicine treatment' where code = N'IPDMRPE1057';
Update MasterDatas set EnName = N'+ Surgical treatment' where code = N'IPDMRPE1058';
Update MasterDatas set EnName = N'+ Outcome' where code = N'IPDMRPE1059';
Update MasterDatas set EnName = N'+ Outcome' where code = N'IPDMRPE1060';
Update MasterDatas set EnName = N'+ Complications/sequelae' where code = N'IPDMRPE1061';
Update MasterDatas set EnName = N'+ Complications/sequelae' where code = N'IPDMRPE1062';
Update MasterDatas set EnName = N'+ Next treatment plan' where code = N'IPDMRPE1063';
Update MasterDatas set EnName = N'+ Next treatment plan' where code = N'IPDMRPE1064';


Update MasterDatas set EnName = N'Surgical treatment' where code = N'IPDMATTBL1';
Update MasterDatas set EnName = N'Date of surgery' where code = N'IPDMATTBL2';
Update MasterDatas set EnName = N'Surgical methods' where code = N'IPDMATTBL3';
Update MasterDatas set EnName = N'Surgeon' where code = N'IPDMATTBL4';
Update MasterDatas set EnName = N'Created At' where code = N'IPDMATTBL5';












