-- Update Setup bệnh án biểu mẫu
update MasterDatas set DataType = 'BENHAN', Level = 2 where [Group] = 'MedicalRecords' and 
Form in('A01_036_050919_V', 'A01_196_050919_V', 'A01_037_050919_V', 'A01_041_050919_V', 'A01_038_050919_V', 'A01_039_050919_V', 'A01_195_050919_V', 'A01_040_050919_V', 'A01_034_050919_V', 'A01_035_050919_V')

update MasterDatas set DataType = 'Label', Level = 1 where [Group] = 'MedicalRecords' and Note = 'IPD' and Form in ('IPDBAICU', 'BMTIMMACH')

update MasterDatas set DataType = 'PromissoryNote', Level = 3, [Group] = 'A01_037_050919_V' where [Group] = 'PromissoryNote' and Form = 'A02_014_220321_VE'

update MasterDatas set DataType = 'PromissoryNote', Level = 3, [Group] = 'A01_038_050919_V' where Form = 'A02_015_220321_VE'

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu trẻ nội trú nhi',N'Initial Assessment For Pediatric Inpatient',N'InitialAssessmentForPediatricInPatient',N'A01_034_050919_V',N'A02_014_220321_VE',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thang điểm HUMPTY DUMPTY đánh giá nguy cơ ngã ở trẻ em',N'Thang điểm HUMPTY DUMPTY đánh giá nguy cơ ngã ở trẻ em',N'A02_047_301220_VE',N'A01_037_050919_V',N'A02_047_301220_VE',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thang điểm HUMPTY DUMPTY đánh giá nguy cơ ngã ở trẻ em',N'Thang điểm HUMPTY DUMPTY đánh giá nguy cơ ngã ở trẻ em',N'A02_047_301220_VE',N'A01_195_050919_V',N'A02_047_301220_VE',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng điểm GLAMORGAN sàng lọc loét do tỳ ép ở trẻ nhi và sơ sinh',N'Glamorgan pressure injury screening tool',N'A02_066_050919_VE',N'A01_037_050919_V',N'A02_066_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng điểm GLAMORGAN sàng lọc loét do tỳ ép ở trẻ nhi và sơ sinh',N'Glamorgan pressure injury screening tool',N'A02_066_050919_VE',N'A01_038_050919_V',N'A02_066_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng điểm GLAMORGAN sàng lọc loét do tỳ ép ở trẻ nhi và sơ sinh',N'Glamorgan pressure injury screening tool',N'A02_066_050919_VE',N'A01_195_050919_V',N'A02_066_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)',N'A02_036_080322_V',N'A01_037_050919_V',N'A02_036_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)',N'A02_036_080322_V',N'A01_195_050919_V',N'A02_036_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 3 tháng tuổi)',N'A02_036_080322_V',N'A01_034_050919_V',N'A02_036_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 3 đến 12 tháng tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 3 đến 12 tháng tuổi)',N'A02_035_080322_V',N'A01_037_050919_V',N'A02_035_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 3 đến 12 tháng tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 3 đến 12 tháng tuổi)',N'A02_035_080322_V',N'A01_195_050919_V',N'A02_035_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 3 đến 12 tháng tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 3 đến 12 tháng tuổi)',N'A02_035_080322_V',N'A01_034_050919_V',N'A02_035_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 4 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 4 tuổi)',N'A02_034_080322_V',N'A01_037_050919_V',N'A02_034_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 4 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 4 tuổi)',N'A02_034_080322_V',N'A01_195_050919_V',N'A02_034_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 4 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 1 đến dưới 4 tuổi)',N'A02_034_080322_V',N'A01_034_050919_V',N'A02_034_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 4 đến 12 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 4 đến 12 tuổi)',N'A02_033_080322_V',N'A01_037_050919_V',N'A02_033_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 4 đến 12 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 4 đến 12 tuổi)',N'A02_033_080322_V',N'A01_195_050919_V',N'A02_033_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 4 đến 12 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Từ 4 đến 12 tuổi)',N'A02_033_080322_V',N'A01_034_050919_V',N'A02_033_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Trên 12 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Trên 12 tuổi)',N'A02_032_080322_V',N'A01_037_050919_V',N'A02_032_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Trên 12 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Trên 12 tuổi)',N'A02_032_080322_V',N'A01_195_050919_V',N'A02_032_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi DHST dành cho trẻ nhi (Trên 12 tuổi)',N'Bảng theo dõi DHST dành cho trẻ nhi (Trên 12 tuổi)',N'A02_032_080322_V',N'A01_034_050919_V',N'A02_032_080322_V',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ thuyên tắc mạch (BN nội khoa)',N'Đánh giá nguy cơ thuyên tắc mạch (BN nội khoa)',N'IPDTRFA',N'A01_034_050919_V',N'IPDTRFA',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ thuyên tắc mạch (BN nội khoa)',N'Đánh giá nguy cơ thuyên tắc mạch (BN nội khoa)',N'IPDTRFA',N'BMTIMMACH',N'IPDTRFA',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ sơ sinh',N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ sơ sinh',N'IPDNOC',N'A01_038_050919_V',N'IPDNOC',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu cho trẻ vừa sinh',N'Đánh giá ban đầu cho trẻ vừa sinh',N'A02_016_050919_VE',N'A01_035_050919_V',N'A02_016_050919_VE',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu cho trẻ vừa sinh',N'Đánh giá ban đầu cho trẻ vừa sinh',N'A02_016_050919_VE',N'A01_038_050919_V',N'A02_016_050919_VE',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ĐGBĐ sản phụ chuyển dạ',N'ĐGBĐ sản phụ chuyển dạ',N'A02_069_080121_VE',N'A01_035_050919_V',N'A02_069_080121_VE',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho sản phụ',N'Bảng theo dõi dấu hiệu sinh tồn dành cho sản phụ',N'VSFPW',N'A01_035_050919_V',N'VSFPW',N'3',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xin lấy bánh rau không theo quy định',N'Xin lấy bánh rau không theo quy định',N'A01_159_050919_VE',N'A01_035_050919_V',N'A01_159_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án ngoại khoa',N'The surgical medical record',N'TheSurgicalMedicalRecord',N'BMTIMMACH',N'A01_195_050919_V',N'2',N'0',N'BENHAN',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ thuyên tắc mạch ngoại khoa',N'Đánh giá nguy cơ thuyên tắc mạch ngoại khoa',N'A01_049_050919_VE',N'A01_195_050919_V',N'A01_049_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ thuyên tắc mạch ngoại khoa',N'Đánh giá nguy cơ thuyên tắc mạch ngoại khoa',N'A01_049_050919_VE',N'BMTIMMACH',N'A01_049_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Yêu cầu người bệnh chuẩn bị trước khi phẫu thuật thủ thuật',N'Yêu cầu người bệnh chuẩn bị trước khi phẫu thuật thủ thuật',N'A02_052_050919_V',N'A01_195_050919_V',N'A02_052_050919_V',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu theo dõi người bệnh thoát mạch thuốc điều trị ung thư',N'Phiếu theo dõi người bệnh thoát mạch thuốc điều trị ung thư',N'A02_041_050919_V',N'A01_196_050919_V',N'A02_041_050919_V',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tóm tắt thủ thuật can thiệp động mạch vành',N'Tóm tắt thủ thuật can thiệp động mạch vành',N'A01_076_050919_VE',N'BMTIMMACH',N'A01_076_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi nhận thực hiện thuốc standing order',N'Ghi nhận thực hiện thuốc standing order',N'A03_029_050919_VE',N'BMTIMMACH',N'A03_029_050919_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'PROM bệnh nhân mạch vành',N'PROM bệnh nhân mạch vành',N'PROMFCD',N'BMTIMMACH',N'PROMFCD',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'PROM bệnh nhân suy tim',N'PROM bệnh nhân suy tim',N'PROMFHF',N'BMTIMMACH',N'PROMFHF',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án tim mạch',N'Cardiology medical record for inpatient',N'CardiovascularForm',N'BMTIMMACH',N'BMTIMMACH',N'2',N'0',N'BENHAN',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án nội khoa',N'The General Internal Medical Record',N'MedicalRecord',N'IPDBAICU',N'A01_034_050919_V',N'2',N'0',N'BENHAN',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá tình trạng trẻ trong 2 giờ sau sinh',N'Assessment of infant status during the first 2 hours of extrauterine life',N'A02_016_061022_VE',N'A01_035_050919_V',N'A02_016_061022_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');

-- Mở khóa XN BCYT ra viện IPD
Insert Into Forms(Id, CreatedAt, UpdatedAt, IsDeleted, Name, Code, VisitTypeGroupCode)Values(NEWID(), GETDATE(), GETDATE(), 0, N'Báo cáo y tế ra viện', 'A01_143_290922_VE', 'IPD')

-- Update form code DGBD + sàng lọc ngã 

update Forms set Code = 'OPD_A02_007_220321_VE' where Code = 'A02_007_220321_VE' and VisitTypeGroupCode = 'OPD'
update Forms set Code = 'ED_A02_007_220321_VE' where Code = 'A02_007_220321_VE' and VisitTypeGroupCode = 'ED'
update Forms set Code = 'EOC_A02_007_220321_VE' where Code = 'A02_007_220321_VE' and VisitTypeGroupCode = 'EOC'
update Forms set Code = 'EOC_A02_007_080121_VE' where Code = 'A02_007_080121_VE' and VisitTypeGroupCode = 'EOC'
update Forms set Code = 'OPD_A02_007_080121_VE' where Code = 'A02_007_080121_VE' and VisitTypeGroupCode = 'OPD'

-- Update masterdata 
update MasterDatas set Code = 'A03_030_290321_VE', Form = 'A03_030_290321_VE', ViName = N'Phiếu ghi nhân thuốc y lệnh miệng', EnName = 'Verbal Order Form' where Code = 'A03_029_050919_VE' and Form = 'A03_029_050919_VE'

-- thêm BA phụ khoa + thai chết lưu trong BA sản
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu',N'Report Coordinating with the patient/ family to deal with a stillbirth',N'A01_152_100122_VE',N'A01_035_050919_V',N'A01_152_100122_VE',N'2',N'0',N'PromissoryNote',N'IPD',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án phụ khoa',N'Medical Record GyNecological',N'MedicalRecordGynecological',N'A01_035_050919_V',N'A01_036_050919_V',N'2',N'0',N'BENHAN',N'IPD',N'',N'',N'', '1');
