insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD] [VIEW] Thông tin khách hàng đánh giá nguy cơ ung thư' , N'RISKASSFORCANCERGET', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD] [BS CHỈNH SỬA] Thông tin khách hàng đánh giá nguy cơ ung thư ' , N'RISKASSFORCANCERPOST', (select id from VisitTypeGroups where Code = 'OPD'));


INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'Thông tin khách hàng đánh giá nguy cơ ung thư', 'A03_115_200520_V', 'OPD')

 INSERT INTO AppConfigs(Id,[Key],[Label],[Value],IsDeleted) VALUES (newid(),'IS_SEND_MAIL_APPOINTMENT',N'Có cho phép gửi mail thông báo Ngày hẹn trả KQ cho bác sĩ','YES', 0)
 INSERT INTO AppConfigs(Id,[Key],[Label],[Value],IsDeleted) VALUES (newid(),'SUBJECT_SEND_MAIL_APPOINTMENT',N'Nhắc hẹn trả kết quả cho khách hàng/ Remind about test results to patients',N'Nhắc hẹn trả kết quả cho khách hàng/ Remind about test results to patients',0)
 INSERT INTO AppConfigs(Id,[Key],[Label],[Value],IsDeleted) VALUES (newid(),'BODY_SEND_MAIL_APPOINTMENT',N'<!DOCTYPE html> <html> <head> <meta charset="UTF-8"> </head> <body> <div> <table style="width:100%;border:1px solid black;border-collapse: collapse;"> <tr  style="border:1px solid black"> <th style="text-align:center">NỘI DUNG</th> <th style="text-align:center">CONTENT</th> </tr> <tr> <td style="border:1px solid black;padding: 0px 12px 12px 12px;width:50%"> <p><b><i>Kính gửi BS {FullNameDoctor},</i></b><br/><br/> Kết quả CLS của KH {CustomerName} - PID {PID}- khám ngày {TimeNT} đã có trên hệ thống.<br/> KH sẽ được nhắc lịch để được tư vấn KQ, Bác sĩ vui lòng thực hiện:<br/> &nbsp;&nbsp;&nbsp;&nbsp;- Gọi điện thoại cho khách hàng tư vấn kết quả và follow up quá trình điều trị.<br/> &nbsp;&nbsp;&nbsp;&nbsp;- Tư vấn cho KH nhận KQ qua My Vinmec/ email hoặc bản cứng nếu cần thiết. Thông tin tới HC khoa về việc KH yêu cầu email/ bản cứng KQ cho KH nếu có yêu cầu.<br/> &nbsp;&nbsp;&nbsp;&nbsp;- BS ghi nhận vào HSBA/ eForm về thời gian đã tư vấn KQ cho KH và các vấn đề liên quan.<br/> Kính đề nghị BS thực hiện đầy đủ để đảm bảo việc trả KQ CLS cho KH, tránh việc gián đoạn trong điều trị, gia tăng hiệu quả trải nghiệm dịch vụ KH tại  Vinmec.<br/> <br/> <i style="display: inherit;">Đây là email nhắc việc tự động, anh chị vui lòng không trả lời lại email này.</i> <br/> Trân trọng, <br/></p> </td> <td style="border:1px solid black;padding: 0px 12px 12px 12px;width:50%"> <p><b><i>Dear Dr {FullNameDoctor},</i></b><br/><br/> The ancillary results of {CustomerName} - PID {PID} - examined on {TimeNT} has been updated on the system.<br/> The patient will be sent a reminder about date & time of consultation. Please follow the instruction:<br/> &nbsp;&nbsp;&nbsp;&nbsp;- Call the patient to consult them about the result and the follow up treatment process.<br/> &nbsp;&nbsp;&nbsp;&nbsp;- Inform the patient about methods to receive their results: via My Vinmec/email or the result report paper if necessary; contact the administrative team of the Department for an email/result report paper if the patient has such request.<br/> &nbsp;&nbsp;&nbsp;&nbsp;- Fill in time/date that the patients have been contacted for consultation and related information in the patients’ medical reports/eForm.<br/> Please follow the above instruction to ensure the return of results to the patient, avoid interruption in treatment, and increase the patients’ satisfaction in experiencing Vinmec International Hospital’s services.<br/> <br/> <i style="display: inherit;">This is an automatically generated email. Please do not reply to this email.</i> <br/> Sincerely, <br/></p> </td> </tr> <tbody> </div> </body> </html>')
