insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD/IPD] [BS CHỈNH SỬA] Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu' , N'STILLBIRTHPOST', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD/IPD] [VIEW] Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu' , N'STILLBIRTHGET', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD/IPD] [XÁC NHẬN] Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu' , N'STILLBIRTHCFPOST', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD/IPD] [BS CHỈNH SỬA] Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu' , N'STILLBIRTHPOST', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD/IPD] [VIEW] Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu' , N'STILLBIRTHGET', (select id from VisitTypeGroups where Code = 'OPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[OPD/IPD] [XÁC NHẬN] Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu' , N'STILLBIRTHCFPOST', (select id from VisitTypeGroups where Code = 'OPD'));
INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'Biên bản phối hợp với bệnh nhân, gia đình xử lý thai chết lưu', 'A01_152_100122_VE', 'IPD')
INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'Biên bản phối hợp với bệnh nhân, gia đình xử lý thai chết lưu', 'A01_152_100122_VE', 'OPD')
INSERT INTO AppConfigs(Id,[Key],[Label],[Value],IsDeleted) VALUES (newid(),'STILL_BIRTH_CODE',N'Đây là Mã khoa ở Prod/ check SpecialtyNo','15,197,202,64,201,213,184',0)
 