-- Khu ED Update Version 2 xét nghiệm tại chỗ masterdata
INSERT INTO EDPointOfCareTestingMasterDatas(Id, Form, [Order], Name, HigherLimit, LowerLimit, HigherAlert, LowerAlert, Unit, IsDeleted)
VALUES(NEWID(), 'A03_038_080322_V', 1, 'pH', 7.45, 7.35, 7.60, 7.20, '', 0)
,(NEWID(), 'A03_038_080322_V', 2, 'pCO2', 45, 35, 70, 20, 'mmHg', 0)
,(NEWID(), 'A03_038_080322_V', 3, 'pO2', 105, 80, NULL, 45, 'mmHg', 0)
,(NEWID(), 'A03_038_080322_V', 4, 'BE', 3, -2, NULL, NULL, 'mmol/L', 0)
,(NEWID(), 'A03_038_080322_V', 5, 'HCO3', 26, 22, NULL, NULL, 'mmol/L', 0)
,(NEWID(), 'A03_038_080322_V', 6, 'TCO2', 27, 23, NULL, NULL, 'mmol/L', 0)
,(NEWID(), 'A03_038_080322_V', 7, 'SO2', 98, 95, NULL, NULL, '%', 0)
,(NEWID(), 'A03_038_080322_V', 8, 'Lactat', 1.25, 0.36, NULL, NULL, 'mmol/L', 0)

--Định thời gian dùng version 2 xét nghiệm tại chỗ
INSERT INTO AppConfigs(Id, [Key], [Label], [Value], IsDeleted)
VALUES(NEWID(), 'UPDATE_VERSION2_A03_038_080322_V', N'Cập nhật tính năng mới cho Xét nghiệm tại chỗ - Khí máu Cartridge CG4 với các bệnh nhân được tiếp sau khi deploy', FORMAT(GETDATE(), 'yyyy/MM/dd HH:mm tt zzz'), 0)

-- Khu IPD thêm mới xét nghiệm tại chỗ
-- PHÂN QUYỀN
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][XEM] Xét nghiệm tại chỗ - Khí máu Cartridge CG4' , N'XEMXNTC', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][SỬA] Xét nghiệm tại chỗ - Khí máu Cartridge CG4' , N'SUAXNTC', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Tạo Mới] Xét nghiệm tại chỗ - Khí máu Cartridge CG4' , N'TAOXNTC', (select id from VisitTypeGroups where Code = 'IPD'));
insert into Actions  (Id, CreatedAt, UpdatedAt, IsDeleted, Name , Code, VisitTypeGroupId) values (NEWID(), GETDATE(), GETDATE(), 'False',N'[IPD][Xác Nhận] Xét nghiệm tại chỗ - Khí máu Cartridge CG4' , N'XACNHANXNTC', (select id from VisitTypeGroups where Code = 'IPD'));

-- UNLOCK FORM xet nghiệm tại chỗ
INSERT INTO Forms(Id, CreatedAt, UpdatedAt, [Name], Code, VisitTypeGroupCode, IsDeleted)
VALUES(NEWID(),GETDATE(),GETDATE(),N'Xét nghiệm tại chỗ - Khí máu Cartridge CG4','A03_038_080322_V','IPD', 0)

-- thời gian update tóm tắt động mạch vành version 2 
INSERT INTO AppConfigs(Id, [Key], [Label], [Value], IsDeleted)
VALUES(NEWID(), 'UPDATE_VERSION2_A01_076_290422_VE', N'Cập nhật tính năng mới cho phiếu tóm tắt thủ thuật can thiệp động mạch vành với các bệnh nhân được tiếp sau khi deploy', FORMAT(GETDATE(), 'yyyy/MM/dd HH:mm tt zzz'), 0)
-- Đổi tên mạch vành
update Forms set Name = N'Tóm tắt thủ thuật can thiệp động mạch vành'
where Code = 'A01_076_050919_VE'

--Set up Benh an ICU
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án ICU',N'Bệnh án ICU',N'IPDBAICU',N'MedicalRecords',N'IPDBAICU',N'',N'',N'',N'IPD',N'',N'',N'', '');

--phieu du tru mau dat version 1 de ban update sau dat versoin 2
update EIOBloodRequestSupplyAndConfirmations set Version = 1


-- Nhom HSBA
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Nhóm biểu mẫu',N'IPD Nhóm biểu mẫu',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Bệnh án hội chẩn',N'IPD Bệnh án hội chẩn',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người bệnh cao tuổi, già yếu/cuối đời',N'Initial assessment for frail elderly/ end-of-life patient',N'InitialAssessmentForFrailElderly',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người bệnh truyền hóa chất',N'Initial assessment for chemotherapy patient',N'InitialAssessmentForChemotherapy',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kế hoạch điều trị và chăm sóc',N'Plan Of Care',N'PlanOfCare',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu chăm sóc',N'CareNote',N'CareNote',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn bệnh nhân sử dụng thuốc có dấu sao (*)',N'Minutes of consultation for patient using drug with an asterisk mark(*)',N'ConsultationDrugWithAnAsteriskMark',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu chăm sóc người bệnh Covid-19',N'Phiếu chăm sóc người bệnh Covid-19',N'TakeCareOfPatientsWithCovid19',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu sơ kết 15 ngày điều trị',N'Sumary Of 15 Day Treatment',N'SumaryOf15DayTreatment',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu trẻ nội trú nhi',N'Initial Assessment For Pediatric Inpatient',N'InitialAssessmentForPediatricInPatient',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án nhi khoa',N'Medical Record Pediatric',N'MedicalRecordPediatric',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'10',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án nội khoa',N'The General Internal Medical Record',N'MedicalRecord',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'11',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu trẻ sơ sinh nội trú',N'Initial Assessment For Neonatal',N'InitialAssessmentForNeonatal',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'12',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án sơ sinh',N'The Neonatal Medical Record',N'MedicalRecordNeonatal',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'13',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án sản khoa',N'The Obstetrics and Gynecology Medical Record',N'MedicalRecordObstetrics',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'14',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án phụ khoa',N'Medical Record Gynecological',N'MedicalRecordGynecological',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'15',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu cho trẻ vừa sinh',N'Initial Assessment For Neonatal Maternity',N'InitialAssessmentForNeonatalMaternity',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'16',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu sản phụ chuyển dạ',N'Initial assessment for women in labour',N'InitialAssessmentForPregnantWomen',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'17',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án ngoại khoa',N'The surgical medical record',N'TheSurgicalMedicalRecord',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'18',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án ung bướu',N'The Oncology Medical Record',N'MedicalRecordOncology',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'19',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu điều trị can thiệp động mạch vành',N'Coronary intervention',N'CoronaryIntervention',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'20',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án mắt',N'The Opthalmology Medical Record',N'MedicalRecordEye',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'21',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án Răng Hàm Mặt',N'The Dentistry Medical Record',N'A01_040_050919_V',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'22',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án Tai Mũi Họng',N'The ENT Medical Record',N'A01_039_050919_V',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'23',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản bàn giao người bệnh chuyển khoa',N'Patient hand over record',N'PatientHandOverRecord',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'24',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Theo dõi diến biến người bệnh',N'Patient Progress Note',N'PatientProgressNote',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'25',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người bệnh nội trú thông thường',N'Initial assessment for adult inpatient',N'InitialAssessmentForAudult',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'26',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thang đánh giá ý tưởng và mức độ ý tưởng tự sát',N'Thang đánh giá ý tưởng và mức độ ý tưởng tự sát',N'IPDScaleForAssessmentOfSuicideIntent',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'27',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Y lệnh ',N'IPD Y lệnh ',N'IPDYL',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu ghi nhận sử dụng thuốc do người bệnh mang vào',N'Patient Own Medications Chart',N'PatientOwnMedicationsChart',N'IPDYL',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu khai thác tiền sử dùng thuốc - Người lớn',N'Medication history form - Adult patient',N'MedicationHistoryForm',N'IPDYL',N'IPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu ghi nhân thuốc y lệnh miệng',N'Verbal Order Form',N'VerbalOrderForm',N'IPDYL',N'IPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu dự trù, cung cấp và xác nhận thực hiện máu - Chế phẩm máu',N'Blood Request Supply And Confirmation',N'BloodRequestSupplyAndConfirmation',N'IPDYL',N'IPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Theo dõi điều dưỡng',N'IPD Theo dõi điều dưỡng',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ ngã nội trú người lớn',N'Fall Risk Assessment Adult',N'FallRiskAssessmentForAdult',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ ngã nội trú sản',N'Fall Risk Assessment Obstetric',N'FallRiskAssessmentForObstetric',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho người lớn',N'Vital Signs For Adult Report',N'VitalSignsForAdult',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thang điểm GUSS đánh giá rối loạn nuốt cho người bệnh tại giường',N'Gugging swallowing screen',N'GuggingSwallowingScreen',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng điểm Braden đánh giá nguy cơ loét',N'Abbreviated Braden scale for predicting pressure score risk',N'BradenScale',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ nhi (1 - 3 tháng tuổi)',N'vital signs monitor for pediatric (1 to 3 month old)',N'VitalSignFor1To3',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ nhi (3 - 12 tháng tuổi)',N'vital signs monitor for pediatric (3 to 12 month old)',N'VitalSignFor3To12',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ nhi (1 - 4 tuổi)',N'vital signs monitor for pediatric (1 to 4 year old)',N'VitalSignFor1To4',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ nhi (4 - 12 tuổi)',N'vital signs monitor for pediatric (4 to 12 year old)',N'VitalSignFor4To12',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'10',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ nhi (trên 12 tuổi)',N'vital signs monitor for pediatric (12 years old and up)',N'VitalSignForOver12',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'11',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ thuyên tắc mạch',N'Thrombosis Risk Factor Assessment',N'ThrombosisRiskFactorAssessment',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'12',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng điểm GLAMORGAN sàng lọc loét do tỳ ép ở trẻ nhi và sơ sinh',N'Glamorgan pressure injury screening tool',N'GlamorganScaleForScreening',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'13',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho trẻ sơ sinh',N'Neonatal Observation Chart',N'NeonatalObservationChart',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'14',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng theo dõi dấu hiệu sinh tồn dành cho sản phụ',N'Vital Signs For Pregnant Woman',N'VitalSignsForPregnantWoman',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'15',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá thuyên tắc mạch bệnh nhân ngoại khoa',N'Thrombosis risk factor assessment for general surgery patients',N'ThrombosisRiskFactorAssessmentFor',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'16',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu theo dõi người bệnh thoát mạch thuốc điều trị ung thư',N'Monitoring sheet for patients with extravasation of cancer drugs',N'MonitoringSheetForPatientsWith',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'17',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu truyền máu',N'Blood Transfusion Checklist',N'BloodTransfusionChecklist',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'18',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Phẫu thuật, thủ thuật',N'IPD Phẫu thuật, thủ thuật',N'IPDPTTT',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu phẫu thuật/ thủ thuật',N'Surgery and procedure Note',N'ProcedureSummary',N'IPDPTTT',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng kiểm chuẩn bị và bàn giao NB trước phẫu thuật',N'Pre-Operative/Procedure handover checklist',N'PHC',N'IPDPTTT',N'IPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn thông qua mổ',N'Joint-Consultation for approval of surgery',N'JointConsultationForApprovalOfSurgery',N'IPDPTTT',N'IPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng kiểm an toàn phẫu thuật/thủ thuật',N'Surgical Procedure Safety Checklist',N'SurgicalProcedureSafetyChecklist',N'IPDPTTT',N'IPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Kết quả xét nghiệm',N'IPD Kết quả xét nghiệm',N'IPDKQXN',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xét nghiệm tại chỗ - Khí máu Cartridge CG4+',N'OnSiteTestCartridgeCG4+BloodGas',N'ArterialBloodGasTest',N'IPDKQXN',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xét nghiệm tai giuong_Sinh hoa mau',N'Xét nghiệm tai giuong_Sinh hoa mau',N'ChemicalBiologyTest',N'IPDKQXN',N'IPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Ra viện',N'IPD Ra viện',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển viện',N'Referral Letter',N'ReferralLetter',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển tuyến',N'Transfer Letter',N'TransferLetter',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo cáo y tế ra viện',N'Discharge Medical Report',N'DischargeMedicalReport',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy ra viện',N'Hospital discharge record',N'Discharged',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu GDSK cho NB và thân nhân',N'Patient and family education form',N'PFEF',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chứng nhận phẫu thuật',N'Surgery Certificate',N'SurgeryCertificate',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy xác nhận ra viện không theo chỉ định của bác sĩ',N'Discharge Againts Medical Advice',N'DischargeAgaintsMedicalAdvice',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng kiểm chuẩn bị ra viện',N'Hospital Discharge Checklist',N'DischargePreparationChecklist',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo cáo y tế',N'Medical Report',N'MedicalReport',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Khác',N'IPD Khác',N'IPDKHAC',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng hồi sinh tim phổi',N'Cardiac Arrest Record',N'CardiacArrestRecord',N'IPDKHAC',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng đánh giá nhu cầu trang thiết bị/ nhân lực vận chuyển ngoại viện',N'External Transportation Assessment',N'ExternalTransportationAssessment',N'IPDKHAC',N'IPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản - Trích biên bản kiểm thảo tử vong',N'Mortality Report',N'MortalityReport',N'IPDKHAC',N'IPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'IPD Biểu mẫu không thuộc HSBA',N'IPD Biểu mẫu không thuộc HSBA',N'IPDBMKTHSBA',N'IPDNHOMBIEUMAU',N'IPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chứng nhận thương tích',N'InjuryCertificate',N'InjuryCertificate',N'IPDBMKTHSBA',N'IPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');


Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Nhóm biểu mẫu',N'EOC Nhóm biểu mẫu',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Bệnh án hội chẩn',N'EOC Bệnh án hội chẩn',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người bệnh ngoại trú thông thường',N'Initial assessment for short term',N'InitialAssessmentForShortTerm',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người bệnh ngoại trú dài hạn',N'Initial assessment for on-going',N'InitialAssessmentForOnGoing',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu sàng lọc nguy cơ ngã',N'Fall risk screening',N'FallRiskScreening',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu khám ngoại trú',N'Outpatient examination note',N'OutpatientExaminationNote',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tóm tắt ca bệnh phức tạp',N'Complex Outpatient Case Summary',N'ComplexOutpatientCaseSummary',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản bào giao NB chuyển khoa',N'Hand Over Check List',N'HandOverCheckList',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Theo dõi diến biến người bệnh',N'Patient Progress Note',N'PatientProgressNote',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn',N'Joint Consultation Group Minutes',N'JointConsultationGroupMinutes',N'EOCBAHC',N'EOCNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Y lệnh ',N'EOC Y lệnh ',N'EOCYL',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi nhận thực hiện thuốc',N'Standing Order',N'StandingOrder',N'EOCYL',N'EOCNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Phẫu thuật thủ thuật',N'EOC Phẫu thuật thủ thuật',N'EOCPTTT',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu phẫu thuật/ thủ thuật',N'Surgery and procedure Note',N'ProcedureSummary',N'EOCPTTT',N'EOCNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bản kiểm bàn giao người bệnh trước mổ',N'Pre-Operative/Procedure handover checklist',N'PHC',N'EOCPTTT',N'EOCNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn thông qua mổ',N'Joint Consultation Group Minutes',N'JointConsultationGroupMinutes',N'EOCPTTT',N'EOCNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng kiểm an toàn phẫu thuật/thủ thuật',N'Surgical Procedure Safety Checklist',N'SurgicalProcedureSafetyChecklist',N'EOCPTTT',N'EOCNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Kết quả xét nghiệm',N'EOC Kết quả xét nghiệm',N'EOCKQXN',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả test da',N'Skin test result',N'SkinTestResult',N'EOCKQXN',N'EOCNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Ra viện',N'EOC Ra viện',N'EOCRAVIEN',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo cáo y tế',N'Medical Report',N'MedicalReport',N'EOCRAVIEN',N'EOCNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển viện',N'Referral Letter',N'ReferralLetter',N'EOCRAVIEN',N'EOCNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển tuyến',N'Transfer Letter',N'TransferLetter',N'EOCRAVIEN',N'EOCNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu GDSK cho NB và thân nhân',N'Phiếu GDSK cho NB và thân nhân',N'PFEF',N'EOCRAVIEN',N'EOCNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'EOC Khác',N'EOC Khác',N'EOCKHAC',N'EOCNHOMBIEUMAU',N'EOCNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng hồi sinh tim phổi',N'Cardiac Arrest Record',N'CardiacArrestRecord',N'EOCKHAC',N'EOCNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');


Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Nhóm biểu mẫu',N'ED Nhóm biểu mẫu',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Bệnh án hội chẩn',N'ED Bệnh án hội chẩn',N'EDBAHC',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phân loại cấp cứu ',N'Phân loại cấp cứu ',N'EmergencyTriageRecord',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Sàng lọc ngã',N'Sàng lọc ngã',N'FallRiskScreen',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Theo dõi diễn biến người bệnh',N'Theo dõi diễn biến người bệnh',N'PatientProgressNote',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng sàng lọc nguy cơ tự hại',N'Bảng sàng lọc nguy cơ tự hại',N'SelfHarmRiskScreeningTool',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án cấp cứu ngoại viện',N'Bệnh án cấp cứu ngoại viện',N'AmbulanceRunReport',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án cấp cứu',N'Bệnh án cấp cứu',N'ER0',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu chăm sóc',N'Phiếu chăm sóc',N'CareNote',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn',N'Biên bản hội chẩn',N'JointConsultationGroupMinutes',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn thuốc có dấu sao',N'Biên bản hội chẩn thuốc có dấu sao',N'ConsultationDrugWithAnAsteriskMark',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'10',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn sử dụng kháng sinh cần ưu tiên quản lý',N'Biên bản hội chẩn sử dụng kháng sinh cần ưu tiên quản lý',N'AssessmentForRetailServicePatient',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'11',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu điều trị',N'Phiếu điều trị',N'PhysicianNote',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'12',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Biểu mẫu không thuộc hồ sơ bệnh án',N'ED Biểu mẫu không thuộc hồ sơ bệnh án',N'EDBMKTHSBA',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chứng nhận thương tích',N'Giấy chứng nhận thương tích',N'InjuryCertificate',N'EDBMKTHSBA',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED kết quả xét nghiệm ',N'ED kết quả xét nghiệm ',N'EDKQXN',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả test da',N'Kết quả test da',N'SkinTestResult',N'EDKQXN',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xét nghiệm tại chỗ - Khí máu Cartridge CG4+',N'Xét nghiệm tại chỗ - Khí máu Cartridge CG4+',N'ArterialBloodGasTest',N'EDKQXN',N'EDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Xét nghiệm tai giuong_Sinh hoa mau',N'Xét nghiệm tai giuong_Sinh hoa mau',N'ChemicalBiologyTest',N'EDKQXN',N'EDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Khác',N'ED Khác',N'EDKHAC',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy xác nhận bệnh nhân cấp cứu',N'Giấy xác nhận bệnh nhân cấp cứu',N'EMCO',N'EDKHAC',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng hồi sinh tim phổi',N'Bảng hồi sinh tim phổi',N'CardiacArrestRecord',N'EDKHAC',N'EDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng đánh giá nhu cầu trang thiết bị/ nhân lực vận chuyển ngoại viện',N'Bảng đánh giá nhu cầu trang thiết bị/ nhân lực vận chuyển ngoại viện',N'ExternalTransportationAssessment',N'EDKHAC',N'EDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trích biên bản kiểm thảo tử vong',N'Trích biên bản kiểm thảo tử vong',N'MortalityReport',N'EDKHAC',N'EDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Thủ thuật phẫu thuật',N'ED Thủ thuật phẫu thuật',N'EDPTTT',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu thủ thuật phẫu thuật',N'Phiếu thủ thuật phẫu thuật',N'ProcedureSummary',N'EDPTTT',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng kiểm chuẩn bị và bàn giao NB trước phẫu thuật',N'Bảng kiểm chuẩn bị và bàn giao NB trước phẫu thuật',N'PHC',N'EDPTTT',N'EDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn thông qua mổ',N'Biên bản hội chẩn thông qua mổ',N'JointConsultationForApprovalOfSurgery',N'EDPTTT',N'EDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Ra viện ',N'ED Ra viện ',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển viện',N'Giấy chuyển viện',N'ReferralLetter',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển tuyến',N'Giấy chuyển tuyến',N'TransferLetter',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá kết thúc',N'Đánh giá kết thúc',N'DI0',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bàn giao vận chuyển',N'Bàn giao vận chuyển',N'MCA',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo cáo y tế',N'Báo cáo y tế',N'KLM',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo cáo y tế ra viện',N'Báo cáo y tế ra viện',N'DMR',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy ra viện ',N'Giấy ra viện ',N'NPQ',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu GDSK cho NB và thân nhân',N'Phiếu GDSK cho NB và thân nhân',N'PFEF',N'EDRAVIEN',N'EDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Theo dõi điều dưỡng',N'ED Theo dõi điều dưỡng',N'EDTDDD',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu truyền máu',N'Phiếu truyền máu',N'BloodTransfusionChecklist',N'EDTDDD',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'ED Y lệnh',N'ED Y lệnh',N'EDYL',N'EDNHOMBIEUMAU',N'EDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi nhận thực hiện thuốc',N'Ghi nhận thực hiện thuốc',N'StandingOrder',N'EDYL',N'EDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá người bệnh dịch vụ lẻ',N'Đánh giá người bệnh dịch vụ lẻ',N'AssessmentForRetailServicePatient',N'EDYL',N'EDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu ghi nhận thuốc y lệnh miệng',N'Phiếu ghi nhận thuốc y lệnh miệng',N'Order',N'EDYL',N'EDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu ghi nhận sử dụng thuốc do người bệnh mang vào',N'Phiếu ghi nhận sử dụng thuốc do người bệnh mang vào',N'PatientOwnMedicationsChart',N'EDYL',N'EDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu dự trù, cung cấp và xác nhận thực hiện máu - Chế phẩm máu',N'Phiếu dự trù, cung cấp và xác nhận thực hiện máu - Chế phẩm máu',N'BloodRequestSupplyAndConfirmation',N'EDYL',N'EDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD Nhóm biểu mẫu',N'OPD Nhóm biểu mẫu',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD Bệnh án hội chẩn',N'OPD Bệnh án hội chẩn',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người bệnh ngoại trú thông thường',N'InitialAssessmentForShortTerm',N'InitialAssessmentForShortTerm',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người chăm sóc từ xa',N'InitialAssessmentForTelehealth',N'InitialAssessmentForTelehealth',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá ban đầu người bệnh ngoại trú dài hạn',N'InitialAssessmentForOnGoing',N'InitialAssessmentForOnGoing',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu khám ngoại trú',N'OutpatientExaminationNote',N'OutpatientExaminationNote',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tóm tắt ca bệnh phức tạp',N'ComplexOutpatientCaseSummary',N'ComplexOutpatientCaseSummary',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn',N'JointConsultationGroupMinutes',N'JointConsultationGroupMinutes',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bản kiểm bàn giao người bệnh trước mổ',N'Pre-Operative/Procedure handover checklist',N'PHC',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'8',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thêm theo dõi diễn biến người bệnh',N'Thêm theo dõi diễn biến người bệnh',N'PatientProgressNote',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD y lệnh',N'OPDYL',N'OPDYL',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá người bệnh dịch vụ lẻ',N'AssessmentForRetailServicePatient',N'AssessmentForRetailServicePatient',N'OPDYL',N'OPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi nhận thực hiện thuốc NB sử dụng dịch vụ lẻ',N'StandingOrderForRetailService',N'StandingOrderForRetailService',N'OPDYL',N'OPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi nhận thực hiện thuốc',N'StandingOrder',N'StandingOrder',N'OPDYL',N'OPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD Phẫu thuật, thủ thuật',N'OPD Phẫu thuật, thủ thuật',N'OPDPTTT',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu phẫu thuật/ thủ thuật',N'ProcedureSummary',N'ProcedureSummary',N'OPDPTTT',N'OPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bản kiểm bàn giao người bệnh trước mổ',N'Pre-Operative/Procedure handover checklist',N'PHC',N'OPDPTTT',N'OPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng kiểm an toàn phẫu thuật/thủ thuật',N'SurgicalProcedureSafetyChecklist',N'SurgicalProcedureSafetyChecklist',N'OPDPTTT',N'OPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD Kết quả xét nghiệm',N'OPD Kết quả xét nghiệm',N'OPDKQXN',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Kết quả test da',N'SkinTestResult',N'SkinTestResult',N'OPDKQXN',N'OPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD Ra viện',N'OPD Ra viện',N'OPDRAVIEN',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo cáo y tế',N'Medical report',N'MedicalReport',N'OPDRAVIEN',N'OPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển viện',N'Referral Letter',N'ReferralLetter',N'OPDRAVIEN',N'OPDNHOMBIEUMAU',N'2',N'3',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy chuyển tuyến',N'Transfer Letter',N'TransferLetter',N'OPDRAVIEN',N'OPDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'OPD Khác',N'OPD Khác',N'OPDKHAC',N'OPDNHOMBIEUMAU',N'OPDNHOMBIEUMAU',N'1',N'1',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bảng hồi sinh tim phổi',N'Cardiac Arrest Record',N'CardiacArrestRecord',N'OPDKHAC',N'OPDNHOMBIEUMAU',N'2',N'2',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu đánh giá tiêu chuẩn chỉ định xét nghiệm GEN BRCA ',N'Phiếu đánh giá tiêu chuẩn chỉ định xét nghiệm GEN BRCA ',N'GENBRCA',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu khai thác tiền sử dùng thuốc bệnh - Nhi',N'Phiếu khai thác tiền sử dùng thuốc bệnh - Nhi',N'MedicationHistoryFormPediatricPatient',N'IPDYL',N'IPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Sàng lọc ngã',N'Fall Risk Screening',N'FallRiskScreening',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'9',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu điều trị',N'Physician Note',N'PhysicianNote',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'26',N'Label',N'',N'',N'',N'', '');

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản bàn giao người bệnh chuyển khoa',N'Hand over check list',N'HandOverCheckList',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'10',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản bàn giao người bệnh chuyển khoa',N'Patient hand over record',N'PatientHandOverRecord',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'13',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu',N'Report Coordinating with the patient/ family to deal with a stillbirth',N'CoordinatingWithThePatient',N'IPDRAVIEN',N'IPDNHOMBIEUMAU',N'2',N'10',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản phối hợp với bệnh nhân/ gia đình xử lý thai chết lưu',N'Report Coordinating with the patient/ family to deal with a stillbirth',N'CoordinatingWithThePatient',N'OPDRAVIEN',N'OPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu tóm tắt thủ thuật',N'Phiếu tóm tắt thủ thuật',N'TrickSummary',N'IPDPTTT',N'IPDNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu tóm tắt thủ thuật',N'Phiếu tóm tắt thủ thuật',N'TrickSummary',N'EOCPTTT',N'EOCNHOMBIEUMAU',N'2',N'6',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu tóm tắt thủ thuật',N'Phiếu tóm tắt thủ thuật',N'TrickSummary',N'EDPTTT',N'EDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu tóm tắt thủ thuật',N'Phiếu tóm tắt thủ thuật',N'TrickSummary',N'OPDPTTT',N'OPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy có ngã của thai phụ nội trú sản',N'Đánh giá nguy có ngã của thai phụ nội trú sản',N'FallRiskAssessmentForObstetric',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'18',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn sử dụng kháng sinh cần ưu tiên quản lý',N'Biên bản hội chẩn sử dụng kháng sinh cần ưu tiên quản lý',N'HighlyRestrictedAntimicrobialConsult',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'13',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn sử dụng kháng sinh cần ưu tiên quản lý',N'Biên bản hội chẩn sử dụng kháng sinh cần ưu tiên quản lý',N'HighlyRestrictedAntimicrobialConsult',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'28',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi nhận thực hiện thuốc NB sử dụng dịch vụ lẻ',N'Ghi nhận thực hiện thuốc NB sử dụng dịch vụ lẻ',N'StandingOrderForRetailService',N'EDYL',N'EDNHOMBIEUMAU',N'2',N'7',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu dự trù, cung cấp và xác nhận thực hiện máu - Chế phẩm máu',N'Phiếu dự trù, cung cấp và xác nhận thực hiện máu - Chế phẩm máu',N'BloodRequestSupplyAndConfirmation',N'EDBMKTHSBA',N'EDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu truyền máu',N'Phiếu truyền máu',N'BloodTransfusionChecklist',N'EDKHAC',N'EDNHOMBIEUMAU',N'2',N'4',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tóm tắt ca bệnh phức tạp',N'Tóm tắt ca bệnh phức tạp',N'ComplexOutpatientCaseSummary',N'EDBAHC',N'EDNHOMBIEUMAU',N'2',N'14',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu đánh giá nguy cơ di truyền trong sàng lọc ung thư vú',N'Phiếu đánh giá nguy cơ di truyền trong sàng lọc ung thư vú',N'NCCNBROV1',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'11',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu thông tin khách hàng - Đánh giá nguy cơ ung thư',N'Phiếu thông tin khách hàng - Đánh giá nguy cơ ung thư',N'PatientInformationTheRiskAssessmentForCancer',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'12',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu khám lâm sàng vú',N'Phiếu khám lâm sàng vú',N'CBE',N'OPDBAHC',N'OPDNHOMBIEUMAU',N'2',N'13',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phiếu giáo dục sức khỏe cho người bệnh và thân nhân',N'Phiếu giáo dục sức khỏe cho người bệnh và thân nhân',N'PFEF',N'OPDRAVIEN',N'OPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');

--- update sửa nhóm HSBA
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản hội chẩn',N'Biên bản hội chẩn',N'JointConsultationGroupMinutes',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'30',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Biên bản bào giao NB chuyển khoa',N'Biên bản bào giao NB chuyển khoa',N'HandOverCheckList',N'IPDBAHC',N'IPDNHOMBIEUMAU',N'2',N'31',N'Label',N'',N'',N'',N'', '');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đánh giá nguy cơ ngã NB nội trú trẻ em ',N'Đánh giá nguy cơ ngã NB nội trú trẻ em ',N'FallRiskAssessmentInPediatricInpatients',N'IPDTDDD',N'IPDNHOMBIEUMAU',N'2',N'20',N'Label',N'',N'',N'',N'', '');

delete from MasterDatas
where Code = 'BloodTransfusionChecklist'
and [Group] = 'EDTDDD'

update MasterDatas set [Group] = 'IPDKHAC'
where Code = 'BloodTransfusionChecklist'
and [Group] = 'IPDTDDD'

update MasterDatas set [Group] = 'IPDBMKTHSBA'
where Code = 'BloodRequestSupplyAndConfirmation'
and [Group] = 'IPDYL'

delete from MasterDatas 
where Code = 'JointConsultationGroupMinutes'
and [Group] = 'EOCPTTT'

update MasterDatas set Code = 'Discharged'
where Code = 'NPQ'

update MasterDatas set Code = 'DischargeMedicalReport'
where Code = 'DMR'

update MasterDatas set Code = 'MedicalReport'
where Code = 'KLM'
------

delete from MasterDatas
where Code = 'BloodRequestSupplyAndConfirmation'
and [Group] = 'EDYL'

delete from MasterDatas
where Code = 'AssessmentForRetailServicePatient'
and [Group] = 'EDBAHC'

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giấy xác nhận bệnh tật',N'Giấy xác nhận bệnh tật',N'DiseasesCertification',N'OPDRAVIEN',N'OPDNHOMBIEUMAU',N'2',N'5',N'Label',N'',N'',N'',N'', '');

-- Giấy ra viện của ED
insert into FormOfPatients(ViName, EnName, TypeName, Area, ViStatusPatient, EnStatusPatient, [Order])
values(N'Giấy ra viện', N'Hospital discharge record', 'Discharged', 'ED', N'Ra viện', 'Discharged', 27)
,(N'Giấy ra viện', N'Hospital discharge record', 'Complete treatment', 'ED', N'Kết thúc điều trị', 'Complete treatment', 28)

--update tiếp Nhom HSBA tiếp
delete from MasterDatas
where Code = 'PHC' and [Group] = 'OPDBAHC'