// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class discharge_inforati : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(discharge_inforati));
        
        string IMigrationMetadata.Id
        {
            get { return "201912030954566_discharge_inforati"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
