// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class chot_lan_n : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chot_lan_n));
        
        string IMigrationMetadata.Id
        {
            get { return "201912160919345_chot_lan_n"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
