// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addreasonandprimarynurse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreasonandprimarynurse));
        
        string IMigrationMetadata.Id
        {
            get { return "202006170722449_add-reason-and-primary-nurse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
