// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addm2muserposition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addm2muserposition));
        
        string IMigrationMetadata.Id
        {
            get { return "202007290809000_add-m2m-user-position"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
