// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatelogremovelogdetailaddbloodchecklist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatelogremovelogdetailaddbloodchecklist));
        
        string IMigrationMetadata.Id
        {
            get { return "202008260459356_update-log-remove-logdetail-add-bloodchecklist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
