// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addipdfallriskassessmentobstetric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addipdfallriskassessmentobstetric));
        
        string IMigrationMetadata.Id
        {
            get { return "202011120309097_add-ipd-fall-risk-assessment-obstetric"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
