// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatepatientfamilyeducationform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatepatientfamilyeducationform));
        
        string IMigrationMetadata.Id
        {
            get { return "202004080736445_update-patient-family-education-form"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
