// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatehandoverchecklist2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatehandoverchecklist2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002260949115_update-hand-over-check-list-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
