// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateeiojointconsultantforapproval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateeiojointconsultantforapproval));
        
        string IMigrationMetadata.Id
        {
            get { return "202012290742303_update-eio-joint-consultant-for-approval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
