// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adduseradminroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduseradminroles));
        
        string IMigrationMetadata.Id
        {
            get { return "202002170855489_add-user-admin-roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
