// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateipdinitialassessment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateipdinitialassessment));
        
        string IMigrationMetadata.Id
        {
            get { return "202010080833185_update-ipd-initial-assessment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
