// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_joint_consultation_group_minute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_joint_consultation_group_minute));
        
        string IMigrationMetadata.Id
        {
            get { return "202008180316597_update_joint_consultation_group_minute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
