// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatekindofallrgy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatekindofallrgy));
        
        string IMigrationMetadata.Id
        {
            get { return "202007140738243_update-kind-of-allrgy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
