// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateipdspecialrequestiskey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateipdspecialrequestiskey));
        
        string IMigrationMetadata.Id
        {
            get { return "202010170455366_update-ipd-special-request-is-key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
