// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addnurseconfirmorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnurseconfirmorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202009150709507_add-nurse-confirm-order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
