// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newtablecovid19takeofcare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtablecovid19takeofcare));
        
        string IMigrationMetadata.Id
        {
            get { return "202109210229200_new-table-covid19-takeofcare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
