// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTestCovid2ConfirmationForeignonedopd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTestCovid2ConfirmationForeignonedopd));
        
        string IMigrationMetadata.Id
        {
            get { return "202105260347390_add-TestCovid2Confirmation-Foreign-on-ed-opd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
