// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatepreoperativeprocedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatepreoperativeprocedure));
        
        string IMigrationMetadata.Id
        {
            get { return "202103180336272_update-pre-operative-procedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
