// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createnewtableConfirmDischarge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createnewtableConfirmDischarge));
        
        string IMigrationMetadata.Id
        {
            get { return "202112151013471_create-new-table-ConfirmDischarge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
