// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addsystemconfigandnotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsystemconfigandnotification));
        
        string IMigrationMetadata.Id
        {
            get { return "202101070253134_add-system-config-and-notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
