// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtranferendoscopy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtranferendoscopy));
        
        string IMigrationMetadata.Id
        {
            get { return "202107070723222_add-tranfer-endoscopy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
