// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addipddischargechecklisttables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addipddischargechecklisttables));
        
        string IMigrationMetadata.Id
        {
            get { return "202111100435209_add-ipd-discharge-checklist-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
