// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mergerhiddenviptosprint17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mergerhiddenviptosprint17));
        
        string IMigrationMetadata.Id
        {
            get { return "202203300423068_merger-hidden-vipto-sprint17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
