// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_field_inventionOther_Glamorgan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_field_inventionOther_Glamorgan));
        
        string IMigrationMetadata.Id
        {
            get { return "202206210925525_update_field_inventionOther_Glamorgan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
