// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatevisitcol2nnn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatevisitcol2nnn));
        
        string IMigrationMetadata.Id
        {
            get { return "202201020853444_update-visit-col-2nnn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
