// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_tbl_IpdSumOf15DayTreatMemnt_and_tbl_ipd_MedicationHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_tbl_IpdSumOf15DayTreatMemnt_and_tbl_ipd_MedicationHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202203150314281_change_tbl_IpdSumOf15DayTreatMemnt_and_tbl_ipd_MedicationHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
