// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_tbl_IPDApgar_IPDAddessed_IPDDeliveryMethod_IPDLabour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tbl_IPDApgar_IPDAddessed_IPDDeliveryMethod_IPDLabour));
        
        string IMigrationMetadata.Id
        {
            get { return "202204010237100_add_tbl_IPDApgar_IPDAddessed_IPDDeliveryMethod_IPDLabour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
