// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetableEIOMortalityReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetableEIOMortalityReport));

        public string Source { get; set; }

        public string Target { get; set; }

        string IMigrationMetadata.Id
        {
            get
            {
                return "202201130917148_update-table-EIOMortalityReport";
            }
        }
    }
    public sealed partial class mergrdbtoprod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mergrdbtoprod));
        
        string IMigrationMetadata.Id
        {
            get { return "202201130958558_mergr-db-to-prod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
