INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'Bệnh án Răng Hàm Mặt', 'A01_040_050919_V', 'IPD')

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án Răng Hàm Mặt',N'Dental medical record',N'A01_040_050919_V',N'MedicalRecords',N'A01_040_050919_V',N'',N'',N'',N'',N'0',N'',N'', '1');

INSERT INTO [dbo].[Forms]([Id], [IsDeleted], [CreatedAt], [UpdatedAt], [Name], [Code], [VisitTypeGroupCode]) VALUES (NEWID(), 0, '2022-03-03 00:00:00.000', '2022-03-03 00:00:00.000',N'Bệnh án Tai Mũi Họng', 'A01_039_050919_V', 'IPD')

Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh án Tai Mũi Họng',N'The Ear, Nose, Throat medical record',N'A01_039_050919_V',N'MedicalRecords',N'A01_039_050919_V',N'',N'',N'',N'',N'0',N'',N'', '1');


Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh chuyên khoa',N'Bệnh chuyên khoa',N'IPDMRPT10000',N'IPDMRPT',N'IPDMRPT',N'1',N'10000',N'Label',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh chuyên khoa',N'Bệnh chuyên khoa',N'IPDMRPT10001',N'IPDMRPT10000',N'IPDMRPT',N'2',N'10001',N'Text',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hình vẽ mô tả tổn thương khi vào viện',N'Hình vẽ mô tả tổn thương khi vào viện',N'IPDMRPT10002',N'IPDMRPT',N'IPDMRPT',N'1',N'10002',N'Label',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Màng nhĩ phải',N'Màng nhĩ phải',N'IPDMRPT10003',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10003',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Màng nhĩ phải',N'Màng nhĩ phải',N'IPDMRPT10004',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10004',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Màng nhĩ trái',N'Màng nhĩ trái',N'IPDMRPT10005',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10005',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Màng nhĩ trái',N'Màng nhĩ trái',N'IPDMRPT10006',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10006',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mũi Trước',N'Mũi Trước',N'IPDMRPT10007',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10007',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mũi Trước',N'Mũi Trước',N'IPDMRPT10008',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10008',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mũi Sau',N'Mũi Sau',N'IPDMRPT10009',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10009',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Mũi Sau',N'Mũi Sau',N'IPDMRPT10010',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10010',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thanh quản',N'Thanh quản',N'IPDMRPT10011',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10011',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thanh quản',N'Thanh quản',N'IPDMRPT10012',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10012',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Họng',N'Họng',N'IPDMRPT10013',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10013',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Họng',N'Họng',N'IPDMRPT10014',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10014',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cổ nghiêng phải',N'Cổ nghiêng phải',N'IPDMRPT10015',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10015',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cổ nghiêng phải',N'Cổ nghiêng phải',N'IPDMRPT10016',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10016',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cổ nghiêng trái',N'Cổ nghiêng trái',N'IPDMRPT10017',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10017',N'UploadFiles',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cổ nghiêng trái',N'Cổ nghiêng trái',N'IPDMRPT10018',N'IPDMRPT10002',N'IPDMRPT',N'2',N'10018',N'Painting',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'+ Tâm thần, thần kinh',N'+ Tâm thần, thần kinh',N'IPDMRPT10019',N'IPDMRPT',N'IPDMRPT',N'1',N'10019',N'Label',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'+ Tâm thần, thần kinh',N'+ Tâm thần, thần kinh',N'IPDMRPT10020',N'IPDMRPT10019',N'IPDMRPT',N'2',N'10020',N'Text',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'+ Da và mô dưới da',N'+ Da và mô dưới da',N'IPDMRPT10021',N'IPDMRPT',N'IPDMRPT',N'1',N'10021',N'Label',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'+ Da và mô dưới da',N'+ Da và mô dưới da',N'IPDMRPT10022',N'IPDMRPT10021',N'IPDMRPT',N'2',N'10022',N'Text',N'',N'0',N'',N'A01_039_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh chuyên khoa',N'Bệnh chuyên khoa',N'IPDMRPT10023',N'IPDMRPT',N'IPDMRPT',N'1',N'10023',N'Label',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bệnh chuyên khoa',N'Bệnh chuyên khoa',N'IPDMRPT10024',N'IPDMRPT10023',N'IPDMRPT',N'2',N'10024',N'Text',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hình vẽ mô tả tổn thương khi vào viện',N'Hình vẽ mô tả tổn thương khi vào viện',N'IPDMRPT10025',N'IPDMRPT',N'IPDMRPT',N'1',N'10002',N'Label',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phải',N'Phải',N'IPDMRPT10026',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10025',N'UploadFiles',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phải',N'Phải',N'IPDMRPT10027',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10026',N'Painting',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thẳng',N'Thẳng',N'IPDMRPT10028',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10027',N'UploadFiles',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Thẳng',N'Thẳng',N'IPDMRPT10029',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10028',N'Painting',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trái',N'Trái',N'IPDMRPT10030',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10029',N'UploadFiles',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Trái',N'Trái',N'IPDMRPT10031',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10030',N'Painting',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hàm trên và họng',N'Hàm trên và họng',N'IPDMRPT10032',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10031',N'UploadFiles',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hàm trên và họng',N'Hàm trên và họng',N'IPDMRPT10033',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10032',N'Painting',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hàm dưới',N'Hàm dưới',N'IPDMRPT10034',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10033',N'UploadFiles',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Hàm dưới',N'Hàm dưới',N'IPDMRPT10035',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10034',N'Painting',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phân loại khe hở môi và miệng',N'Phân loại khe hở môi và miệng',N'IPDMRPT10036',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10035',N'UploadFiles',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Phân loại khe hở môi và miệng',N'Phân loại khe hở môi và miệng',N'IPDMRPT10036',N'IPDMRPT10025',N'IPDMRPT',N'2',N'10035',N'UploadFiles',N'',N'0',N'',N'A01_040_050919_V', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cơ quan khác',N'Cơ quan khác',N'IPDMRPT10037',N'IPDMRPT',N'IPDMRPT',N'1',N'10036',N'Label',N'',N'0',N'',N'A01_040_050919_V', '1');



